### ISSUE TITLE
Chown Output Directory

### ISSUE THREAD

**Issue by MostAttack** [Veil-Framework/Veil-Evasion#100]
Good days.
 I can't win this problem while install (according to http://www.youtube.com/watch?v=XWrw_I38fd0):
 
[*] Path '/etc/veil/' Created
Configuration File Written To '/etc/veil/settings.py'
chown: cannot access `/root/veil-output': No such file or directory﻿

**Comment by ChrisTruncer** [comment]
Hello,

Are you running as root, and are you using the latest version of Veil-Evasion? The latest version doesn't output anything to /root/*

**Comment by MostAttack** [comment]
Hello.
Yes, I am running as root on latest Kali Linux x86 (1.0.9a). And I am using the latest version of Veil-Evasion from here (git clone https://github.com/Veil-Framework/Veil-Evasion.git and so on according to your youtube manual).

So I have problem in this line https://github.com/Veil-Framework/Veil-Evasion/blob/master/setup/setup.sh#L240 . Why? And how to fix it?

**Comment by ChrisTruncer** [comment]
I believe that this should be fixed now with the merged in patch.  Let me know if you are having any more issues.
