### ISSUE TITLE
pyherion encrypting fails du to missing "encryption" module import in auxiliary/pyinstaller_wrapper.py

### ISSUE THREAD

**Issue by Herrsatz** [Veil-Framework/Veil-Evasion#101]
Hi,

Downloaded the the latest kali-approved (2.13.4) version of veil-evasion and tried to use the auxiliary/pyinstaller_wrapper to generate a pwnstaller version of a custom Python script.
When setting the "use_pyherion" parameter to "Y", I get an exception: "Name Error: global name 'encryption' is not defined" in the file "pyinstaller_wrapper.py".

I also cloned the latest version from GitHub and the error is still present.

Fix is very simple to implement:
Replace this line:
from modules.common import helpers
By this line:
from modules.common import helpers, encryption

**Comment by ChrisTruncer** [comment]
Awesome, thanks for reporting this in to us, should be a quick fix (thanks for providing the fix too :))

**Comment by Herrsatz** [comment]
You're welcome!
Thanks for the great work.

**Comment by ChrisTruncer** [comment]
merged in the fix, thanks again for reporting this!
