### ISSUE TITLE
no compiled payloads

### ISSUE THREAD

**Issue by listen2me** [Veil-Framework/Veil-Evasion#104]
Hi
Well I have this problem, when I try to generate a payload, it gives me the mesg that my payload has been generated and put into the compiled directory, but when i get there i can't find anything.
But when I check the source and handler directories a find the files concerning my payload, but the compiled payload who supposed to be .exe doesn't exist in the complied directory help me please

**Comment by ChrisTruncer** [comment]
Hello, you didn't give enough information for us to help you.

Please make a payload, then copy every step you took from your console into pastebin, and post your pastebin link here for us to look at.

**Comment by listen2me** [comment]
probleme solved I just reinstalled kali and veil, now it's working just fine Thanks anyway
