### ISSUE TITLE
when i am trying to give this command "root@kali:~/Desktop/Veil-Evasion# ./Veil-Evasion.py " it is giving the following errors 

### ISSUE THREAD

**Issue by maheshtata** [Veil-Framework/Veil-Evasion#106]
=========================================================================
 Veil-Evasion | [Version]: 2.16.0
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

Traceback (most recent call last):
  File "./Veil-Evasion.py", line 278, in <module>
    controller = controller.Controller(oneRun=False)
  File "/root/Desktop/Veil-Evasion/modules/common/controller.py", line 127, in __init__
    self.LoadPayloads()
  File "/root/Desktop/Veil-Evasion/modules/common/controller.py", line 139, in LoadPayloads
    d = dict( (path[path.find("payloads")+9:-3], imp.load_source( "/".join(path.split("/")[3:])[:-3],path )  ) for path in glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" * x,'[!_]*.py')) )
  File "/root/Desktop/Veil-Evasion/modules/common/controller.py", line 139, in <genexpr>
    d = dict( (path[path.find("payloads")+9:-3], imp.load_source( "/".join(path.split("/")[3:])[:-3],path )  ) for path in glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" * x,'[!_]*.py')) )
  File "/root/Desktop/Veil-Evasion//modules/payloads/native/backdoor_factory.py", line 14, in <module>
    from tools.backdoor import pebin
  File "/root/Desktop/Veil-Evasion/tools/backdoor/pebin.py", line 42, in <module>
    import pefile
ImportError: No module named pefile

**Comment by secretsquirrel** [comment]
How did you install Veil?


On Feb 4, 2015, at 5:55 AM, maheshtata <notifications@github.com> wrote:

 Veil-Evasion | [Version]: 2.16.0 [Web]: https://www.veil-framework.com/ |
[Twitter]: @VeilFramework

Traceback (most recent call last):
File "./Veil-Evasion.py", line 278, in
controller = controller.Controller(oneRun=False)
File "/root/Desktop/Veil-Evasion/modules/common/controller.py", line 127,
in *init*
self.LoadPayloads()
File "/root/Desktop/Veil-Evasion/modules/common/controller.py", line 139,
in LoadPayloads
d = dict( (path[path.find("payloads")+9:-3], imp.load_source(
"/".join(path.split("/")[3:])[:-3],path ) ) for path in
glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" *
x,'[!_]*.py')) )
File "/root/Desktop/Veil-Evasion/modules/common/controller.py", line 139,
in
d = dict( (path[path.find("payloads")+9:-3], imp.load_source(
"/".join(path.split("/")[3:])[:-3],path ) ) for path in
glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" *
x,'[!_]*.py')) )
File
"/root/Desktop/Veil-Evasion//modules/payloads/native/backdoor_factory.py",
line 14, in
from tools.backdoor import pebin
File "/root/Desktop/Veil-Evasion/tools/backdoor/pebin.py", line 42, in
import pefile
ImportError: No module named pefile

—
Reply to this email directly or view it on GitHub
<https://github.com/Veil-Framework/Veil-Evasion/issues/106>.

**Comment by ChrisTruncer** [comment]
I don't think you ran the setup script, or have the latest version. This issue has already been discussed before, and it was just a matter of running the setup script to install the latest dependencies.

**Comment by maheshtata** [comment]
i installed the setup and then when i try to run the veil-evasion.py it is giving this error

**Comment by ChrisTruncer** [comment]
then manually install it

**Comment by ChrisTruncer** [comment]
I don't think you have the latest version.  Please clone it off of github and then re-run

**Comment by maheshtata** [comment]
i have done it 5 times

**Comment by ChrisTruncer** [comment]
This is something isolated to your environment.  We've had people with this issue before, and you just need to make sure you have the latest backdoor factory that we have in the repo.

Please try running it again, or try in a different VM.  But this is isolated to your environment.
