### ISSUE TITLE
Not issue, only is suggestion

### ISSUE THREAD

**Issue by discipuloosho** [Veil-Framework/Veil-Evasion#109]
Would you like to make one option to implement TOR in generate payload? It would be interesting. Thanks and close issue if you see fit.

**Comment by ChrisTruncer** [comment]
Hi,

We haven't added integration for that since we haven't seen a legitimate reason to do so as of yet.

**Comment by discipuloosho** [comment]
I think it's very interesting when concerned anonymous attacker. Many hackers fighting dirty governments and companies , and anonymity is indispensable. No more , thanks for Veil .
