### ISSUE TITLE
metsrv.*.dll no longer in metasploit dir

### ISSUE THREAD

**Issue by Meatballs1** [Veil-Framework/Veil-Evasion#110]
Has been moved to the meterpreter-bins gem. 

Causes crash when trying to use contained payloads.

**Comment by ChrisTruncer** [comment]
OK,

Thanks for the heads up. This should be a fast fix

**Comment by ChrisTruncer** [comment]
Quick question for you.  I'm checking out the path in Kali (primary platform we develop this for) and it looks like I can still access it here: /usr/share/metasploit-framework/vendor/bundle/ruby/2.1.0/gems/meterpreter_bins-0.0.14/meterpreter/metsrv.x86.dll (as of writing this)

Is this the best location that we should use?  I realize every update we're going to have to update this path, so I wanted to check with you on best way to grab this.
