### ISSUE TITLE
./setup/setup.sh: line 264: cd: ../config: No such file or directory

### ISSUE THREAD

**Issue by andyrat33** [Veil-Framework/Veil-Evasion#112]
Error during setup on Kali 64bit
./setup/setup.sh: line 264: cd: ../config: No such file or directory
python: can't open file 'update.py': [Errno 2] No such file or directory
root@kali:~/Veil-Evasion# 

root@kali:~/Veil-Evasion# ls -la
total 6708
drwxr-xr-x  8 root root    4096 Feb 26 17:18 .
drwx------ 30 root root    4096 Feb 26 17:18 ..
-rw-r--r--  1 root root   12477 Feb 26 16:51 CHANGELOG
drwxr-xr-x  2 root root    4096 Feb 26 16:51 config
-rw-r--r--  1 root root   33465 Feb 26 16:51 COPYRIGHT
drwxr-xr-x  8 root root    4096 Feb 26 16:51 .git
drwxr-xr-x  4 root root    4096 Feb 26 16:51 modules
-rw-r--r--  1 root root 6755644 May 28  2013 pywin32-218.win32-py2.7.exe
-rw-r--r--  1 root root    2206 Feb 26 16:51 README.md
drwxr-xr-x  2 root root    4096 Feb 26 16:51 setup
drwxr-xr-x  2 root root    4096 Feb 26 16:51 testbins
drwxr-xr-x  7 root root    4096 Feb 26 16:51 tools
-rw-r--r--  1 root root      84 Feb 26 16:51 .travis.yml
-rwxr-xr-x  1 root root   14793 Feb 26 16:51 Veil-Evasion.py
root@kali:~/Veil-Evasion# cd config/
root@kali:~/Veil-Evasion/config# ls
__init__.py  update.py
root@kali:~/Veil-Evasion/config# ./update.py 

 Veil-Framework configuration:

 [*] OPERATING_SYSTEM = Kali
 [*] TERMINAL_CLEAR = clear
 [*] TEMP_DIR = /tmp/
 [*] MSFVENOM_OPTIONS = 
 [*] METASPLOIT_PATH = /usr/share/metasploit-framework/
 [*] PYINSTALLER_PATH = /opt/pyinstaller-2.0/

 [*] VEIL_EVASION_PATH = /root/Veil-Evasion/
 [*] PAYLOAD_SOURCE_PATH = /usr/share/veil-output/source/
 [*] Path '/usr/share/veil-output/source/' Created
 [*] PAYLOAD_COMPILED_PATH = /usr/share/veil-output/compiled/
 [*] Path '/usr/share/veil-output/compiled/' Created
 [*] Path '/usr/share/veil-output/handlers/' Created
 [*] GENERATE_HANDLER_SCRIPT = True
 [*] HANDLER_PATH = /usr/share/veil-output/handlers/
 [*] HASH_LIST = /usr/share/veil-output/hashes.txt

 [*] VEIL_CATAPULT_PATH = /root/Veil-Catapult/
 [*] Path '/usr/share/veil-output/catapult/' Created
 [*] CATAPULT_RESOURCE_PATH = /usr/share/veil-output/catapult/

 [*] Path '/etc/veil/' Created
 Configuration File Written To '/etc/veil/settings.py'

**Comment by ChrisTruncer** [comment]
I just tested this out, and everything works for me.  Just make sure to run setup script within the setup folder.
