### ISSUE TITLE
Problem with rev_https.py

### ISSUE THREAD

**Issue by martin009** [Veil-Framework/Veil-Evasion#118]
Hi

The logic to turn off the certificate validation does not work in the rev_https.py payload 

I have tried to test the payload against a win 7 machine which goes through a squid proxy.

When I set the squid proxy in standard non ssl mode the payload works just fine but when I use a selfsign ssl certificate and do a ssl bump in the squid I get this.

fwdNegotiateSSL: Error negotiating SSL connection on FD 12: error:xxxx:SSL routings:SSL3_GET_SERVER_CERTIFICATE: certificate verify failed.

Any ideas were the error is in this code?

validateServerCertficateName = helpers.randomString()
payloadCode += "private static bool %s(object sender, System.Security.Cryptography.X509Certificates.X509Certificate cert, System.Security.Cryptography.X509Certificates.X509Chain chain, System.Net.Security.SslPolicyErrors sslPolicyErrors) { return true; }\n" %(validateServerCertficateName)

payloadCode += "ServicePointManager.ServerCertificateValidationCallback = %s;\n" %(validateServerCertficateName)

**Comment by ChrisTruncer** [comment]
Hm... to be honest, I'm not sure.  We haven't run into this issue anywhere yet, and I don't have a setup currently to test this

**Comment by ChrisTruncer** [comment]
I'm going to close this for the time being, but doesn't mean it can't be re-opened.  Also, it won't be locked so further discussion can be had on this.
