### ISSUE TITLE
ImportError: No module named pefile

### ISSUE THREAD

**Issue by lgcambero** [Veil-Framework/Veil-Evasion#119]
Hello, I have a problem installing Veil Evasion in a clean and up-to-date virtual machine, the error is:

=========================================================================
 Veil-Evasion | [Version]: 2.17.0
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

Traceback (most recent call last):
  File "./Veil-Evasion.py", line 283, in <module>
    controller = controller.Controller(oneRun=False)
  File "/root/Veil/Veil-Evasion/modules/common/controller.py", line 129, in __init__
    self.LoadPayloads()
  File "/root/Veil/Veil-Evasion/modules/common/controller.py", line 141, in LoadPayloads
    d = dict( (path[path.find("payloads")+9:-3], imp.load_source( "/".join(path.split("/")[3:])[:-3],path )  ) for path in glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" * x,'[!_]*.py')) )
  File "/root/Veil/Veil-Evasion/modules/common/controller.py", line 141, in <genexpr>
    d = dict( (path[path.find("payloads")+9:-3], imp.load_source( "/".join(path.split("/")[3:])[:-3],path )  ) for path in glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" * x,'[!_]*.py')) )
  File "/root/Veil/Veil-Evasion//modules/payloads/native/backdoor_factory.py", line 14, in <module>
    from tools.backdoor import pebin
  File "/root/Veil/Veil-Evasion/tools/backdoor/pebin.py", line 42, in <module>
    import pefile
ImportError: No module named pefile

By doing reinstalling or updating:

==========================================================================
 Veil-Evasion Setup Script | [Updated]: 09.09.2014
==========================================================================
 [Web]: https://www.veil-framework.com | [Twitter]: @VeilFramework
==========================================================================

 [WARNING]: Setup No Longer Requires Constant Root Privileges.
            Continuing Will Install Veil Only For The Root User.

 Continue With Installation? (y/n): y

 Kali linux detected...

 [*] Capstone Already Installed... Skipping.
 [*] Wine Python Already Installed... Skipping.
 [*] Initializing Apt Package Installation
 [*] Installing Microsoft Fonts
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package ttf-mscorefonts-installer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ttf-mscorefonts-installer' has no installation candidate
 [*] Installing Apt Dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mingw-w64
E: Unable to locate package monodoc-browser
E: Unable to locate package monodevelop
E: Unable to locate package mono-mcs
E: Unable to locate package python-pefile
 [*] Wine Ruby Already Installed... Skipping.
 [*] Updating Veil-Framework Configuration

 Veil-Framework configuration:

 [*] OPERATING_SYSTEM = Kali
 [*] TERMINAL_CLEAR = clear
 [*] TEMP_DIR = /tmp/
 [*] MSFVENOM_OPTIONS = 
 [*] METASPLOIT_PATH = /usr/share/metasploit-framework/
 [*] PYINSTALLER_PATH = /opt/pyinstaller-2.0/

 [*] VEIL_EVASION_PATH = /root/Veil/Veil-Evasion/
 [*] PAYLOAD_SOURCE_PATH = /usr/share/veil-output/source/
 [*] PAYLOAD_COMPILED_PATH = /usr/share/veil-output/compiled/
 [*] GENERATE_HANDLER_SCRIPT = True
 [*] HANDLER_PATH = /usr/share/veil-output/handlers/
 [*] HASH_LIST = /usr/share/veil-output/hashes.txt

 [*] VEIL_CATAPULT_PATH = /root/Veil/Veil-Catapult/
 [*] CATAPULT_RESOURCE_PATH = /usr/share/veil-output/catapult/

 Configuration File Written To '/etc/veil/settings.py'

 [*] Ensuring this account owns veil output directory...

Thank you for your help and for your time.

**Comment by secretsquirrel** [comment]
https://www.google.com/search?safe=off&site=&source=hp&ei=kzsPVc67EMjHsQSpkIGoCQ&q=import+pefile+ImportError%3A+No+module+named+pefile&oq=import+pefile+ImportError%3A+No+module+named+pefile&gs_l=mobile-gws-hp.3...6583.6583.0.7551.2.2.0.1.1.0.397.631.2-1j1.2.0.msedr...0...1c.2.62.mobile-gws-hp..1.1.40.3.aFHvZLCNbj8


On Mar 22, 2015, at 5:29 PM, lgcambero <notifications@github.com> wrote:

import pefile
ImportError: No module named pefile

**Comment by lgcambero** [comment]
You seem to come up here without going through the search engine, I expose this error since previously had not happened to me, and do not help antics, shows seriousness.

**Comment by secretsquirrel** [comment]
Sure. Here's your answer: http://bit.ly/1xcndTr


On Mar 22, 2015, at 6:14 PM, lgcambero <notifications@github.com> wrote:

You seem to come up here without going through the search engine, I expose
this error since previously had not happened to me, and do not help antics,
shows seriousness.

—
Reply to this email directly or view it on GitHub
<https://github.com/Veil-Framework/Veil-Evasion/issues/119#issuecomment-84714796>
.
