### ISSUE TITLE
Backdoor Factory Payloads within Veil

### ISSUE THREAD

**Issue by salmankhalil** [Veil-Framework/Veil-Evasion#122]
Hello guys 

sorry if it's stupid questions is it possible need to use Veil Backdoor Factory Payloads in PDF file ?

**Comment by secretsquirrel** [comment]
It is.


On Mar 30, 2015, at 10:07 AM, salmankhalil <notifications@github.com> wrote:

Hello guys

sorry if it's stupid questions is it possible need to use Veil Backdoor
Factory Payloads in PDF file ?

—
Reply to this email directly or view it on GitHub
<https://github.com/Veil-Framework/Veil-Evasion/issues/122>.
