### ISSUE TITLE
Hello Veil Pywin32-218 issue

### ISSUE THREAD

**Issue by joeblack6** [Veil-Framework/Veil-Evasion#123]
I'm trying to install Veil on Kali 64bit.But it gives an error related Pywin32-218.How can we fix this error?32bit installation certain solution?I updated Kali the last version.I redownloaded git repo.Still same.Wine 1.4.1 platform 32 bit

**Comment by ChrisTruncer** [comment]
Did you run the setup?

Pastebin the output of everything so we can look at it.

**Comment by ChrisTruncer** [comment]
Bueller?

**Comment by joeblack6** [comment]
I'll paste the pastebin here after reran.

**Comment by joeblack6** [comment]
pastebin.com/6xvV887B

**Comment by joeblack6** [comment]
pastebin.com/768f3JBM

**Comment by ChrisTruncer** [comment]
Hi, sorry, but I can't really tell what's going on with that.  Did you run the setup script?

**Comment by joeblack6** [comment]
yes i ran setup.sh and while installation goes well win32 python wine setup programs caused errors

**Comment by ChrisTruncer** [comment]
Can you still generate a payload?  Does it work?

**Comment by joeblack6** [comment]
No it didn't work i'm not generating payload without python installer
packages.It generates null payload...Nothing works for me.

2015-04-06 17:17 GMT+03:00 ChrisTruncer <notifications@github.com>:

**Comment by ChrisTruncer** [comment]
Can you paste in your output from running the setup script?

**Comment by ChrisTruncer** [comment]
Pastebin*

**Comment by joeblack6** [comment]
It didn't give a different error it gave only errors while installing
python windows executables.

2015-04-07 15:03 GMT+03:00 ChrisTruncer <notifications@github.com>:

**Comment by ChrisTruncer** [comment]
Sorry, but if I can't see the error, or reproduce it, there isn't a whole lot I can do

**Comment by joeblack6** [comment]
Here is the log:

I'm trying to generate payload but no file exist in the compiled folder

http://pastebin.com/07FjXjKH

2015-04-08 14:52 GMT+03:00 ChrisTruncer <notifications@github.com>:

**Comment by agentc4** [comment]
I too am having the same issue. I reinstalled Veil couple times, and everytime I do, I get a pop-up installation of Python, Pywin32 and PyCrpyto, and the last 2 fail. Before installing it twice, I was having an issue generating any executables in the output folder.

Here is my pastebin link for the output:

http://pastebin.com/KaEb2B3Q

**Comment by agentc4** [comment]
does it matter if I install it by doing "apt-get install veil"

or is it much better grabbing the git link and pasting that into the terminal and doing it that way

**Comment by ChrisTruncer** [comment]
If you installed by doing apt-get install Veil, you might have messed up the install process. We ALWAYS tell people to clone from github and install that way.

**Comment by ChrisTruncer** [comment]
Also, I did test the install on a clean Kali x64 install and everything seems working. A specific payload fail for you?

**Comment by agentc4** [comment]
ah, ok, i had a feeling you were going to say that about grabbing it from here and not apt. This was done on an existing kali install that i've been using for a while. Any good way to completely remove veil along with pywin and pycrypto so I can do a fresh install from git? 

as far as the payload, anything python related wouldnt generate an exe file, guesing because the pywin and pycrypto fails to install.

**Comment by agentc4** [comment]
This is what I keep getting 

![image](https://cloud.githubusercontent.com/assets/11905107/7106065/330fc9b0-e103-11e4-929f-7a4c2cd1baa1.png)

**Comment by joeblack6** [comment]
Yes ruby generators are working well on 64bit.But python generators are not
working.

2015-04-12 18:01 GMT+03:00 agentc4 <notifications@github.com>:

**Comment by ChrisTruncer** [comment]
Agentc4 - besides uninstalling from apt and then trying to install by cloning from github, I'm not sure of your best bet besides starting with a new image.

Joeblack6 - I just installed on a clean Kali x64 image from github and my Python payloads are working. Can you try on a clean install for testing purposes?

**Comment by joeblack6** [comment]
Ok I'll reinstall Kali today and inform you.

2015-04-12 22:47 GMT+03:00 ChrisTruncer <notifications@github.com>:

**Comment by funk49** [comment]
I'm encountering the same issue during the process of the pywin32 installation and this is happening on a brand new, clean version of Kali64 running setup from git, not apt-get. I've tried both builds 218 and 219. Any ideas on why this is happening?

**Comment by ChrisTruncer** [comment]
Have you tried using the one's that we download from our setup script, and manually installing that?

**Comment by funk49** [comment]
I downloaded both from SourceForge and they appear to be the same place that the setup script pulls from. FYI, this is the 2nd system that this has happened to me on.  I was trying to get it working today with a Kali 1.09 build and the same thing happened at the same exact place. Thanks in advance for the help!

Here's where I got 218 from:

http://sourceforge.net/projects/pywin32/files/pywin32/Build%20218/pywin32-218.win32-py2.7.exe/download

**Comment by ChrisTruncer** [comment]
Please use the setup script to install our dependencies as they are what we've tested and ensure work for installs.

**Comment by funk49** [comment]
Just to clarify, the initial installation of pywin32 using the setup script failed for me. That's why I went out and tried to pull it down and install it manually.

**Comment by ChrisTruncer** [comment]
Can you give us any output to show it?  I'm able to run the install here on a x64 Kali VM and it installs for me.  Unfortunately, I'm just having a hard time re-creating it.

**Comment by funk49** [comment]
Here's a dump of the Seg Fault:

http://pastebin.com/hdc1twAX

**Comment by ChrisTruncer** [comment]
OK,

Yeah, I definitely see it happening there to you.  I’m sorry, I can’t seem to get that issue happening on their system I have here in front of my to test on.

-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer

On June 16, 2015 at 8:35:04 PM, funk49 (notifications@github.com) wrote:

Here's a dump of the Seg Fault:

http://pastebin.com/hdc1twAX

**Comment by funk49** [comment]
Here's the seg fault from the setup-downloaded Pywin32 exe:

http://pastebin.com/gVG2ePZ5

**Comment by ChrisTruncer** [comment]
Honestly, we just install nearly everything via apt, so the current version in Kali's apt repos work with the install process.  I can't really speak to why you're running into that error.  Will it work on a x86 system?

**Comment by funk49** [comment]
Let me spin up an 32-bit version of Kali and see if I have any better results.  I'll keep you posted.

**Comment by funk49** [comment]
Just an update, I reran the install (using the latest git branch) with the latest 32-bit version of Kali, no apt-get update and it worked fine out of the box (with the exception of module pefile not found, which I fixed). Thanks a bunch for your help and for the product!

**Comment by ChrisTruncer** [comment]
Great, glad to hear it.

**Comment by agentc4** [comment]
so does this mean that apt-get update breaks things for veil even though it's downloaded from here?

**Comment by ChrisTruncer** [comment]
No, we use apt because it works
