### ISSUE TITLE
  File "./Veil-Evasion.py", line 283, in <module>

### ISSUE THREAD

**Issue by ext1** [Veil-Framework/Veil-Evasion#124]
[Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

Traceback (most recent call last):
  File "./Veil-Evasion.py", line 283, in <module>
    controller = controller.Controller(oneRun=False)
  File "/usr/share/veil-evasion/modules/common/controller.py", line 129, in __init__
    self.LoadPayloads()
  File "/usr/share/veil-evasion/modules/common/controller.py", line 141, in LoadPayloads
    d = dict( (path[path.find("payloads")+9:-3], imp.load_source( "/".join(path.split("/")[3:])[:-3],path )  ) for path in glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" * x,'[!_]*.py')) )
  File "/usr/share/veil-evasion/modules/common/controller.py", line 141, in <genexpr>
    d = dict( (path[path.find("payloads")+9:-3], imp.load_source( "/".join(path.split("/")[3:])[:-3],path )  ) for path in glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" * x,'[!_]*.py')) )
  File "/usr/share/veil-evasion//modules/payloads/native/backdoor_factory.py", line 14, in <module>
    from tools.backdoor import pebin
  File "/usr/share/veil-evasion/tools/backdoor/pebin.py", line 37, in <module>
    from intel.intelCore import intelCore
  File "/usr/share/veil-evasion/tools/backdoor/intel/intelCore.py", line 32, in <module>
    from capstone import *
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 310, in <module>
    _setup_prototype(_cs, "cs_regs_access", ctypes.c_int, ctypes.c_size_t, ctypes.POINTER(_cs_insn), ctypes.POINTER(ctypes.c_uint16*64), ctypes.POINTER(ctypes.c_uint8), ctypes.POINTER(ctypes.c_uint16*64), ctypes.POINTER(ctypes.c_uint8))
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 292, in _setup_prototype
    getattr(lib, fname).restype = restype
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libcapstone.so.3: undefined symbol: cs_regs_access

**Comment by ext1** [comment]
run ./setup.sh  and then have problems, how can i fix this? Kali Linux x64

**Comment by ext1** [comment]
and at the end :

ore  
  inflating: /root/.wine/drive_c/Ruby187/lib/ruby/gems/1.8/specifications/fast-aes-0.1.1.gemspec  
 [*] Cleaning Up Ruby Setup Files
 [*] Updating Veil-Framework Configuration
/usr/share/veil-evasion/setup/setup.sh: line 264: cd: ../config: Нет такого файла или каталога
python: can't open file 'update.py': [Errno 2] No such file or directory

**Comment by ext1** [comment]
O I'm fix this, 
git clone https://github.com/Veil-Framework/Veil-Evasion.git
cp /root/Veil-Evasion/setup/setup.sh  /usr/share/veil-evasion/setup/
cp /usr/share/veil-evasion/setup/
./setup.sh

all works Thanks!

**Comment by NetworkLlama** [comment]
I ran into this, and it looks like a collision with an older version of libcapstone.so (the mentioned libcapstone.so.3).  Despite compiling libcapstone into .so.4, .so.3 is called.  By moving .so.3 elsewhere and setting up a symlink to .so.4 (ln -s /usr/lib/libcapstone.so.4 /usr/lib/libcapstone.so.3), it allows veil-evasion to run.

I have not determined yet if this affects anything else in Kali.

**Comment by ChrisTruncer** [comment]
Ext 1 looks like your setup failed?

**Comment by ext1** [comment]
yes.. When you run ./setup.sh

**Comment by ext1** [comment]
if i get setup.sh from Kali linux = failed
if i git setup.sh from git = allright

**Comment by ChrisTruncer** [comment]
That's why we say only install from github. I'm not certain if you installed from apt besides uninstalling it and then trying from github.

**Comment by aquynh** [comment]
you should have both Capstone core + Python binding from the same version to avoid any potential issues.

a good way to guarantee this is to install from PyPi like below - which automatically compile & install everything (core + Python binding) for you:

    $ sudo pip install capstone

**Comment by ChrisTruncer** [comment]
Thanks for the info @aquynh .  We'll take a look at it, although the only issue is we're using the python installed from apt vs. pip (due to the primary platform we are developing for).  I'll be interested if we do encounter a conflict in the future, and if so we may have to look into changing it then.

**Comment by aquynh** [comment]
do you mean you install Capstone from Ubuntu/Debian packages in their official distro repo? if so, please do not do that, as they only carry 2.2 version, which is very buggy.

thanks.

**Comment by ChrisTruncer** [comment]
Ah, sorry.  I meant we install python from apt.  Capstone we install a specific version that's known good for working with Backdoor Factory.  We're cloning Capstone from your github, and then using commit b53a59af53ffbd5dbe8dbcefba41a00cf4fc7469.

**Comment by aquynh** [comment]
i think that commit is after 3.0, and a lot of issues have been fixed since then. therefore, i would recommend to always use the latest stable release (which is 3.0.2 at the moment, and 3.0.3 will be out next week).

thanks.
