### ISSUE TITLE
payload error

### ISSUE THREAD

**Issue by g33xter** [Veil-Framework/Veil-Evasion#131]
Setup:
OS Kali Linux 
Msf dev (pulled from git)

![screenshot from 2015-04-21 01 39 48](https://cloud.githubusercontent.com/assets/8503135/7248417/5d2c199a-e7c7-11e4-8cbc-8acb89259fcd.png)

**Comment by ChrisTruncer** [comment]
You might not have the MSF path set correctly in your settings file.  Can you check that?

**Comment by g33xter** [comment]
Solved, thanks!!
