### ISSUE TITLE
KeyError: 'MSFVENOM_PATH'

### ISSUE THREAD

**Issue by funcoding** [Veil-Framework/Veil-Evasion#132]
I am trying to install in BackBox. The following is the output when I run ./setup.sh
<pre>
[>] Please enter the path of your metasploit installation: /usr/local/share/metasploit-framework

 Veil-Framework configuration:
 [*] OPERATING_SYSTEM = Linux
 [*] TERMINAL_CLEAR = clear
 [*] TEMP_DIR = /tmp/
 [*] MSFVENOM_OPTIONS = 
 [*] METASPLOIT_PATH = /usr/local/share/metasploit-framework
Traceback (most recent call last):
  File "./config/update.py", line 210, in <module>
    generateConfig(options)
  File "./config/update.py", line 54, in generateConfig
    config += 'MSFVENOM_PATH="' + options["MSFVENOM_PATH"] + '"\n\n'
KeyError: 'MSFVENOM_PATH'
</pre>
I checked the path of <b>msfvenom</b>
<pre>msfvenom: /usr/bin/msfvenom /usr/bin/X11/msfvenom</pre>

**Comment by ChrisTruncer** [comment]
yup, good catch.  I see where that issue is.  I'll push a patch shortly.

Thanks for reporting this.

**Comment by ChrisTruncer** [comment]
This should be done now.  Thanks for reporting it!

**Comment by funcoding** [comment]
Solved. Thanks!
