### ISSUE TITLE
Contained Payloads

### ISSUE THREAD

**Issue by suissext** [Veil-Framework/Veil-Evasion#136]
metasploit-framework updated to meterpreter bins 0.0.22 and the compiled dll's are different it can't find METERPRETER_UA

**Comment by ChrisTruncer** [comment]
OK, I'll get looking into this.  Thanks

**Comment by suissext** [comment]
It seems that the ruby payloads are fixed, but the python are not.

**Comment by ChrisTruncer** [comment]
I'm going to track this issue in Issue #147.  Please follow this there.
