### ISSUE TITLE
WARNING: not all required options filled

### ISSUE THREAD

**Issue by smilingassassin** [Veil-Framework/Veil-Evasion#137]
after install all of them and run it choose list and get the payload when i choose generate he tell me 
WARNING: not all required options filled

**Comment by ChrisTruncer** [comment]
Hi, this doesn't give enough information, but it just sounds like you didn't fill out all the required information.  Please do that, or provide a pastebin of what you did so I can review it.

**Comment by smilingassassin** [comment]
http://prntscr.com/6xtksw

**Comment by ChrisTruncer** [comment]
That's because you didn't set the required variables.  You need to set them or you get that error.

**Comment by smilingassassin** [comment]
how
