### ISSUE TITLE
win64 not found 

### ISSUE THREAD

**Issue by ayhaga** [Veil-Framework/Veil-Evasion#144]
kali x64 1.0.1
it had many problems on first setup i ran setup again and the only problem that wasn't resolved was couldn't find win64 but everything is still intact and functioning properly but the https payload ,either ruby or python just tries connection once not as it used to do as trying to reconnect for about 3 minutes after execution so is there a solution....thank you very much

**Comment by byt3bl33d3r** [comment]
@ayhaga Can you please paste the errors that you encountered while running the setup script? 
Thanks

**Comment by ayhaga** [comment]
@byt3bl33d3r can`t find the setup.log file unfortunately
