### ISSUE TITLE
metasploit path not accepted 

### ISSUE THREAD

**Issue by ayhaga** [Veil-Framework/Veil-Evasion#145]
[*] Error: You either do not have the latest version of Metasploit or
[*] Error: do not have your METASPLOIT_PATH set correctly in your settings file.
[*] Error: Please fix either issue then select this payload again!

that happens when i try meterpreter/reverse_https_contained only

and the reverse_https connection timeout used to be like 3 min now its just a second is there a way to get that back ...
thanks.

**Comment by jack81** [comment]
Hi,
I have same problem.
What happens when i try meterpreter/reverse_https_contained only (I think for wrong path dll meterpreter), it's ok for other payloads.
Now I'm using Metasploit (Express, Framework Version: 4.11.1-2015042001) last version + Ubuntu and last version Veil. 
 THanks


Thanks

**Comment by ChrisTruncer** [comment]
Is this for the contained payloads that we have (I assume so).  As of now, we are working on updating the framework to accept the recent changes to the meterpreter dll, so this is a known issue and something we are working on to fix.

**Comment by ayhaga** [comment]
ok then thank you and what about the connection time for the reverse_https meterpreter as it used to be much longer and this was why i used it in the first place

**Comment by ChrisTruncer** [comment]
We have nothing to do with how often that connects back
