### ISSUE TITLE
Veil payload gets caught by antivirus

### ISSUE THREAD

**Issue by Digita-Nightmare** [Veil-Framework/Veil-Evasion#149]
ok guys i know the soul purpose of veil is to evade av detection and ive tried just about all of the reverse_tcp payloads from veils list so far ruby has been the best but the all have been picked up
by avira , avast and a few others i think norton as well is there any tricks that i can do to really bypass
the antivirus oh and i guess i should mention im testing this in virtualbox " windows 8.1 and windows 7"
ive tried msfvenom with the shikata_ga_nai encoder as well  im out of options or im doing something wrong  i hope someone can help me i get red flaged by every payload and everything that i try 
im open for suggestions  thanx in advance :)

**Comment by ChrisTruncer** [comment]
They still bypass AV for us. If it doesn't for you, try making a small modification to a module, or try powershell.

**Comment by odd-meta** [comment]
Often times I've run into AV tagging and flagging network traffic on the host side, especially when the meterpreter dll is coming down without any encoding. Have you had the same issues with the reverse_https payloads?
