### ISSUE TITLE
Veil-Evasion.py setup.sh completes with error

### ISSUE THREAD

**Issue by NerishiQaMaster** [Veil-Framework/Veil-Evasion#156]
Hi,

One of several recent issues with the otherwise amazing framework.
Issues first experienced following "metasploit-framework" update on Friday 29/05/2015.
Have also run an "apt-get dist-upgrade" today 01/06/2015.

OS is Kali Linux on i686
Veil-Evasion shows as 2.20.3.
./setup/setup.sh shows as "[Updated] 04/16/2015" (but must be latest version)
**Please advise on any relevant contextual info that is missing, I'll be happy to provide**

The error received is one that seems to appear in many other closed Issues:

"./setup/setup.sh: line 289: cd: ../config: No such file or directory
python: can't open file 'update.py' [Errno 2] No such file or directory"

When trying to run with this config I can't generate the payload I need.
Separate issue raised for that, but since at face value setup.sh should be running correctly regardless, this seemed worth raising.

Actions I've taken:
Reviewd Issues for common strands: nothing 100% identical, the issues which mention problems finding the config dir appear to have different root causes.
Removing & reinstalling veril-evasion using apt: got the same error at a different line number in the setup.sh script - assume different version from current git master?
Removing veil-evasion using apt, then trying to start from scratch by cloning Veil-Framework directly from git: this ended up worse, with no payloads! However with that bit of user error resolved, I'm back to having both this setup.sh error, and the other "generate" error (raised separately) which caused me to look at setup.sh. Net no change.

Please help me out by telling me the error of my ways if necessary, but assume no technical knowledge on my part to aviod having to repeat yourself: I'm an infrastructure pen tester, but never been a developer :)

Thanks,

Nerishi

**Comment by ChrisTruncer** [comment]
I'm going to close this out.

We've stated multiple times, please do not install from apt.  Please clone from github and run it that way.  It ensures you have the latest version and everything you need.

**Comment by NerishiQaMaster** [comment]
Hi Chris,

Thanmks for the quick resposne.
I think you might have failed to read the output above fully, since you've applied the same comment to two tangentially-related, but different, issues.
This in turn might be preventing you from fixing a problem with your project, or getting a message to us users that we're Doing It Wrong.

As stated above, this problem occurs both with a clone of the latest master AND with the APT package. 
Please read the entire submission?
Please also update your README.md, and the Veil-Fraemwork website. Both tell Kali users they have no more to do to setup & use, creatign unecessary support requests for you. I know this advice conflicts with your most current advice to use git, which is why I did it BEFORE submitting an issue.

Regards,

Nerishi

**Comment by ChrisTruncer** [comment]
Hello,

This problem is isolated to your system.  I just tested the setup process out on a clean system without Veil on it, and everything setup perfectly.  I also tested generating a payload, all payloads were listed, and everything worked.

Please watch our setup videos/guides and follow them exactly as we show them.
