### ISSUE TITLE
if DEP POLICY is on the python letter_substitution not work

### ISSUE THREAD

**Issue by coldalfred** [Veil-Framework/Veil-Evasion#162]
https://www.veil-framework.com/dep-pyinstaller/

The module python letter_substitution not work with a DEP Policy i believe before the changes... avlol?

i have the version 2.19.2 and this version work well vs the actual git version

**Comment by ChrisTruncer** [comment]
The change shouldn't have impacted anything.  Can you please pastebin your console to show us everything you did generating the payload?

**Comment by ChrisTruncer** [comment]
I just verified this against a Windows 7 system with the default DEP policy.  I received a callback without any issues, I think this might be something isolated to your system.
