### ISSUE TITLE
Problem with go payloads

### ISSUE THREAD

**Issue by copo1234** [Veil-Framework/Veil-Evasion#194]
Hello im doing a payload with the go/merpreter/rev_https and when im in the listener with the armitage waiting for the reverse and someone run the payload I get and error with a lot of words that dosent tell me anything please someone can help me with this

**Comment by ChrisTruncer** [comment]
Hi there,

I just tested this out on the latest Kali, Veil, and MSF as of me writing this response, and I am able to receive a session without a problem.  Please make sure all software is up to date on your side.

Additionally, for any future github issues, saying that "a lot of words" are displayed doesn't give me any context to which I can begin helping to troubleshoot your issue.  Please in the future make a copy of your console output, paste it in pastebin, and put that link here.
