### ISSUE TITLE
Problem with the go payload

### ISSUE THREAD

**Issue by copo1234** [Veil-Framework/Veil-Evasion#196]
[*] 190.154.164.85:7877 (UUID: 14dbde9f2fff0046/x86=1/windows=1/2015-07-23T15:35:54Z) Staging Native payload ...
[-] Exception handling request: undefined method `stage_payload' for #<#<Class:0x000000033b3af0>:0x00000006ba84d8>
Someone can help me why I get that error

**Comment by ChrisTruncer** [comment]
You didn't provide any information that I can use to help troubleshoot this.  Please let me know which go payload isn't working for you.

Also, I just tested the Go rev_http payload, and that is working for me, with everything up to date.
