### ISSUE TITLE
Picking 'golang' as source package instead of 'golang-go' -- error while installing on KALI V2.0 

### ISSUE THREAD

**Issue by yo0x** [Veil-Framework/Veil-Evasion#201]
Hi guys while trying to install Veil-Evasion on Kali V2 i got this error:

 [*] (Wine) Python Already Installed... Skipping...

 [*] (Wine) Ruby Already Installed... Skipping...

 [*] Initializing Go Dependencies Installation...
 [*] Installing Go (v13 via Repos)
Reading package lists... Done
Building dependency tree
Reading state information... Done
Picking 'golang' as source package instead of 'golang-go'
E: Unable to find a source package for golang
 [ERROR] Failed To Download Go... Exit Code: 100.

any ideas why it is unable to install Go..???

**Comment by ChrisTruncer** [comment]
This looks to be odd with something on your local system, or the mirror you are using.  When checking the repo right now with apt-cache search golang-go, I can see the package available for install.

**Comment by Margae** [comment]
Nothing odd with your system! Kali 2.0 is pretty fresh and you need to add source repos of sana:

deb-src http://http.kali.org/kali sana main non-free contrib
deb-src http://security.kali.org/kali-security sana/updates main contrib non-free

That's it ;-)  Hope this alos helps others who experience this error message.
