### ISSUE TITLE
issue with installing veil-evasion on kali v 2

### ISSUE THREAD

**Issue by mahmoodkia** [Veil-Framework/Veil-Evasion#202]
hey tnx for time
so first i did install with apt-get :/ and it ran perfectly without any problem for me but after close it up and went to configue file but next time i ran it it was without any payload like this:
Main Menu

	0 payloads loaded

so i decided get github versione! idid got it but when i want to run setup it give me this error :/
 [ERROR] Internal Issue. Couldn't Detect OS Information...
any help would be awesome & tnx for programm <3

**Comment by ChrisTruncer** [comment]
Please run the update.py file.  If you've installed this multiple times, there is potentially an issue now with your install.  Might need to start clean if update.py doesn't fix it.

**Comment by mahmoodkia** [comment]
hi tnx for your fast answer sir<3 what i done was
apt-get autoremove veil-evasion
then i went to setup.sh and edited where there is if didnt req os print  [ERROR] Internal Issue. Couldn't Detect OS Information... and made elif kali to if
setup runed :+1: ! so it runed and installed it
now it gave me this error while i run this programm ImportError: ERROR: fail to load the dynamic library.
then i raned update.py
[*] OPERATING_SYSTEM = Kali
 [*] TERMINAL_CLEAR = clear
 [*] TEMP_DIR = /tmp/
 [*] MSFVENOM_OPTIONS = 
 [*] METASPLOIT_PATH = /usr/share/metasploit-framework/
 [*] MSFVENOM_PATH = /usr/bin/
 [*] PYINSTALLER_PATH = /usr/share/pyinstaller/

 [*] VEIL_EVASION_PATH = /
 [*] PAYLOAD_SOURCE_PATH = /usr/share/veil-output/source/
 [*] PAYLOAD_COMPILED_PATH = /usr/share/veil-output/compiled/
 [*] GENERATE_HANDLER_SCRIPT = True
 [*] HANDLER_PATH = /usr/share/veil-output/handlers/
 [*] HASH_LIST = /usr/share/veil-output/hashes.txt

 [*] VEIL_CATAPULT_PATH = /Veil-Catapult/
 [*] CATAPULT_RESOURCE_PATH = /usr/share/veil-output/catapult/

 Configuration File Written To '/etc/veil/settings.py
now it load 0 payloads loaded!!

any fix? how to start clean?

**Comment by ChrisTruncer** [comment]
Hi, I really don't know to be honest.  Best way to start clean will probably be to try a new clean VM.  I can't really speak to how to fix any/all of the changes you made to your system.

**Comment by mahmoodkia** [comment]
hi tnx for advise ! i did remove my os and reinstall kali again!
did work like charm also fixed my sound issue and vpn issues xD i quess  first packeges were bit buggy
