### ISSUE TITLE
Error in setup.sh on ubuntu 14.04

### ISSUE THREAD

**Issue by sec0ps** [Veil-Framework/Veil-Evasion#204]
Installing on Ubuntu 14.04 LTS the following error appears:

/setup.sh: line 352: [[: "14.04": syntax error: operand expected (error token is ""14.04"")

--- from setup.sh, error is in the if statement ---
  echo " [i] Ubuntu ${version} $(uname -m) Detected..."
  if [[ "${version}" -lt "14" ]]; then
    echo -e " [ERROR]: Veil-Evasion Only Supported On Ubuntu 14+.\n"
    exit 1
  fi

**Comment by ChrisTruncer** [comment]
I just pushed a fix, so I think this should be good now.  Thanks for reporting this!
