### ISSUE TITLE
Veil-Evasion did work for mac 10.9 and setup is now not working

### ISSUE THREAD

**Issue by metasecdev** [Veil-Framework/Veil-Evasion#207]
I would like to request that it would work again.
$ sudo ./setup.sh 
==========================================================================
 Veil-Evasion Setup Script | [Updated]: 2015-07-06
==========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
==========================================================================

 [ERROR] Internal Issue. Couldn't Detect OS Information...

$

**Comment by ChrisTruncer** [comment]
Hi, this shouldn't have worked on Mac.  It requires apt for a package manager.  We're also not looking for Mac to be a supported OS.  If you would like to send us a pull request making it supported, I'll be happy to review it.  However, at this time, this isn't on the roadmap to work on this.

Thanks!
