### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by AnorexicSeal** [Veil-Framework/Veil-Evasion#210]
Hello, I tried installing veil-evasion through apt-get and manually, but unfortunately I keep getting the same error when I run veil-evasion.

Traceback (most recent call last):
  File "./Veil-Evasion.py", line 287, in <module>
    controller = controller.Controller(oneRun=False)
  File "/root/Veil-Evasion/modules/common/controller.py", line 107, in __init__
    self.LoadPayloads()
  File "/root/Veil-Evasion/modules/common/controller.py", line 119, in LoadPayloads
    d = dict( (path[path.find("payloads")+9:-3], imp.load_source( "/".join(path.split("/")[3:])[:-3],path )  ) for path in glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" * x,'[!_]*.py')) )
  File "/root/Veil-Evasion/modules/common/controller.py", line 119, in <genexpr>
    d = dict( (path[path.find("payloads")+9:-3], imp.load_source( "/".join(path.split("/")[3:])[:-3],path )  ) for path in glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" * x,'[!_]*.py')) )
  File "/root/Veil-Evasion//modules/payloads/native/backdoor_factory.py", line 14, in <module>
    from tools.backdoor import pebin
  File "/root/Veil-Evasion/tools/backdoor/pebin.py", line 45, in <module>
    from intel.intelCore import intelCore
  File "/root/Veil-Evasion/tools/backdoor/intel/intelCore.py", line 38, in <module>
    from capstone import *
ImportError: No module named capstone

I am running Kali Linux
Am I missing something, or perhaps should I reinstall kali?

**Comment by ChrisTruncer** [comment]
Are you on Kali 2?  It looks like everything should be installed, including capstone:

apt-cache show veil-evasion
Package: veil-evasion
Version: 2.21.1.1-0kali1
Architecture: amd64
Maintainer: Devon Kearns <dookie@kali.org>
Installed-Size: 68089
Depends: python:any (>= 2.7.5-5~), mingw-w64, monodoc-browser, monodevelop, mono-mcs, wine, python-crypto, python-pefile, python-pip, unzip, ruby, pyinstaller, ttf-mscorefonts-installer, python-symmetric-jsonrpc, python-capstone (>= 3.0), metasploit-framework, sudo
Replaces: veil
Homepage: https://github.com/Veil-Framework/Veil-Evasion
Priority: extra
Section: utils
Filename: pool/main/v/veil-evasion/veil-evasion_2.21.1.1-0kali1_amd64.deb
Size: 55498168
SHA256: 4f022af5da4e217d2677687cf24f3fae270541c6aecfd4a87c4b2306403cb69c
SHA1: 717b35944284e56512174f151e90d268a5ba7103
MD5sum: 8e53d7ad73b716abfc48245ed71c3853
Description: Generate payloads that bypass antivirus solutions
 Veil-Evasion is a tool to generate payload executables that bypass common
 antivirus solutions. Veil-Evasion’s code is located at
 https://www.github.com/Veil-Framework/Veil-Evasion/ and it’s a part of the Veil
 super project at https://github.com/Veil-Framework/Veil
Description-md5: f96401df4cc5b8f9cf4d5284c3ff85fb

**Comment by AnorexicSeal** [comment]
That is correct,

apt-cache show veil-evasion
Package: veil-evasion
Version: 2.20-0kali1
Architecture: amd64
Maintainer: Devon Kearns <dookie@kali.org>
Installed-Size: 16074
Depends: mingw-w64, monodoc-browser, monodevelop, mono-mcs, wine, python, python-crypto, python-pefile, python-pip, unzip, ruby, python-support, pyinstaller, ttf-mscorefonts-installer
Replaces: veil
Homepage: https://github.com/Veil-Framework/Veil-Evasion
Priority: extra
Section: utils
Filename: pool/main/v/veil-evasion/veil-evasion_2.20-0kali1_amd64.deb
Size: 5360280
SHA256: be1f79dc849075d061d2e9514f3f51c673f7241b9287b18c875b60acedb8346d
SHA1: bbca54f3a4bc8fd69338a645d9522984b4ba8697
MD5sum: f90b5d95b326cec8233f128896ec5d81
Description: Generate payloads that bypass antivirus solutions
 Veil-Evasion is a tool to generate payload executables that bypass common
 antivirus solutions. Veil-Evasion’s code is located at
 https://www.github.com/Veil-Framework/Veil-Evasion/ and it’s a part of the Veil
 super project at https://github.com/Veil-Framework/Veil

I think the only difference is the installed size.

**Comment by ChrisTruncer** [comment]
That is the old version, try doing an apt-get update then installing.

And let me know if it works

**Comment by necrose99** [comment]
One I get moved, I'll see if I can build from src's , then cobble an
ebuild/s together, one I get time.
Ebuild, repo overlay Gentoo/Pentoo/Funtoo/Sabayon Linux
Should be able to then build veil packages from src's, @ version x? (Stable
release #s) and 9999 (wildcard for latest git-src/test)
Then if the packages work I'm sure upstream maintainers will be quite happy
to take them.

Good list of depends  I can use always.
To make an attempt to package veil for Gentoo family of Linux
distributions.

**Comment by AnorexicSeal** [comment]
Hello Chris, Sorry for the late response I did try the update, but regrettably it did not work.

Although I reinstalled Kali, with a new Image, and it finally worked! I thought it was weird that I stopped working to be honest.

**Comment by ChrisTruncer** [comment]
OK, glad to hear it's working
