### ISSUE TITLE
solving problem of payload showing

### ISSUE THREAD

**Issue by mahmoodkia** [Veil-Framework/Veil-Evasion#212]
so as you might know i had this issue which might be many of us issue aswell 
so i had to clear install my kali for couple of times and each time i had to install veil-evasion again but after one day or some houre it just show me  0 payload and there was no soultion for it
till in one of my installs i didnt add any thing to my source list and installed veil-evasion
it did work and didnt show me 0 payload again 
hope this work for some of you guyz
have fun.

**Comment by ChrisTruncer** [comment]
Please read the other issues which show the answer to this - simply run update.py

**Comment by mahmoodkia** [comment]
this wont fix it mate ;) i have had this problem
