### ISSUE TITLE
Installation of Veil-Evasion on Kali 2.0 fails

### ISSUE THREAD

**Issue by sud0nick** [Veil-Framework/Veil-Evasion#221]
I'm trying to install Veil-Evasion on Kali 2.0.  I've cloned the github repo and tried installing it on both 32-bit and 64-bit Kali 2 to no avail.  I realize this may end up being an issue with Kali rather than Veil but I must begin ruling things out somewhere.

The following error is what I receive when trying to install on 32-bit:
>[*] Installing Dependencies
>Reading package lists... Done
>Building dependency tree
>Reading state information... Done
>Package ttf-mscore-installer is not available, but is referred to by another package.
>This may mean that the package is missing, has been obsoleted, or
>is only available from another source
>
>E: Unable to locate package mingw-w64
>E: Unable to locate package monodoc-browser
>E: Unable to locate package monodevelop
>E: Unable to locate package mono-mcs
>E: Unable to locate package golang
>E: Package 'ttf-mscorefonts-installer' has no installation candidate
> [ERROR] Failed To Install Dependencies... Exit Code: 100.

And this error is what I receive when trying to install on 64-bit:
> [*] Installing (Wine) i386 Binaries
>Reading package lists... Done
>Building dependency tree
>Reading state information... Done
>Package wine32 is not available, but is referred to by another package.
>This may mean that the package is missing, has been obsoleted, or
>is only available from another source
>However the following packages replace it:
>  wine
>
>E: Package 'wine32' has no installation candidate
>Reading package lists... Done
>Building dependency tree
>Reading state information... Done
>Package win-bin:i386 is not available, but is referred to by another package.
>This may mean that the package is missing, has been obsoleted, or
>is only available from another source
>However the following packages replace it:
>  libwine wine
>
>E: Package 'wine-bin:i386' has no installation candidate
> [ERROR] Failed To Install Wine x86_64... Exit Code: 100.

I have tried this on multiple fresh installs both before and after updating all packages on Kali.  I've also tried installing the packages with apt-get and they can't seem to be found.  Any ideas?

**Comment by ChrisTruncer** [comment]
Hi there,

This is going to be a problem with your repos that you are using.  Please change the repos you have set because those packages are installed within Kali's repos.

**Comment by sud0nick** [comment]
Which repos should I use?  With the images being fresh should I not have had Kali's repos already?

**Comment by sud0nick** [comment]
Nevermind.  I got it to work by adding an additional repo that I just found online.  For anyone else having this issue your sources.list file in /etc/apt/ should like this:

># Regular repositories
>deb http://http.kali.org/kali sana main non-free contrib
>deb http://security.kali.org/kali-security sana/updates main contrib non-free
># Source repositories
>deb-src http://http.kali.org/kali sana main non-free contrib
>deb-src http://security.kali.org/kali-security sana/updates main contrib non-free

Thanks for the help, Chris.

**Comment by tonymontana111** [comment]
I have installed Kali Linux 2.0 virtual machine VMware Workstation 12  It is updated (apt-get update) upgraded (apt-get upgrade && apt-get dist upgrade) 
Repositories 

# Regular repositories
deb http://http.kali.org/kali sana main non-free contrib
deb http://security.kali.org/kali-security sana/updates main contrib non-free
# Source repositories
deb-src http://http.kali.org/kali sana main non-free contrib
deb-src http://security.kali.org/kali-security sana/updates main contrib non-free
I take a clone Veil-Evasion from GitHub with git clone and I get this error:::


root@kali:~# git clone https://github.com/Veil-Framework/Veil-Evasion.git
Cloning into 'Veil-Evasion'...
remote: Counting objects: 3328, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 3328 (delta 3), reused 0 (delta 0), pack-reused 3308
Receiving objects: 100% (3328/3328), 85.29 MiB | 121.00 KiB/s, done.
Resolving deltas: 100% (1859/1859), done.
Checking connectivity... done.
Checking out files: 100% (304/304), done.
root@kali:~# ls
Desktop    Downloads  Pictures  Templates     Videos
Documents  Music      Public    Veil-Evasion
root@kali:~# cd Veil-Evasion
root@kali:~/Veil-Evasion# ls
CHANGELOG  COPYRIGHT  README.md  testbins  Veil-Evasion.py
config     modules    setup      tools
root@kali:~/Veil-Evasion# cd setup/
root@kali:~/Veil-Evasion/setup# ls
go1.4.2.src.tar.gz            python-tcl.zip
ocra-1.3.0.gem                python-Tools.zip
pycrypto-2.6.win32-py2.7.exe  pywin32-219.win32-py2.7.exe
pyinstaller-2.0.zip           ruby_gems-1.8.zip
python-2.7.5.msi              rubyinstaller-1.8.7-p371.exe
python-distutils.zip          setup.sh
root@kali:~/Veil-Evasion/setup# ./setup.sh
==========================================================================
 Veil-Evasion Setup Script | [Updated]: 2015-07-06
==========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
==========================================================================


 [i] Kali Linux "2.0" x86_64 Detected...

 [?] Are you sure you wish to install Veil-Evasion?

 Continue With Installation? (y/N): y


 [*] Initializing Package Installation
Err http://security.kali.org sana/updates InRelease
  
Err http://security.kali.org sana/updates Release.gpg
  Could not resolve 'security.kali.org'
Err http://http.kali.org sana InRelease
  
Err http://http.kali.org sana Release.gpg
  Could not resolve 'http.kali.org'
Reading package lists...
W: Failed to fetch http://http.kali.org/kali/dists/sana/InRelease  

W: Failed to fetch http://security.kali.org/kali-security/dists/sana/updates/InRelease  

W: Failed to fetch http://security.kali.org/kali-security/dists/sana/updates/Release.gpg  Could not resolve 'security.kali.org'

W: Failed to fetch http://http.kali.org/kali/dists/sana/Release.gpg  Could not resolve 'http.kali.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.


 [*] Adding i386 Architecture To x86_64 System
Err http://http.kali.org sana InRelease
  
Err http://http.kali.org sana Release.gpg
  Could not resolve 'http.kali.org'
Err http://security.kali.org sana/updates InRelease
  
Err http://security.kali.org sana/updates Release.gpg
  Could not resolve 'security.kali.org'
Reading package lists...
W: Failed to fetch http://http.kali.org/kali/dists/sana/InRelease  

W: Failed to fetch http://security.kali.org/kali-security/dists/sana/updates/InRelease  

W: Failed to fetch http://http.kali.org/kali/dists/sana/Release.gpg  Could not resolve 'http.kali.org'

W: Failed to fetch http://security.kali.org/kali-security/dists/sana/updates/Release.gpg  Could not resolve 'security.kali.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.


 [*] Installing (Wine) i386 Binaries
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package wine32 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  wine

E: Package 'wine32' has no installation candidate
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package wine-bin:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  wine libwine

E: Package 'wine-bin:i386' has no installation candidate
 [ERROR] Failed To Install Wine x86_64... Exit Code: 100.

Please help I trying everything but unsuccesful

**Comment by tonymontana111** [comment]
After re-run ./setup.ch I got  this
 [i] Kali Linux "2.0" x86_64 Detected...

 [?] Are you sure you wish to install Veil-Evasion?

 Continue With Installation? (y/N): y


 [*] Initializing Package Installation
Err http://security.kali.org sana/updates InRelease
  
Err http://security.kali.org sana/updates Release.gpg
  Could not resolve 'security.kali.org'
Err http://http.kali.org sana InRelease
  
Err http://http.kali.org sana Release.gpg
  Could not resolve 'http.kali.org'
W: Failed to fetch http://http.kali.org/kali/dists/sana/InRelease  

W: Failed to fetch http://security.kali.org/kali-security/dists/sana/updates/InRelease  

W: Failed to fetch http://security.kali.org/kali-security/dists/sana/updates/Release.gpg  Could not resolve 'security.kali.org'

W: Failed to fetch http://http.kali.org/kali/dists/sana/Release.gpg  Could not resolve 'http.kali.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?


 [*] Adding i386 Architecture To x86_64 System
Err http://http.kali.org sana InRelease
  
Err http://http.kali.org sana Release.gpg
  Could not resolve 'http.kali.org'
Err http://security.kali.org sana/updates InRelease
  
Err http://security.kali.org sana/updates Release.gpg
  Could not resolve 'security.kali.org'
Reading package lists...
W: Failed to fetch http://http.kali.org/kali/dists/sana/InRelease  

W: Failed to fetch http://security.kali.org/kali-security/dists/sana/updates/InRelease  

W: Failed to fetch http://http.kali.org/kali/dists/sana/Release.gpg  Could not resolve 'http.kali.org'

W: Failed to fetch http://security.kali.org/kali-security/dists/sana/updates/Release.gpg  Could not resolve 'security.kali.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.


 [*] Installing (Wine) i386 Binaries
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  gcc-4.9-base:i386 i965-va-driver:i386 libasound2:i386
  libasound2-plugins:i386 libasyncns0:i386 libattr1:i386 libavcodec56:i386
  libavresample2:i386 libavutil54:i386 libbsd0:i386 libc6:i386 libc6-i686:i386
  libcap2:i386 libdb5.3:i386 libdbus-1-3:i386 libdrm-intel1:i386
  libdrm-nouveau2:i386 libdrm-radeon1:i386 libdrm2:i386 libedit2:i386
  libelf1:i386 libexpat1:i386 libffi6:i386 libflac8:i386 libfreetype6:i386
  libgcc1:i386 libgcrypt20:i386 libgl1-mesa-dri:i386 libgl1-mesa-glx:i386
  libglapi-mesa:i386 libglib2.0-0:i386 libglu1-mesa:i386 libgmp10:i386
  libgnutls-deb0-28:i386 libgpg-error0:i386 libgpm2:i386 libgsm1:i386
  libgstreamer-plugins-base0.10-0:i386 libgstreamer0.10-0:i386
  libhogweed2:i386 libice6:i386 libjack-jackd2-0:i386 libjson-c2:i386
  liblcms2-2:i386 libldap-2.4-2:i386 libllvm3.5:i386 liblzma5:i386
  libmp3lame0:i386 libmpg123-0:i386 libncurses5:i386 libnettle4:i386
  libogg0:i386 libopenal1:i386 libopenjpeg5:i386 libopus0:i386
  liborc-0.4-0:i386 libp11-kit0:i386 libpciaccess0:i386 libpcre3:i386
  libpng12-0:i386 libpulse0:i386 libsamplerate0:i386 libsasl2-2:i386
  libsasl2-modules:i386 libsasl2-modules-db:i386 libschroedinger-1.0-0:i386
  libselinux1:i386 libsm6:i386 libsndfile1:i386 libspeex1:i386
  libspeexdsp1:i386 libssl1.0.0:i386 libstdc++6:i386 libsystemd0:i386
  libtasn1-6:i386 libtheora0:i386 libtinfo5:i386 libtxc-dxtn-s2tc0:i386
  libudev1:i386 libuuid1:i386 libva1:i386 libvdpau1:i386 libvorbis0a:i386
  libvorbisenc2:i386 libvpx1:i386 libwine:i386 libwrap0:i386 libx11-6:i386
  libx11-xcb1:i386 libx264-142:i386 libxau6:i386 libxcb-dri2-0:i386
  libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386 libxcb-sync1:i386
  libxcb1:i386 libxcursor1:i386 libxdamage1:i386 libxdmcp6:i386 libxext6:i386
  libxfixes3:i386 libxi6:i386 libxml2:i386 libxrender1:i386 libxshmfence1:i386
  libxtst6:i386 libxvidcore4:i386 libxxf86vm1:i386 va-driver-all:i386
  vdpau-va-driver:i386 zlib1g:i386
Suggested packages:
  glibc-doc:i386 rng-tools:i386 gnutls-bin:i386 gpm:i386
  libvisual-0.4-plugins:i386 gstreamer-codec-install:i386
  gnome-codec-install:i386 gstreamer0.10-tools:i386
  gstreamer0.10-plugins-base:i386 jackd2:i386 liblcms2-utils:i386
  libportaudio2:i386 opus-tools:i386 libsasl2-modules-otp:i386
  libsasl2-modules-ldap:i386 libsasl2-modules-sql:i386
  libsasl2-modules-gssapi-mit:i386 libsasl2-modules-gssapi-heimdal:i386
  speex:i386 nvidia-vdpau-driver:i386 vdpau-driver:i386 xvba-va-driver:i386
Recommended packages:
  xml-core:i386
The following NEW packages will be installed:
  gcc-4.9-base:i386 i965-va-driver:i386 libasound2:i386
  libasound2-plugins:i386 libasyncns0:i386 libattr1:i386 libavcodec56:i386
  libavresample2:i386 libavutil54:i386 libbsd0:i386 libc6:i386 libc6-i686:i386
  libcap2:i386 libdb5.3:i386 libdbus-1-3:i386 libdrm-intel1:i386
  libdrm-nouveau2:i386 libdrm-radeon1:i386 libdrm2:i386 libedit2:i386
  libelf1:i386 libexpat1:i386 libffi6:i386 libflac8:i386 libfreetype6:i386
  libgcc1:i386 libgcrypt20:i386 libgl1-mesa-dri:i386 libgl1-mesa-glx:i386
  libglapi-mesa:i386 libglib2.0-0:i386 libglu1-mesa:i386 libgmp10:i386
  libgnutls-deb0-28:i386 libgpg-error0:i386 libgpm2:i386 libgsm1:i386
  libgstreamer-plugins-base0.10-0:i386 libgstreamer0.10-0:i386
  libhogweed2:i386 libice6:i386 libjack-jackd2-0:i386 libjson-c2:i386
  liblcms2-2:i386 libldap-2.4-2:i386 libllvm3.5:i386 liblzma5:i386
  libmp3lame0:i386 libmpg123-0:i386 libncurses5:i386 libnettle4:i386
  libogg0:i386 libopenal1:i386 libopenjpeg5:i386 libopus0:i386
  liborc-0.4-0:i386 libp11-kit0:i386 libpciaccess0:i386 libpcre3:i386
  libpng12-0:i386 libpulse0:i386 libsamplerate0:i386 libsasl2-2:i386
  libsasl2-modules:i386 libsasl2-modules-db:i386 libschroedinger-1.0-0:i386
  libselinux1:i386 libsm6:i386 libsndfile1:i386 libspeex1:i386
  libspeexdsp1:i386 libssl1.0.0:i386 libstdc++6:i386 libsystemd0:i386
  libtasn1-6:i386 libtheora0:i386 libtinfo5:i386 libtxc-dxtn-s2tc0:i386
  libudev1:i386 libuuid1:i386 libva1:i386 libvdpau1:i386 libvorbis0a:i386
  libvorbisenc2:i386 libvpx1:i386 libwine:i386 libwrap0:i386 libx11-6:i386
  libx11-xcb1:i386 libx264-142:i386 libxau6:i386 libxcb-dri2-0:i386
  libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386 libxcb-sync1:i386
  libxcb1:i386 libxcursor1:i386 libxdamage1:i386 libxdmcp6:i386 libxext6:i386
  libxfixes3:i386 libxi6:i386 libxml2:i386 libxrender1:i386 libxshmfence1:i386
  libxtst6:i386 libxvidcore4:i386 libxxf86vm1:i386 va-driver-all:i386
  vdpau-va-driver:i386 wine32:i386 zlib1g:i386
0 upgraded, 113 newly installed, 0 to remove and 0 not upgraded.
Need to get 61.9 MB of archives.
After this operation, 256 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  gcc-4.9-base:i386 libgcc1:i386 libc6:i386 libssl1.0.0:i386 libstdc++6:i386
  libudev1:i386 libattr1:i386 liblzma5:i386 libtinfo5:i386 libncurses5:i386
  libpcre3:i386 libselinux1:i386 libuuid1:i386 zlib1g:i386 libcap2:i386
  libdb5.3:i386 libbsd0:i386 libedit2:i386 libgpg-error0:i386 libgcrypt20:i386
  libgmp10:i386 libnettle4:i386 libhogweed2:i386 libffi6:i386 libp11-kit0:i386
  libtasn1-6:i386 libgnutls-deb0-28:i386 libgpm2:i386 libsasl2-modules-db:i386
  libsasl2-2:i386 libldap-2.4-2:i386 libwrap0:i386 libxml2:i386 libdrm2:i386
  libpciaccess0:i386 libdrm-intel1:i386 libva1:i386 i965-va-driver:i386
  libasound2:i386 libavutil54:i386 libavresample2:i386 libgsm1:i386
  libmp3lame0:i386 libopenjpeg5:i386 libopus0:i386 liborc-0.4-0:i386
  libschroedinger-1.0-0:i386 libspeex1:i386 libogg0:i386 libtheora0:i386
  libvorbis0a:i386 libvorbisenc2:i386 libvpx1:i386 libx264-142:i386
  libxvidcore4:i386 libavcodec56:i386 libsamplerate0:i386
  libjack-jackd2-0:i386 libasyncns0:i386 libdbus-1-3:i386 libice6:i386
  libjson-c2:i386 libsm6:i386 libflac8:i386 libsndfile1:i386 libsystemd0:i386
  libxau6:i386 libxdmcp6:i386 libxcb1:i386 libx11-6:i386 libx11-xcb1:i386
  libxext6:i386 libxi6:i386 libxtst6:i386 libpulse0:i386 libspeexdsp1:i386
  libasound2-plugins:i386 libdrm-nouveau2:i386 libdrm-radeon1:i386
  libelf1:i386 libexpat1:i386 libpng12-0:i386 libfreetype6:i386
  libllvm3.5:i386 libgl1-mesa-dri:i386 libglapi-mesa:i386 libxcb-dri2-0:i386
  libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386 libxcb-sync1:i386
  libxfixes3:i386 libxdamage1:i386 libxshmfence1:i386 libxxf86vm1:i386
  libgl1-mesa-glx:i386 libglib2.0-0:i386 libglu1-mesa:i386
  libgstreamer0.10-0:i386 libgstreamer-plugins-base0.10-0:i386 liblcms2-2:i386
  libmpg123-0:i386 libopenal1:i386 libvdpau1:i386 libwine:i386
  libxrender1:i386 libxcursor1:i386 vdpau-va-driver:i386 libc6-i686:i386
  libtxc-dxtn-s2tc0:i386 libsasl2-modules:i386 va-driver-all:i386 wine32:i386
E: There are problems and -y was used without --force-yes
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  gcc-4.9-base:i386 i965-va-driver:i386 libasound2:i386
  libasound2-plugins:i386 libasyncns0:i386 libattr1:i386 libavcodec56:i386
  libavresample2:i386 libavutil54:i386 libbsd0:i386 libc6:i386 libc6-i686:i386
  libcap2:i386 libdb5.3:i386 libdbus-1-3:i386 libdrm-intel1:i386
  libdrm-nouveau2:i386 libdrm-radeon1:i386 libdrm2:i386 libedit2:i386
  libelf1:i386 libexpat1:i386 libffi6:i386 libflac8:i386 libfreetype6:i386
  libgcc1:i386 libgcrypt20:i386 libgl1-mesa-dri:i386 libgl1-mesa-glx:i386
  libglapi-mesa:i386 libglib2.0-0:i386 libglu1-mesa:i386 libgmp10:i386
  libgnutls-deb0-28:i386 libgpg-error0:i386 libgpm2:i386 libgsm1:i386
  libgstreamer-plugins-base0.10-0:i386 libgstreamer0.10-0:i386
  libhogweed2:i386 libice6:i386 libjack-jackd2-0:i386 libjson-c2:i386
  liblcms2-2:i386 libldap-2.4-2:i386 libllvm3.5:i386 liblzma5:i386
  libmp3lame0:i386 libmpg123-0:i386 libncurses5:i386 libnettle4:i386
  libogg0:i386 libopenal1:i386 libopenjpeg5:i386 libopus0:i386
  liborc-0.4-0:i386 libp11-kit0:i386 libpciaccess0:i386 libpcre3:i386
  libpng12-0:i386 libpulse0:i386 libsamplerate0:i386 libsasl2-2:i386
  libsasl2-modules:i386 libsasl2-modules-db:i386 libschroedinger-1.0-0:i386
  libselinux1:i386 libsm6:i386 libsndfile1:i386 libspeex1:i386
  libspeexdsp1:i386 libssl1.0.0:i386 libstdc++6:i386 libsystemd0:i386
  libtasn1-6:i386 libtheora0:i386 libtinfo5:i386 libtxc-dxtn-s2tc0:i386
  libudev1:i386 libuuid1:i386 libva1:i386 libvdpau1:i386 libvorbis0a:i386
  libvorbisenc2:i386 libvpx1:i386 libwine:i386 libwrap0:i386 libx11-6:i386
  libx11-xcb1:i386 libx264-142:i386 libxau6:i386 libxcb-dri2-0:i386
  libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386 libxcb-sync1:i386
  libxcb1:i386 libxcursor1:i386 libxdamage1:i386 libxdmcp6:i386 libxext6:i386
  libxfixes3:i386 libxi6:i386 libxml2:i386 libxrender1:i386 libxshmfence1:i386
  libxtst6:i386 libxvidcore4:i386 libxxf86vm1:i386 va-driver-all:i386
  vdpau-va-driver:i386 wine32:i386 zlib1g:i386
Suggested packages:
  glibc-doc:i386 rng-tools:i386 gnutls-bin:i386 gpm:i386
  libvisual-0.4-plugins:i386 gstreamer-codec-install:i386
  gnome-codec-install:i386 gstreamer0.10-tools:i386
  gstreamer0.10-plugins-base:i386 jackd2:i386 liblcms2-utils:i386
  libportaudio2:i386 opus-tools:i386 libsasl2-modules-otp:i386
  libsasl2-modules-ldap:i386 libsasl2-modules-sql:i386
  libsasl2-modules-gssapi-mit:i386 libsasl2-modules-gssapi-heimdal:i386
  speex:i386 nvidia-vdpau-driver:i386 vdpau-driver:i386 xvba-va-driver:i386
Recommended packages:
  xml-core:i386
The following NEW packages will be installed:
  gcc-4.9-base:i386 i965-va-driver:i386 libasound2:i386
  libasound2-plugins:i386 libasyncns0:i386 libattr1:i386 libavcodec56:i386
  libavresample2:i386 libavutil54:i386 libbsd0:i386 libc6:i386 libc6-i686:i386
  libcap2:i386 libdb5.3:i386 libdbus-1-3:i386 libdrm-intel1:i386
  libdrm-nouveau2:i386 libdrm-radeon1:i386 libdrm2:i386 libedit2:i386
  libelf1:i386 libexpat1:i386 libffi6:i386 libflac8:i386 libfreetype6:i386
  libgcc1:i386 libgcrypt20:i386 libgl1-mesa-dri:i386 libgl1-mesa-glx:i386
  libglapi-mesa:i386 libglib2.0-0:i386 libglu1-mesa:i386 libgmp10:i386
  libgnutls-deb0-28:i386 libgpg-error0:i386 libgpm2:i386 libgsm1:i386
  libgstreamer-plugins-base0.10-0:i386 libgstreamer0.10-0:i386
  libhogweed2:i386 libice6:i386 libjack-jackd2-0:i386 libjson-c2:i386
  liblcms2-2:i386 libldap-2.4-2:i386 libllvm3.5:i386 liblzma5:i386
  libmp3lame0:i386 libmpg123-0:i386 libncurses5:i386 libnettle4:i386
  libogg0:i386 libopenal1:i386 libopenjpeg5:i386 libopus0:i386
  liborc-0.4-0:i386 libp11-kit0:i386 libpciaccess0:i386 libpcre3:i386
  libpng12-0:i386 libpulse0:i386 libsamplerate0:i386 libsasl2-2:i386
  libsasl2-modules:i386 libsasl2-modules-db:i386 libschroedinger-1.0-0:i386
  libselinux1:i386 libsm6:i386 libsndfile1:i386 libspeex1:i386
  libspeexdsp1:i386 libssl1.0.0:i386 libstdc++6:i386 libsystemd0:i386
  libtasn1-6:i386 libtheora0:i386 libtinfo5:i386 libtxc-dxtn-s2tc0:i386
  libudev1:i386 libuuid1:i386 libva1:i386 libvdpau1:i386 libvorbis0a:i386
  libvorbisenc2:i386 libvpx1:i386 libwine:i386 libwrap0:i386 libx11-6:i386
  libx11-xcb1:i386 libx264-142:i386 libxau6:i386 libxcb-dri2-0:i386
  libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386 libxcb-sync1:i386
  libxcb1:i386 libxcursor1:i386 libxdamage1:i386 libxdmcp6:i386 libxext6:i386
  libxfixes3:i386 libxi6:i386 libxml2:i386 libxrender1:i386 libxshmfence1:i386
  libxtst6:i386 libxvidcore4:i386 libxxf86vm1:i386 va-driver-all:i386
  vdpau-va-driver:i386 wine-bin:i386 wine32:i386 zlib1g:i386
0 upgraded, 114 newly installed, 0 to remove and 0 not upgraded.
Need to get 62.0 MB of archives.
After this operation, 256 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  gcc-4.9-base:i386 libgcc1:i386 libc6:i386 libssl1.0.0:i386 libstdc++6:i386
  libudev1:i386 libattr1:i386 liblzma5:i386 libtinfo5:i386 libncurses5:i386
  libpcre3:i386 libselinux1:i386 libuuid1:i386 zlib1g:i386 libcap2:i386
  libdb5.3:i386 libbsd0:i386 libedit2:i386 libgpg-error0:i386 libgcrypt20:i386
  libgmp10:i386 libnettle4:i386 libhogweed2:i386 libffi6:i386 libp11-kit0:i386
  libtasn1-6:i386 libgnutls-deb0-28:i386 libgpm2:i386 libsasl2-modules-db:i386
  libsasl2-2:i386 libldap-2.4-2:i386 libwrap0:i386 libxml2:i386 libdrm2:i386
  libpciaccess0:i386 libdrm-intel1:i386 libva1:i386 i965-va-driver:i386
  libasound2:i386 libavutil54:i386 libavresample2:i386 libgsm1:i386
  libmp3lame0:i386 libopenjpeg5:i386 libopus0:i386 liborc-0.4-0:i386
  libschroedinger-1.0-0:i386 libspeex1:i386 libogg0:i386 libtheora0:i386
  libvorbis0a:i386 libvorbisenc2:i386 libvpx1:i386 libx264-142:i386
  libxvidcore4:i386 libavcodec56:i386 libsamplerate0:i386
  libjack-jackd2-0:i386 libasyncns0:i386 libdbus-1-3:i386 libice6:i386
  libjson-c2:i386 libsm6:i386 libflac8:i386 libsndfile1:i386 libsystemd0:i386
  libxau6:i386 libxdmcp6:i386 libxcb1:i386 libx11-6:i386 libx11-xcb1:i386
  libxext6:i386 libxi6:i386 libxtst6:i386 libpulse0:i386 libspeexdsp1:i386
  libasound2-plugins:i386 libdrm-nouveau2:i386 libdrm-radeon1:i386
  libelf1:i386 libexpat1:i386 libpng12-0:i386 libfreetype6:i386
  libllvm3.5:i386 libgl1-mesa-dri:i386 libglapi-mesa:i386 libxcb-dri2-0:i386
  libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386 libxcb-sync1:i386
  libxfixes3:i386 libxdamage1:i386 libxshmfence1:i386 libxxf86vm1:i386
  libgl1-mesa-glx:i386 libglib2.0-0:i386 libglu1-mesa:i386
  libgstreamer0.10-0:i386 libgstreamer-plugins-base0.10-0:i386 liblcms2-2:i386
  libmpg123-0:i386 libopenal1:i386 libvdpau1:i386 libwine:i386
  libxrender1:i386 libxcursor1:i386 vdpau-va-driver:i386 wine32:i386
  wine-bin:i386 libc6-i686:i386 libtxc-dxtn-s2tc0:i386 libsasl2-modules:i386
  va-driver-all:i386
E: There are problems and -y was used without --force-yes
 [ERROR] Failed To Install Wine x86_64... Exit Code: 100.

What I did wrong    help ChrisTruncer

**Comment by BlueH4t** [comment]
sudo dpkg --add-architecture i386
sudo apt-get update
sudo ./setup.sh

if the problem is gccgo-5
gccgo-5_5.3.1-7 conflicts with golang-go (version 2: 1.3.3-1), ie impossible INSTALLING while not resolve this issue*

*I do not know English, I use google translator

**Comment by ChrisTruncer** [comment]
Did you already have Veil-Evasion installed?  Please use Kali Rolling, not Kali 2.0

**Comment by nikki999** [comment]
At first while trying to install veil evasion i was getting  error code : 100 (wine 32)
then i had updated my kali 2.0 to kali rolling by changing my repo from the official website
and then i had changed my repo as suggested by sud0nick
now while installing veil framework on kali rolling i am facing problem while installing Go Dependencies
it is as follows


 [*] Initializing Go Dependencies Installation...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package gccgo-5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libgcc-5-dev cpp-5 gcc-5

E: Package 'gccgo-5' has no installation candidate
update-alternatives: error: alternative /usr/bin/go-5 for go not registered; not setting
 [*] Installing Go (via TAR)
##### Building Go bootstrap tool.
cmd/dist
cmd/dist/build.go:8:2: cannot find package "bytes" in any of:
	/usr/src/bytes (from $GOROOT)
	($GOPATH not set)
cmd/dist/test.go:9:2: cannot find package "errors" in any of:
	/usr/src/errors (from $GOROOT)
	($GOPATH not set)
cmd/dist/build.go:9:2: cannot find package "flag" in any of:
	/usr/src/flag (from $GOROOT)
	($GOPATH not set)
cmd/dist/build.go:10:2: cannot find package "fmt" in any of:
	/usr/src/fmt (from $GOROOT)
	($GOPATH not set)
cmd/dist/util.go:10:2: cannot find package "io/ioutil" in any of:
	/usr/src/io/ioutil (from $GOROOT)
	($GOPATH not set)
cmd/dist/test.go:12:2: cannot find package "log" in any of:
	/usr/src/log (from $GOROOT)
	($GOPATH not set)
cmd/dist/build.go:11:2: cannot find package "os" in any of:
	/usr/src/os (from $GOROOT)
	($GOPATH not set)
cmd/dist/build.go:12:2: cannot find package "os/exec" in any of:
	/usr/src/os/exec (from $GOROOT)
	($GOPATH not set)
cmd/dist/build.go:13:2: cannot find package "path/filepath" in any of:
	/usr/src/path/filepath (from $GOROOT)
	($GOPATH not set)
cmd/dist/test.go:16:2: cannot find package "regexp" in any of:
	/usr/src/regexp (from $GOROOT)
	($GOPATH not set)
cmd/dist/util.go:14:2: cannot find package "runtime" in any of:
	/usr/src/runtime (from $GOROOT)
	($GOPATH not set)
cmd/dist/util.go:15:2: cannot find package "sort" in any of:
	/usr/src/sort (from $GOROOT)
	($GOPATH not set)
cmd/dist/main.go:11:2: cannot find package "strconv" in any of:
	/usr/src/strconv (from $GOROOT)
	($GOPATH not set)
cmd/dist/build.go:14:2: cannot find package "strings" in any of:
	/usr/src/strings (from $GOROOT)
	($GOPATH not set)
cmd/dist/util.go:18:2: cannot find package "sync" in any of:
	/usr/src/sync (from $GOROOT)
	($GOPATH not set)
cmd/dist/util.go:19:2: cannot find package "sync/atomic" in any of:
	/usr/src/sync/atomic (from $GOROOT)
	($GOPATH not set)
cmd/dist/test.go:19:2: cannot find package "time" in any of:
	/usr/src/time (from $GOROOT)
	($GOPATH not set)
 [ERROR] Failed To Compile Go... Exit Code: 1....




please chris help me as soon as possible..!!

**Comment by veil-evasion** [comment]
Please use the latest version of Kali (Kali rolling)

**Comment by tonymontana111** [comment]
I changed repo  kali rolling and get the same error as before  [ERROR] Failed To Install Wine x86_64... Exit Code: 100.
I have no idea how to fix it I've tried everything but without effectively
Once again I installed  Kali linux  I changed  repo Kali rolling (apt-get update apt-get upgrade and apt-get dist-upgrade)  after that  I installed veil-evasion from github page and still the same error.
Can anyone help

**Comment by veil-evasion** [comment]
Please try a clean Kali-rolling VM. I've previously tested on it and the setup script works for it.

**Comment by nikki999** [comment]
i am using kali rolling itself.i have updated that morning itself
.

**Comment by ChrisTruncer** [comment]
Did you download a new VM, or just change the repos?  Please use a new CLEAN vm.  I just tested again, and I can verify it works on a clean/fresh/new install on Kali-rolling.
