### ISSUE TITLE
Powershell Payloads Not Working

### ISSUE THREAD

**Issue by jhale85446** [Veil-Framework/Veil-Evasion#222]
I am using version 2.21.4 currently. A while ago (June 2015) I was able to get the Powershell Meterpreter reverse TCP payload to work and was having fun with a USB Ducky.  However, recently when the payload is executed all I get in Metasploit is "Sending state (885806 bytes) to 'ip address'" and it just sits there.  I am never able to get a Meterpreter shell.  I've tried this on several different Windows OS's with no luck. Any suggestions?

**Comment by veil-evasion** [comment]
Which payload is it that isn’t working specifically?

I’m using some of them right now and they seem to be ok.  If you can give specifics, it would help me test.



On October 8, 2015 at 3:52:51 PM, Josh Hale (notifications@github.com) wrote:

I am using version 2.21.4 currently. A while ago (June 2015) I was able to get the Powershell Meterpreter reverse TCP payload to work and was having fun with a USB Ducky. However, recently when the payload is executed all I get in Metasploit is "Sending state (885806 bytes) to 'ip address'" and it just sits there. I am never able to get a Meterpreter shell. I've tried this on several different Windows OS's with no luck. Any suggestions?

**Comment by jhale85446** [comment]
Using #22 powershell/meterpreter/rev_tcp.  Tried on Windows 10 and Server 2012 with nothing back.  I'll try a few different OS's here in a few and let you know.

**Comment by coldalfred** [comment]
there is no change on your network or company network from your test it?

**Comment by jhale85446** [comment]
No change in my networks.  I have tried the VMWare internal network and two different physical networks.  Just tried it on a basic wireless network (consumer level Linksys router) with physical machines (target running win7x86) with the same result, sending stage with no shell.  I was able to get the compiled C# payload to work on the same target using the same port (4444) so nothing is blocking the meterpreter shell.

**Comment by jhale85446** [comment]
I can get both the powershell/meterpreter/rev_http and the rev_https work, but not the rev_tcp.

**Comment by ChrisTruncer** [comment]
Ok,

Thanks for that info, helps me narrow it down :)

**Comment by ChrisTruncer** [comment]
sweet, this is now fixed.  Thanks for letting us know!

**Comment by jhale85446** [comment]
No problem Chris.  Thank you for the work you do on this outstanding project.
