### ISSUE TITLE
Internal error #2. Unable to generate output. Please run /root/Veil-Evasion/config/update.py manually

### ISSUE THREAD

**Issue by Ianvdh** [Veil-Framework/Veil-Evasion#223]
Hi every time i want to create an payload i get the following error and dont know how to fix it. Can someone please help. Internal error #2. Unable to generate output. Please run /root/Veil-Evasion/config/update.py manually

**Comment by ChrisTruncer** [comment]
Did you do what the error says?

**Comment by ChrisTruncer** [comment]
I'm going to close this out for now.  Please try doing what the error message says and then if you still have problems let me know.

**Comment by Ianvdh** [comment]
I did what the message said but same error occur. Thats why im here for help

**Comment by ChrisTruncer** [comment]
Have you ran the setup script?

**Comment by jacksql** [comment]
Listen hard to explain?
Or you do not have time for a few words

**Comment by Ianvdh** [comment]
What are you talking about?


Sent from my Samsung device

-------- Original message --------

**Comment by hosemn** [comment]
@Ianvdh I'd ignore the comment from JackSQL, it looks like spam to me. It's possible he's follwing the repo via email, and his email account was taken over and the spammer replied to this thread. Aside from that comment, he's essentially inactive on GitHub.

**Comment by Ianvdh** [comment]
Thank you hosemn for the heads up. Keep up the gr8 work


Sent from my Samsung device

-------- Original message --------
