### ISSUE TITLE
generate without encoding 

### ISSUE THREAD

**Issue by shufan123** [Veil-Framework/Veil-Evasion#224]
Hello,
i know you didn't include the powershell which opened a hidden internet explorer instance ( i can't understand the reason but it has been very very useful for me) but i wanted to enhance it a bit(extend its functionality) and when i try to decode it from base64 to ASCII i get a non-understandable string so is there something i missed about the obfuscation method?.
can you help me generate the bat file without encoding or even give the correct way to decode it ..
a very nice one @pyrohaz4good and great effort.
Thanks a billion.

**Comment by ChrisTruncer** [comment]
Just look at the original code in the powershell module.  It's not encoded when looking at it.

**Comment by pyrohaz4good** [comment]
@shufan123 thanks! I have to do a new pull request on the latest metasploit branch and rebase my code. Once I do that, I'll resubmit my pull request to add this powershell module. I'm glad it was helpful to you. I also use it a lot as user-agent monitoring has become pretty common.

**Comment by shufan123** [comment]
@pyrohaz4good it really is a very good yet very simple idea but its biggest problem is powershell as most user-agent monitoring also monitor powershell usage and restrict it so i wanted to wrap it up in something else so it doesnt need powershell
