### ISSUE TITLE
Runing Veil-Evasion on Arch Linux

### ISSUE THREAD

**Issue by Gadzev** [Veil-Framework/Veil-Evasion#230]
Is it possible? Because when i run setup.sh it gives me an error about my OS

**Comment by ChrisTruncer** [comment]
No, unless you'll submit us the setup script to make it work :)

**Comment by necrose99** [comment]
i'm working on one for Gentoo @Gadzev , it will use wine-tricks , 
thus one can deploy 64 bit windows 7 (32 bit compatible) and 32 bit only windows 7 wine images. 
as well as wipe scripts. (can test X64_86-AMD bit for g'its & sh'iggles ) 

app-emulation/veil-wine  and scripts , etc, ( ie wine-tricks/wget packages) if i had a package manager probe ? ie apt-get , pacman, exists emerge (pure Gentoo) , equo (Sabayon/Gentoo variants) 
net-analyzer/veil-evasion
net-analyzer/veil-catapult
net-analyzer/veil-ordnance
net-analyzer/Veil-Pillage
net-analyzer/veil-meta (pull in scripts) / packages.

/home/$user/.veil-wine 
at the moment I'm trying from sources , however I can rig ebuilds to use Debian installs. 
but that could rig breakage.  

Ebuilds aren't much but bash/+API but getting them right can be frustrating,::person_frowning:: but it governs the build from source's in Gentoo. 


(https://bbs.archlinux.org/viewtopic.php?id=187558 Debtap - A script to convert .deb packages to Arch Linux packages) which in your case could save a crap ton of grief. ::smiley_cat::
