### ISSUE TITLE
Veil Evasion Installation error on Kali linux 64bits

### ISSUE THREAD

**Issue by Inguu** [Veil-Framework/Veil-Evasion#231]
I tried everything to install Veil Evasion on my laptop, i have kali linux 64bits and also ubuntu 14.04 64bits, and i can't install it in any of the two OS.

It get this error:

E: Package 'wine32' has no installation candidate
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package win-bin:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
libwine wine

E: Package 'wine-bin:i386' has no installation candidate
[ERROR] Failed To Install Wine x86_64... Exit Code: 100.

Please help i tried everything i could.

**Comment by necrose99** [comment]
winetricks is handy to deploy packages , have a script ,in progress to do win32 or wine64 
./veil-wine , and to pull in pkg to script a DOD-wipe /file-shred it  , as I F'ont want ./wine or ./wine-steam etc got my regular stuff their. 
any where near veil-framwork , I'd rather have it in its own wine-prefix , which can be done with winetricks.
along with wget deploy lib's , [Microsoft Visual C++ for python] (http://www.microsoft.com/en-us/download/details.aspx?id=44266) and just about anything else. python freeze py2exe or c++ outputs of veil and or py2c++ https://github.com/pradyunsg/Py2C ,https://shedskin.github.io/ or some other py to C parse , Which might be of use for veil. 
Gentoo/Sabayon wise , you can have 64bit wine but deploy 32 only, in prefix etc...

Anyhow , Working on trying to pkg veil-framwork myself.

**Comment by Inguu** [comment]
is already done.. i just run dpkg --configure -a, and it works thank you for helping me anyway  n_n

Date: Wed, 18 Nov 2015 13:34:44 -0800

**Comment by Inguu** [comment]
is already done.. i just run dpkg --configure -a, and add a few repositories to sources.list, and it works thank you for helping me anyway  n_n

Date: Wed, 18 Nov 2015 20:52:02 -0800

**Comment by ChrisTruncer** [comment]
Please change your mirrors you are using.  I can confirm that this is the correct package, so your mirror might be having an issue with this.  Just change them and the problem will almost certainly fix itself.

**Comment by metalcode93** [comment]
i'm new here, @Inguu  please can you tell me what repository you add to source list ? i really need veil for my project, i exactly have the same problem like yours, please help me

**Comment by LewPa** [comment]
Hi I'm very new to kali and have recently installed veil-evasion through git clone when I run the setup.sh error i get this:
![screenshot from 2016-07-10 22-39-39](https://cloud.githubusercontent.com/assets/20386863/16715961/da5f171c-46e6-11e6-83bb-fa164fe8dd03.png)
any help is much appreciated hopefully someone gets back to me.

**Comment by Engelon1** [comment]
I have the same issue
[sources.txt](https://github.com/Veil-Framework/Veil-Evasion/files/356400/sources.txt)

**Comment by LewPa** [comment]
Thank you for the help that seems to have helped but now i encounter this.
![screenshot from 2016-07-12 20-59-59](https://cloud.githubusercontent.com/assets/20386863/16779729/55871d7e-486b-11e6-80fd-6e4858161b16.png)
![screenshot from 2016-07-12 20-59-50](https://cloud.githubusercontent.com/assets/20386863/16779730/57b1e6ba-486b-11e6-8a3b-01e2b99bb461.png)

**Comment by Engelon1** [comment]
I wasn't really trying to help, I was just saying that I get the same error and would like some help too.
Although I can see that now it is complaining about duplicates in your sources.list

**Comment by LewPa** [comment]
Since you wasn't really trying to help me I guess I won't really try to help you. But I just wanted to let you know I got it to work.
![screenshot from 2016-07-13 19-25-28](https://cloud.githubusercontent.com/assets/20386863/16812980/7622e90c-4927-11e6-857b-d55dbe023eab.png)

**Comment by Engelon1** [comment]
No need to get salty, I wasn't trying to help you because I had the same problem and if I could have solved your problem I would have been able to solve my  problem and not been here in the first place.
I never meant for you to take my comment negatively.

**Comment by ChrisTruncer** [comment]
off-topic
