### ISSUE TITLE
RPC Server Documentation or Examples

### ISSUE THREAD

**Issue by ethack** [Veil-Framework/Veil-Evasion#232]
I'd like to integrate with Veil-Evasion, and it appears that the best way to do this is through the builtin RPC server. I was hoping that you'd have some Python example code that interacts with the RPC server or maybe some documentation to point me to. The only documentation I've found is here:
https://github.com/Veil-Framework/Veil-Evasion/blob/master/Veil-Evasion.py#L30-L47

And I've tried connecting via netcat to see if I could get it to respond. I'm using the Kali veil-evasion package and the version number is 2.21.4. I tried sending a payload like `{"method":"version"}` and Evasion gave the following output:
```
root@kali:~# veil-evasion --rpc
[*] Starting Veil-Evasion RPC server...
dispatch_notification({u'method': u'version'})
[!] Shutting down Veil-Evasion RPC server...
```

In the netcat window I did not receive any output.
```
root@kali:~# nc 127.0.0.1 4242
{"method":"version"}
```

I have a feeling netcat doesn't work because there is more to the communication protocol than I am aware of. I did some digging into the library used and found an example client but haven't had much luck with it yet.

https://github.com/niligulmohar/python-symmetric-jsonrpc/blob/master/examples/client.py

https://github.com/tomsteele/veil-evasion-api appears to use the RPC server in Go. I tried looking there as well but am not familiar enough with Go to find what I need. Maybe @tomsteele could provide some input as well, at least on the protocol?

**Comment by ChrisTruncer** [comment]
I don't have anything in the way of this currently unfortunately.  If that's something someone wants to submit to us, I'm pretty sure it would get a quick acceptance :)

**Comment by ChrisTruncer** [comment]
I'll close the issue, but leave it open for now since it's obviously/hopefully going to have some valuable information.

**Comment by ethack** [comment]
Bummer, I was hoping you'd have tested the RPC code when you wrote it and be able to provide even a basic example.  If I can get it working how would you like docs/example contributions formatted?  Inline in the code, an example script in a separate file, a separate file containing documentation?
