### ISSUE TITLE
Veil evasion on kali 2.0 empty payloads

### ISSUE THREAD

**Issue by eranvak** [Veil-Framework/Veil-Evasion#237]
Hi, i am installing veil evasion on my clean installation kali 2.0 (via git clone)
when i am entering the veil i see 0 payloads loaded.

wth?

**Comment by ChrisTruncer** [comment]
Please review any of the other issues which address this problem.

**Comment by tuannvm** [comment]
perhaps this could help [link](https://null-byte.wonderhowto.com/forum/fix-veil-evasion-error-compiling-python-payloads-and-zero-payload-list-0169604/)
