### ISSUE TITLE
wine: cannot find '/root/.wine64/drive_c/Python27/python.exe'

### ISSUE THREAD

**Issue by OscarDgrouch** [Veil-Framework/Veil-Evasion#240]
I keep getting this error message when generating when generating a 64x payload
"wine: cannot find '/root/.wine64/drive_c/Python27/python.exe'". 

As it was instructed I deleted my WINE profile and reinstall again, however after reinstalling i kept getting the same error everytime i tried to generate a x64 payload, thanks
 

********************************************************************************************************************
---
Installed Go for windows/386 in /var/lib/veil-evasion/go
Installed commands in /var/lib/veil-evasion/go/bin

 [*] Updating Veil-Framework Configuration...

 Veil-Framework configuration:

 [*] OPERATING_SYSTEM = Kali
 [*] TERMINAL_CLEAR = clear
 [*] TEMP_DIR = /tmp/
 [*] MSFVENOM_OPTIONS = 
 [*] METASPLOIT_PATH = /usr/share/metasploit-framework/
 [*] MSFVENOM_PATH = /usr/bin/
 [*] PYINSTALLER_PATH = /usr/share/pyinstaller/

 [*] VEIL_EVASION_PATH = /usr/share/veil-evasion/
 [*] PAYLOAD_SOURCE_PATH = /var/lib/veil-evasion/output/source/
 [*] PAYLOAD_COMPILED_PATH = /var/lib/veil-evasion/output/compiled/
 [*] GENERATE_HANDLER_SCRIPT = True
 [*] HANDLER_PATH = /var/lib/veil-evasion/output/handlers/
 [*] HASH_LIST = /var/lib/veil-evasion/output/hashes.txt

 [*] VEIL_CATAPULT_PATH = /usr/share/veil-catapult/
 [*] CATAPULT_RESOURCE_PATH = /var/lib/veil-evasion/output/catapult/

 [*] SPAWN_CATAPULT_HANDLER = false

 Configuration File Written To '/etc/veil/settings.py'
*****************************************************************************************************************

**Comment by ChrisTruncer** [comment]
Yeah, we don't automate the install process for x64 payloads (since to be honest I've never heard anyone using Veil to generate one).  Currently, we only automate the x32 install in Wine.  So since you're trying to invoke the x64, it (obviously) isn't finding it.  Now you could follow the same process to install x64 python on x64 wine, but I don't believe you'll be able to use x32 wine then.

Your other option is to make a payload and use x64 windows, install the dependencies there (in a VM?) and then converting it into an exe.

I'll close this since that's essentially the only way of doing it, but feel free to comment or ask any other questions related to this in this thread.

**Comment by necrose99** [comment]
Already working on Gentoo automation scripts for wine deploys to setup. I /home/$user/.veil-wine/
Automation of wine for 32 or 64 is doable via bash. 

Add shreding, for veil ie dod-wipe of folder doable. 
However a side order of Firejail, would be useful for local systems security.  Don't want to run under wine , and have it eat up much cpu.

**Comment by OscarDgrouch** [comment]
Awesome, thank you!!

**Comment by necrose99** [comment]
anyhow if you have wine-tricks , you can also get a list of packages and settings and build your own. 

i for one don't want to by accident infect my wine containers. were i have my day to day or IE crostie-Linux apps etc. ALL work and no MMO's during long compiles makes for a dull evening.... 
WINEPREFIX=$HOME/prefix32 WINEARCH='win32' wine 'wineboot'
Where WINEPREFIX is the directory for the prefix
ie .veilwine64 or 32 http://www.dedoimedo.com/computers/winetricks.html

point being is One could rapidly deploy and then sanitize/(self-destruct) a perfect VEil-wine environment on demand. 
anyhow winetrics gui or va command-line wget to cashed-dir  etc, fairly simple to make a bash deploy script for a number of things. 

ie games etc.
