### ISSUE TITLE
@VeilFramework === [ERROR] Internal Issue. Couldn't Detect OS Information...

### ISSUE THREAD

**Issue by solankirohit** [Veil-Framework/Veil-Evasion#241]

**Comment by ChrisTruncer** [comment]
You didn't provide any information at all.  What OS/Distro are you using, and what's in your /etc/issue?

**Comment by Matthew0292** [comment]
my etc/issue: Kali GNU/Linux Rolling \n \l

**Comment by ChrisTruncer** [comment]
@Matthew0292 does it not work for you? Can you please try using Kali 2 which is the current supported version of Kali?

**Comment by Matthew0292** [comment]
unfortunately it doesn't work, I will try to use Kali 2, although it is better suited to the current version of me, because I have examples in the book based on version 1.0.6

**Comment by ChrisTruncer** [comment]
I'll take a look into this, but Kali 1 won't be officially supported.  I can't guarantee the packages in there are up to date with that Veil needs, so that's the problem

**Comment by ChrisTruncer** [comment]
actually, @Matthew0292 can you give me your /etc/os-release?

**Comment by ChrisTruncer** [comment]
I just received the /etc/os-release from a kali 1 user (thanks to Crash on #kali-linux) and Veil's setup code should be properly parsing kali 1.0 and not run into this issue.  Did you modify it at all?

Please post your /etc/os-issue so I can look at it.

**Comment by Matthew0292** [comment]
os-release:
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
#VERSION="3~alpha1 (unknown)"
#VERSION_ID="3~alpha1"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.kali.org/"
SUPPORT_URL="http://forums.kali.org/"
BUG_REPORT_URL="http://bugs.kali.org/"

**Comment by Matthew0292** [comment]
I don't have os-issue in etc

**Comment by FAROUKix** [comment]
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
#VERSION="3~alpha1 (unknown)"
#VERSION_ID="3~alpha1"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.kali.org/"
SUPPORT_URL="http://forums.kali.org/"
BUG_REPORT_URL="http://bugs.kali.org/"

me to i have prolm
 [ERROR] Internal Issue. Couldn't Detect OS Information... 

Kali 2 32bit

help me plz :'(

@ChrisTruncer

**Comment by ChrisTruncer** [comment]
Can you please try on a new kali install?  I can't seem to re-create this on a clean install.

**Comment by FAROUKix** [comment]
i use kali sytem not VM ... 
@ChrisTruncer

**Comment by FAROUKix** [comment]
┌┼─┼─ root @ anassfarouki ─┤├─ 14:13:16 Wed Jan 06 ─┤├─ ~/Veil-Evasion/setup ─┤ 
└┼─#─┤▶ ./setup.sh
==========================================================================
 Veil-Evasion Setup Script | [Updated]: 2015-07-06
==========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
==========================================================================


 [ERROR] Internal Issue. Couldn't Detect OS Information...

**Comment by rshmode** [comment]
I had the same issue, and I think I've found out why. I've added the kali-rolling repo (as described here http://docs.kali.org/general-use/kali-linux-sources-list-repositories) to my sources.list which appears to have messed with the results of the declaration of the $os & $version global variables in the script (i.e. $version is blank). This appears to  cause the OS detection to fail with the message that people have been posting above. My current work around has been to comment out the $os & $version declarations at the start of the script and replace them with statically declared values e.g.
```
#os="$(awk -F '=' '/^ID=/ {print $2}' /etc/os-release 2>&-)"
#version=$(awk -F '=' '/^VERSION_ID=/ {print $2}' /etc/os-release 2>&-)
os=kali
version=2
```

For reference, here is the output of my /etc/os-release - notice the VERSION has been commented out, which is probably why the $version declaration in setup.sh returns null!
```
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
#VERSION="3~alpha1 (unknown)"
#VERSION_ID="3~alpha1"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.kali.org/"
SUPPORT_URL="http://forums.kali.org/"
BUG_REPORT_URL="http://bugs.kali.org/"
```

However once I re-ran setup.sh - it failed when it was compiling Go (I realise this should probably be submitted as a separate issue)
````
# cmd/pprof
/var/lib/veil-evasion/go/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
/var/lib/veil-evasion/go/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
runtime/cgo(.text): unexpected relocation type 298
runtime/cgo(.text): unexpected relocation type 298
# cmd/go
/var/lib/veil-evasion/go/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
/var/lib/veil-evasion/go/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
runtime/cgo(.text): unexpected relocation type 298
runtime/cgo(.text): unexpected relocation type 298
 [ERROR] Failed To Compile Go... Exit Code: 2.
````
