### ISSUE TITLE
gnome-control center being removed after installing veil-evasion

### ISSUE THREAD

**Issue by shrkboy** [Veil-Framework/Veil-Evasion#242]
hey, i've got some problem after installing veil-evasion
when the veil-evasion setup is running and when it tried to install wine i396 binaries, it said some package will removed. well ok, i can take that. but after i read what was the package that was going to be removed, there was gnome-control-center.
here what's looklike in terminal

The following packages will be REMOVED:
  caribou caribou-antler empathy gnome-contacts gnome-control-center
  gnome-core gnome-orca gstreamer1.0-plugins-bad kali-desktop-gnome
  libatk1.0-dev libcairo2-dev libcheese-gtk23 libcheese7 libfarstream-0.2-2
  libgail-common libgail18 libgdk-pixbuf2.0-dev libglib2.0-dev libgtk2.0-dev
  libhogweed2 libnettle4 libpango1.0-dev libpcre3-dev libsoup2.4-dev
  libtelepathy-farstream3 libwebkit-dev libwebkitgtk-dev python-pyatspi
  python3-pyatspi totem totem-plugins vega

after it i cant open the gnome-control-center and the other package that removed anymore
is it a bug or is it just like that?

**Comment by ChrisTruncer** [comment]
Can you find and let me know exactly which package is removing it?  I don’t believe we actually remove anything, just install packages.



On December 9, 2015 at 3:52:38 PM, shrkboy (notifications@github.com) wrote:

hey, i've got some problem after installing veil-evasion
when the veil-evasion setup is running and when it tried to install wine i396 binaries, it said some package will removed. well ok, i can take that. but after i read what was the package that was going to be removed, there was gnome-control-center.
here what's looklike in terminal

The following packages will be REMOVED:
caribou caribou-antler empathy gnome-contacts gnome-control-center
gnome-core gnome-orca gstreamer1.0-plugins-bad kali-desktop-gnome
libatk1.0-dev libcairo2-dev libcheese-gtk23 libcheese7 libfarstream-0.2-2
libgail-common libgail18 libgdk-pixbuf2.0-dev libglib2.0-dev libgtk2.0-dev
libhogweed2 libnettle4 libpango1.0-dev libpcre3-dev libsoup2.4-dev
libtelepathy-farstream3 libwebkit-dev libwebkitgtk-dev python-pyatspi
python3-pyatspi totem totem-plugins vega

after it i cant open the gnome-control-center and the other package that removed anymore
is it a bug or is it just like that?

**Comment by shrkboy** [comment]
here is what it look like in terminal 
 
[*] Installing (Wine) i386 Binaries
Reading package lists... Done
Building dependency tree       
Reading state information... Done

The following packages were automatically installed and are no longer required:
  commix empathy-common gir1.2-gtk-2.0 gstreamer1.0-clutter-3.0
  gstreamer1.0-nice icu-devtools libairspy0 libasan2 libavformat-ffmpeg56
  libbladerf0 libbladerf1 libboost-program-options1.55.0 libboost-regex1.55.0
  libboost-serialization1.55.0 libboost-test1.55.0 libbs2b0
  libcairo-script-interpreter2 libchamplain-0.12-0 libchamplain-gtk-0.12-0
  libclutter-gst-3.0-0 libcodec2-0.4 libcomedi0 libde265-0 libebackend-1.2-7
  libedata-cal-1.2-23 libelfg0 libfontconfig1-dev libfreetype6-dev
  libgcc-5-dev libgsl0ldbl libharfbuzz-dev libharfbuzz-gobject0
  libhidapi-libusb0 libicu-dev libinput10 libjavascriptcoregtk-1.0-dev
  libmirisdr0 libmpx0 libopenvg1-mesa libosmosdr0 libpcre16-3 libpcre32-3
  libpcrecpp0 libpgm-5.1-0 libpixman-1-dev libpng12-dev libprotobuf9
  libqt5core5a libqt5dbus5 libqt5test5 libqwt-dev libqwt6 libsodium13
  libsoundtouch1 libssh-gcrypt-4 libstdc++-5-dev libvolk-bin libvolk0.0.0
  libvolk1.1 libxcb-shm0-dev libxcomposite-dev libxcursor-dev libxft-dev
  libxi-dev libxinerama-dev libxml2-dev libxml2-utils libxrandr-dev
  libxrender-dev libzmq3 python-cheetah python-networkx python-pygraphviz
  python-qwt5-qt4 python-zmq qthid-fcd-controller qttranslations5-l10n
  telepathy-gabble telepathy-logger telepathy-salut totem-common
  x11proto-composite-dev x11proto-randr-dev x11proto-render-dev
  x11proto-xinerama-dev zlib1g-dev
Use 'apt-get autoremove' to remove them.

The following extra packages will be installed:
  accountsservice adwaita-icon-theme bash-completion dnsmasq-base fonts-wine
  gcc-5-base:i386 gir1.2-atk-1.0 gir1.2-gdkpixbuf-2.0 gir1.2-gtk-2.0
  gir1.2-pango-1.0 gir1.2-soup-2.4 gnome-desktop3-data
  gstreamer1.0-clutter-3.0 gtk2-engines-pixbuf i965-va-driver
  i965-va-driver:i386 icu-devtools initscripts ldap-utils libaccountsservice0
  libarchive13 libasan2 libasound2 libasound2:i386 libasound2-data
  libasound2-plugins libasound2-plugins:i386 libass5 libasyncns0:i386
  libatk1.0-0 libatk1.0-data libatomic1 libattr1:i386 libavcodec-ffmpeg56
  libavcodec-ffmpeg56:i386 libavformat-ffmpeg56 libavresample-ffmpeg2
  libavresample-ffmpeg2:i386 libavutil-ffmpeg54 libavutil-ffmpeg54:i386
  libbs2b0 libbsd0:i386 libc-dev-bin libc6 libc6:i386 libc6-dbg libc6-dev
  libc6-i686:i386 libcairo-gobject2 libcairo-script-interpreter2 libcairo2
  libcap2 libcap2:i386 libcilkrts5 libclutter-gst-3.0-0 libcrystalhd3
  libcrystalhd3:i386 libcurl3-gnutls libdb5.3 libdb5.3:i386 libdbus-1-3:i386
  libde265-0 libdrm-amdgpu1 libdrm-amdgpu1:i386 libdrm-dev libdrm-intel1
  libdrm-intel1:i386 libdrm-nouveau2 libdrm-nouveau2:i386 libdrm-radeon1
  libdrm-radeon1:i386 libdrm2 libdrm2:i386 libedit2 libedit2:i386
  libegl1-mesa-drivers libelf1 libelf1:i386 libexpat1 libexpat1:i386
  libexpat1-dev libfdisk1 libffi-dev libffi6 libffi6:i386 libflac8
  libflac8:i386 libfreetype6 libfreetype6:i386 libfreetype6-dev libgail-3-0
  libgcc-5-dev libgcc1 libgcc1:i386 libgcrypt20 libgcrypt20:i386
  libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgl1-mesa-dev libgl1-mesa-dri
  libgl1-mesa-dri:i386 libgl1-mesa-glx libgl1-mesa-glx:i386 libglapi-mesa
  libglapi-mesa:i386 libgles1-mesa libgles2-mesa libglib2.0-0
  libglib2.0-0:i386 libglib2.0-bin libglu1-mesa libglu1-mesa:i386
  libglu1-mesa-dev libgme0 libgmp-dev libgmp10 libgmp10:i386 libgmpxx4ldbl
  libgnutls-deb0-28 libgnutls-deb0-28:i386 libgnutls-openssl27 libgomp1
  libgpg-error0 libgpg-error0:i386 libgpm2:i386 libgrilo-0.2-1 libgsm1:i386
  libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libgtk-3-0 libgtk-3-common
  libgtk2.0-0 libgtk2.0-bin libhogweed4 libhogweed4:i386 libice6:i386
  libicu-dev libicu55:i386 libitm1 libjack-jackd2-0 libjack-jackd2-0:i386
  libjavascriptcoregtk-1.0-0 libjavascriptcoregtk-1.0-dev libjson-c2:i386
  liblcms2-2:i386 libldap-2.4-2 libldap-2.4-2:i386 libllvm3.7 libllvm3.7:i386
  liblsan0 liblzma5 liblzma5:i386 libmodplug1 libmount1 libmp3lame0
  libmp3lame0:i386 libmpg123-0 libmpg123-0:i386 libmpx0 libncurses5:i386
  libnettle6 libnettle6:i386 libnghttp2-14 libnuma1:i386 libogg0:i386
  libopenal-data libopenal1 libopenal1:i386 libopenjpeg5 libopenjpeg5:i386
  libopus0 libopus0:i386 liborc-0.4-0:i386 libp11-kit0 libp11-kit0:i386
  libpam-systemd libpango-1.0-0 libpango1.0-0 libpangocairo-1.0-0
  libpangoft2-1.0-0 libpangoxft-1.0-0 libpcap0.8 libpcap0.8:i386 libpciaccess0
  libpciaccess0:i386 libpcre3 libpcre3:i386 libpcre32-3 libpng12-0
  libpng12-0:i386 libpng12-dev libpulse-mainloop-glib0 libpulse0
  libpulse0:i386 libpulsedsp libquadmath0 librtmp1 libsamplerate0:i386
  libsasl2-2 libsasl2-2:i386 libsasl2-modules libsasl2-modules:i386
  libsasl2-modules-db libsasl2-modules-db:i386 libschroedinger-1.0-0:i386
  libseccomp2 libselinux1 libselinux1:i386 libshine3:i386 libsm6:i386
  libsmartcols1 libsnappy1v5 libsnappy1v5:i386 libsndfile1 libsndfile1:i386
  libsoundtouch1 libsoup2.4-1 libsoxr0 libspeex1:i386 libspeexdsp1:i386
  libssh-gcrypt-4 libssl1.0.2 libssl1.0.2:i386 libstdc++-5-dev libstdc++6:i386
  libswresample-ffmpeg1 libswresample-ffmpeg1:i386 libswscale-ffmpeg3
  libswscale-ffmpeg3:i386 libsystemd0 libsystemd0:i386 libtasn1-6
  libtasn1-6:i386 libtheora0 libtheora0:i386 libtinfo5:i386 libtsan0
  libtwolame0 libtwolame0:i386 libtxc-dxtn-s2tc0:i386 libubsan0 libudev1
  libudev1:i386 libuuid1 libuuid1:i386 libva-x11-1 libva-x11-1:i386 libva1
  libva1:i386 libvdpau-va-gl1 libvdpau-va-gl1:i386 libvdpau1 libvdpau1:i386
  libvorbis0a libvorbis0a:i386 libvorbisenc2 libvorbisenc2:i386 libvorbisfile3
  libvpx2 libvpx2:i386 libwavpack1 libwavpack1:i386 libwebkitgtk-1.0-0
  libwebkitgtk-1.0-common libwebp5 libwebp5:i386 libwine libwine:i386
  libwrap0:i386 libx11-6 libx11-6:i386 libx11-dev libx11-xcb-dev libx11-xcb1
  libx11-xcb1:i386 libx264-148 libx264-148:i386 libx265-68 libx265-68:i386
  libxau6:i386 libxcb-dri2-0:i386 libxcb-dri3-0:i386 libxcb-glx0:i386
  libxcb-present0:i386 libxcb-randr0:i386 libxcb-render0:i386
  libxcb-shape0:i386 libxcb-sync1:i386 libxcb-xfixes0:i386 libxcb1:i386
  libxcursor1:i386 libxdamage1:i386 libxdmcp-dev libxdmcp6 libxdmcp6:i386
  libxext6:i386 libxfixes3:i386 libxi-dev libxi6 libxi6:i386 libxml2
  libxml2:i386 libxml2-dev libxrandr-dev libxrandr2 libxrender-dev libxrender1
  libxrender1:i386 libxshmfence-dev libxshmfence1 libxshmfence1:i386
  libxtst6:i386 libxvidcore4 libxvidcore4:i386 libxxf86vm-dev libxxf86vm1
  libxxf86vm1:i386 libzvbi-common libzvbi0 libzvbi0:i386 mesa-common-dev
  mesa-vdpau-drivers mesa-vdpau-drivers:i386 mount ocl-icd-libopencl1
  ocl-icd-libopencl1:i386 p11-kit-modules pulseaudio pulseaudio-module-x11
  pulseaudio-utils systemd systemd-sysv sysvinit-utils totem-common udev
  util-linux va-driver-all va-driver-all:i386 vdpau-driver-all
  vdpau-driver-all:i386 vdpau-va-driver vdpau-va-driver:i386 wget wine
  zlib1g:i386
Suggested packages:
  libsasl2-modules-gssapi-mit libsasl2-modules-gssapi-heimdal lrzip alsa-utils
  glibc-doc glibc-doc:i386 firmware-crystalhd firmware-crystalhd:i386
  rng-tools rng-tools:i386 gmp-doc libgmp10-doc libmpfr-dev gnutls-bin
  gnutls-bin:i386 gpm:i386 gstreamer1.0-tools icu-doc jackd2 jackd2:i386
  liblcms2-utils:i386 libportaudio2:i386 opus-tools opus-tools:i386
  libsasl2-modules-otp libsasl2-modules-ldap libsasl2-modules-sql
  libsasl2-modules-otp:i386 libsasl2-modules-ldap:i386
  libsasl2-modules-sql:i386 libsasl2-modules-gssapi-mit:i386
  libsasl2-modules-gssapi-heimdal:i386 speex:i386 libstdc++-5-doc
  ttf-mscorefonts-installer ttf-mscorefonts-installer:i386 libx265-68-dbg
  libx265-68-dbg:i386 opencl-icd opencl-icd:i386 pavumeter pavucontrol paman
  paprefs systemd-ui systemd-container bootlogd sash util-linux-locales
  xvba-va-driver xvba-va-driver:i386 nvidia-vdpau-driver
  nvidia-legacy-340xx-vdpau-driver nvidia-vdpau-driver:i386
  nvidia-legacy-340xx-vdpau-driver:i386 wine-binfmt dosbox
  wine32-preloader:i386

Recommended packages:
  fonts-wine:i386 xml-core:i386 libwine-gecko-2.40:i386

The following packages will be REMOVED:
  caribou caribou-antler empathy gnome-contacts gnome-control-center
  gnome-core gnome-orca gstreamer1.0-plugins-bad kali-desktop-gnome
  libatk1.0-dev libcairo2-dev libcheese-gtk23 libcheese7 libfarstream-0.2-2
  libgail-common libgail18 libgdk-pixbuf2.0-dev libglib2.0-dev libgtk2.0-dev
  libhogweed2 libnettle4 libpango1.0-dev libpcre3-dev libsoup2.4-dev
  libtelepathy-farstream3 libwebkit-dev libwebkitgtk-dev python-pyatspi
  python3-pyatspi totem totem-plugins vega

please help me

**Comment by ChrisTruncer** [comment]
Are you running into a problem if it removes it?

I’m running on a x64 Kali right now and haven’t had any issues.


On December 9, 2015 at 4:09:15 PM, shrkboy (notifications@github.com) wrote:

here is what it look like in terminal

[*] Installing (Wine) i386 Binaries
Reading package lists... Done
Building dependency tree

Reading state information... Done

The following packages were automatically installed and are no longer required:
commix empathy-common gir1.2-gtk-2.0 gstreamer1.0-clutter-3.0
gstreamer1.0-nice icu-devtools libairspy0 libasan2 libavformat-ffmpeg56
libbladerf0 libbladerf1 libboost-program-options1.55.0 libboost-regex1.55.0
libboost-serialization1.55.0 libboost-test1.55.0 libbs2b0
libcairo-script-interpreter2 libchamplain-0.12-0 libchamplain-gtk-0.12-0
libclutter-gst-3.0-0 libcodec2-0.4 libcomedi0 libde265-0 libebackend-1.2-7
libedata-cal-1.2-23 libelfg0 libfontconfig1-dev libfreetype6-dev
libgcc-5-dev libgsl0ldbl libharfbuzz-dev libharfbuzz-gobject0
libhidapi-libusb0 libicu-dev libinput10 libjavascriptcoregtk-1.0-dev
libmirisdr0 libmpx0 libopenvg1-mesa libosmosdr0 libpcre16-3 libpcre32-3
libpcrecpp0 libpgm-5.1-0 libpixman-1-dev libpng12-dev libprotobuf9
libqt5core5a libqt5dbus5 libqt5test5 libqwt-dev libqwt6 libsodium13
libsoundtouch1 libssh-gcrypt-4 libstdc++-5-dev libvolk-bin libvolk0.0.0
libvolk1.1 libxcb-shm0-dev libxcomposite-dev libxcursor-dev libxft-dev
libxi-dev libxinerama-dev libxml2-dev libxml2-utils libxrandr-dev
libxrender-dev libzmq3 python-cheetah python-networkx python-pygraphviz
python-qwt5-qt4 python-zmq qthid-fcd-controller qttranslations5-l10n
telepathy-gabble telepathy-logger telepathy-salut totem-common
x11proto-composite-dev x11proto-randr-dev x11proto-render-dev
x11proto-xinerama-dev zlib1g-dev
Use 'apt-get autoremove' to remove them.

The following extra packages will be installed:
accountsservice adwaita-icon-theme bash-completion dnsmasq-base fonts-wine
gcc-5-base:i386 gir1.2-atk-1.0 gir1.2-gdkpixbuf-2.0 gir1.2-gtk-2.0
gir1.2-pango-1.0 gir1.2-soup-2.4 gnome-desktop3-data
gstreamer1.0-clutter-3.0 gtk2-engines-pixbuf i965-va-driver
i965-va-driver:i386 icu-devtools initscripts ldap-utils libaccountsservice0
libarchive13 libasan2 libasound2 libasound2:i386 libasound2-data
libasound2-plugins libasound2-plugins:i386 libass5 libasyncns0:i386
libatk1.0-0 libatk1.0-data libatomic1 libattr1:i386 libavcodec-ffmpeg56
libavcodec-ffmpeg56:i386 libavformat-ffmpeg56 libavresample-ffmpeg2
libavresample-ffmpeg2:i386 libavutil-ffmpeg54 libavutil-ffmpeg54:i386
libbs2b0 libbsd0:i386 libc-dev-bin libc6 libc6:i386 libc6-dbg libc6-dev
libc6-i686:i386 libcairo-gobject2 libcairo-script-interpreter2 libcairo2
libcap2 libcap2:i386 libcilkrts5 libclutter-gst-3.0-0 libcrystalhd3
libcrystalhd3:i386 libcurl3-gnutls libdb5.3 libdb5.3:i386 libdbus-1-3:i386
libde265-0 libdrm-amdgpu1 libdrm-amdgpu1:i386 libdrm-dev libdrm-intel1
libdrm-intel1:i386 libdrm-nouveau2 libdrm-nouveau2:i386 libdrm-radeon1
libdrm-radeon1:i386 libdrm2 libdrm2:i386 libedit2 libedit2:i386
libegl1-mesa-drivers libelf1 libelf1:i386 libexpat1 libexpat1:i386
libexpat1-dev libfdisk1 libffi-dev libffi6 libffi6:i386 libflac8
libflac8:i386 libfreetype6 libfreetype6:i386 libfreetype6-dev libgail-3-0
libgcc-5-dev libgcc1 libgcc1:i386 libgcrypt20 libgcrypt20:i386
libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgl1-mesa-dev libgl1-mesa-dri
libgl1-mesa-dri:i386 libgl1-mesa-glx libgl1-mesa-glx:i386 libglapi-mesa
libglapi-mesa:i386 libgles1-mesa libgles2-mesa libglib2.0-0
libglib2.0-0:i386 libglib2.0-bin libglu1-mesa libglu1-mesa:i386
libglu1-mesa-dev libgme0 libgmp-dev libgmp10 libgmp10:i386 libgmpxx4ldbl
libgnutls-deb0-28 libgnutls-deb0-28:i386 libgnutls-openssl27 libgomp1
libgpg-error0 libgpg-error0:i386 libgpm2:i386 libgrilo-0.2-1 libgsm1:i386
libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libgtk-3-0 libgtk-3-common
libgtk2.0-0 libgtk2.0-bin libhogweed4 libhogweed4:i386 libice6:i386
libicu-dev libicu55:i386 libitm1 libjack-jackd2-0 libjack-jackd2-0:i386
libjavascriptcoregtk-1.0-0 libjavascriptcoregtk-1.0-dev libjson-c2:i386
liblcms2-2:i386 libldap-2.4-2 libldap-2.4-2:i386 libllvm3.7 libllvm3.7:i386
liblsan0 liblzma5 liblzma5:i386 libmodplug1 libmount1 libmp3lame0
libmp3lame0:i386 libmpg123-0 libmpg123-0:i386 libmpx0 libncurses5:i386
libnettle6 libnettle6:i386 libnghttp2-14 libnuma1:i386 libogg0:i386
libopenal-data libopenal1 libopenal1:i386 libopenjpeg5 libopenjpeg5:i386
libopus0 libopus0:i386 liborc-0.4-0:i386 libp11-kit0 libp11-kit0:i386
libpam-systemd libpango-1.0-0 libpango1.0-0 libpangocairo-1.0-0
libpangoft2-1.0-0 libpangoxft-1.0-0 libpcap0.8 libpcap0.8:i386 libpciaccess0
libpciaccess0:i386 libpcre3 libpcre3:i386 libpcre32-3 libpng12-0
libpng12-0:i386 libpng12-dev libpulse-mainloop-glib0 libpulse0
libpulse0:i386 libpulsedsp libquadmath0 librtmp1 libsamplerate0:i386
libsasl2-2 libsasl2-2:i386 libsasl2-modules libsasl2-modules:i386
libsasl2-modules-db libsasl2-modules-db:i386 libschroedinger-1.0-0:i386
libseccomp2 libselinux1 libselinux1:i386 libshine3:i386 libsm6:i386
libsmartcols1 libsnappy1v5 libsnappy1v5:i386 libsndfile1 libsndfile1:i386
libsoundtouch1 libsoup2.4-1 libsoxr0 libspeex1:i386 libspeexdsp1:i386
libssh-gcrypt-4 libssl1.0.2 libssl1.0.2:i386 libstdc++-5-dev libstdc++6:i386
libswresample-ffmpeg1 libswresample-ffmpeg1:i386 libswscale-ffmpeg3
libswscale-ffmpeg3:i386 libsystemd0 libsystemd0:i386 libtasn1-6
libtasn1-6:i386 libtheora0 libtheora0:i386 libtinfo5:i386 libtsan0
libtwolame0 libtwolame0:i386 libtxc-dxtn-s2tc0:i386 libubsan0 libudev1
libudev1:i386 libuuid1 libuuid1:i386 libva-x11-1 libva-x11-1:i386 libva1
libva1:i386 libvdpau-va-gl1 libvdpau-va-gl1:i386 libvdpau1 libvdpau1:i386
libvorbis0a libvorbis0a:i386 libvorbisenc2 libvorbisenc2:i386 libvorbisfile3
libvpx2 libvpx2:i386 libwavpack1 libwavpack1:i386 libwebkitgtk-1.0-0
libwebkitgtk-1.0-common libwebp5 libwebp5:i386 libwine libwine:i386
libwrap0:i386 libx11-6 libx11-6:i386 libx11-dev libx11-xcb-dev libx11-xcb1
libx11-xcb1:i386 libx264-148 libx264-148:i386 libx265-68 libx265-68:i386
libxau6:i386 libxcb-dri2-0:i386 libxcb-dri3-0:i386 libxcb-glx0:i386
libxcb-present0:i386 libxcb-randr0:i386 libxcb-render0:i386
libxcb-shape0:i386 libxcb-sync1:i386 libxcb-xfixes0:i386 libxcb1:i386
libxcursor1:i386 libxdamage1:i386 libxdmcp-dev libxdmcp6 libxdmcp6:i386
libxext6:i386 libxfixes3:i386 libxi-dev libxi6 libxi6:i386 libxml2
libxml2:i386 libxml2-dev libxrandr-dev libxrandr2 libxrender-dev libxrender1
libxrender1:i386 libxshmfence-dev libxshmfence1 libxshmfence1:i386
libxtst6:i386 libxvidcore4 libxvidcore4:i386 libxxf86vm-dev libxxf86vm1
libxxf86vm1:i386 libzvbi-common libzvbi0 libzvbi0:i386 mesa-common-dev
mesa-vdpau-drivers mesa-vdpau-drivers:i386 mount ocl-icd-libopencl1
ocl-icd-libopencl1:i386 p11-kit-modules pulseaudio pulseaudio-module-x11
pulseaudio-utils systemd systemd-sysv sysvinit-utils totem-common udev
util-linux va-driver-all va-driver-all:i386 vdpau-driver-all
vdpau-driver-all:i386 vdpau-va-driver vdpau-va-driver:i386 wget wine
zlib1g:i386
Suggested packages:
libsasl2-modules-gssapi-mit libsasl2-modules-gssapi-heimdal lrzip alsa-utils
glibc-doc glibc-doc:i386 firmware-crystalhd firmware-crystalhd:i386
rng-tools rng-tools:i386 gmp-doc libgmp10-doc libmpfr-dev gnutls-bin
gnutls-bin:i386 gpm:i386 gstreamer1.0-tools icu-doc jackd2 jackd2:i386
liblcms2-utils:i386 libportaudio2:i386 opus-tools opus-tools:i386
libsasl2-modules-otp libsasl2-modules-ldap libsasl2-modules-sql
libsasl2-modules-otp:i386 libsasl2-modules-ldap:i386
libsasl2-modules-sql:i386 libsasl2-modules-gssapi-mit:i386
libsasl2-modules-gssapi-heimdal:i386 speex:i386 libstdc++-5-doc
ttf-mscorefonts-installer ttf-mscorefonts-installer:i386 libx265-68-dbg
libx265-68-dbg:i386 opencl-icd opencl-icd:i386 pavumeter pavucontrol paman
paprefs systemd-ui systemd-container bootlogd sash util-linux-locales
xvba-va-driver xvba-va-driver:i386 nvidia-vdpau-driver
nvidia-legacy-340xx-vdpau-driver nvidia-vdpau-driver:i386
nvidia-legacy-340xx-vdpau-driver:i386 wine-binfmt dosbox
wine32-preloader:i386

Recommended packages:
fonts-wine:i386 xml-core:i386 libwine-gecko-2.40:i386

The following packages will be REMOVED:
caribou caribou-antler empathy gnome-contacts gnome-control-center
gnome-core gnome-orca gstreamer1.0-plugins-bad kali-desktop-gnome
libatk1.0-dev libcairo2-dev libcheese-gtk23 libcheese7 libfarstream-0.2-2
libgail-common libgail18 libgdk-pixbuf2.0-dev libglib2.0-dev libgtk2.0-dev
libhogweed2 libnettle4 libpango1.0-dev libpcre3-dev libsoup2.4-dev
libtelepathy-farstream3 libwebkit-dev libwebkitgtk-dev python-pyatspi
python3-pyatspi totem totem-plugins vega

please help me

**Comment by shrkboy** [comment]
i'm also runing kali linux 2.0 x64.yes offcourse, i can't open setting after it removed it. my desktop setting, network setting, all of ti. is there any way to fix it?

**Comment by ChrisTruncer** [comment]
I’ll test running this on a clean Kali install now and let you know. 

You could just try to reinstall the packages that were uninstalled.


On December 9, 2015 at 4:14:31 PM, shrkboy (notifications@github.com) wrote:

i'm also runing kali linux 2.0 x64.yes offcourse, i can't open setting after it removed it. my desktop setting, network setting, all of ti. is there any way to fix it?

**Comment by ChrisTruncer** [comment]
That looks to be isolated to your system unfortunately.  I just ran the install on a clean kali image, and it didn't uninstall anything.  It only installed new packages that it needs.

**Comment by shrkboy** [comment]
problem solved. i tried to install it too on clean kali install and it didn't remove anything. it just my previous kali that corrupted. thanks alot for helping me to solve it!
