### ISSUE TITLE
Go payload byte array too small

### ISSUE THREAD

**Issue by tomsteele** [Veil-Framework/Veil-Evasion#243]
https://github.com/Veil-Framework/Veil-Evasion/blob/dbe0e7002a7d7d9ad7a8f46e3784d6e7708a04c8/modules/payloads/go/meterpreter/rev_http.py#L99

Example above. Didn't want to submit a PR for just the Go payloads as this might be  larger issue. Newest Meterpreter stage is 958531 bytes.

**Comment by ChrisTruncer** [comment]
yup, valid bug.  Checking this out now.  Thanks for the report!

**Comment by ChrisTruncer** [comment]
Got this fix merged in.  Looks like right now it happened to only be the go payloads.  Thanks for letting me know!
