### ISSUE TITLE
Error when loading script with Cobalt Strike

### ISSUE THREAD

**Issue by adde88** [Veil-Framework/Veil-Evasion#245]
Could not load /usr/share/veil-evasion/tools/cortana/veil_evasion.cna
Error: Class SafeMouseListener was not found at line 722
	SafeMouseListener

System: Kali Linux 2.0 (Sana)

**Comment by ChrisTruncer** [comment]
Yup, Cobalt Strike has changed, so the cna script probably doesn't work currently.  Want to take a shot at updating it for me? :)

**Comment by adde88** [comment]
Sure, i'll take a look at the issue, and see what i can figure out. :)
Thanks for responding. :+1:
