### ISSUE TITLE
UBUNTU [ERROR] Failed To Install Wine x86_64... Exit Code: 100.

### ISSUE THREAD

**Issue by alexej-okelloj** [Veil-Framework/Veil-Evasion#246]
Second day trying to find a solution.
Ubuntu 14.04
$ uname -r 
3.16.0-57-generic
$ bash setup/setup.sh -s
. . .
 [*] Installing (Wine) i386 Binaries
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package wine32:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'wine32:i386' has no installation candidate
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package wine-bin:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libwine:i386 libwine

E: Package 'wine-bin:i386' has no installation candidate
 [ERROR] Failed To Install Wine x86_64... Exit Code: 100.

**Comment by ChrisTruncer** [comment]
I normally answer issues, but please just use the search functionality here.  This issue has been answered multiple times before.

**Comment by alexej-okelloj** [comment]
I appreciate if you could find me that. I could not find anything. At least nothing worked.
