### ISSUE TITLE
UBUNTU [ERROR] Failed To Install Wine x86_64... Exit Code: 100 NOT SOLVED

### ISSUE THREAD

**Issue by alexej-okelloj** [Veil-Framework/Veil-Evasion#247]
I have to open very same issue which was opened yesterday since I failed to find any solution in here nor somewhere else. Running dpkg --add-architecture i386 as well as other workarounds failed. Even adding deb http://ftp.de.debian.org/debian jessie main to sources.list results in security warnings and in the end it still does not work. For example: 
The following NEW packages will be installed
  wine32:i386
0 to upgrade, 1 to newly install, 0 to remove and 2208 not to upgrade.
2 not fully installed or removed.
Need to get 0 B/69.7 kB of archives.
After this operation, 84.0 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  wine32:i386
E: There are problems and -y was used without --force-yes
Reading package lists... Done
Building dependency tree       
Reading state information... Done
wine-bin:i386 is already the newest version.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies.
 wine-bin:i386 : Depends: wine32:i386 (>= 1.6.2-20) but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
 [ERROR] Failed To Install Wine x86_64... Exit Code: 100.

**Comment by ChrisTruncer** [comment]
https://github.com/Veil-Framework/Veil-Evasion/issues/231
