### ISSUE TITLE
Couldn't Detect OS Information

### ISSUE THREAD

**Issue by FAROUKix** [Veil-Framework/Veil-Evasion#249]
┌┼─┼─ root @ anassfarouki ─┤├─ 14:13:16 Wed Jan 06 ─┤├─ ~/Veil-Evasion/setup ─┤
./setup.sh
[ERROR] Internal Issue. Couldn't Detect OS Information...

:'( my kali 2 

help me plz 

32 bit

**Comment by ChrisTruncer** [comment]
I responded in a previous issue.
