### ISSUE TITLE
[Debian 8] Wine-bin packet no longer exists in the repositories

### ISSUE THREAD

**Issue by KALRONG** [Veil-Framework/Veil-Evasion#251]
Hi,

While running setup.sh on a Debian 8 I found that it was complaining regarding not finding the wine-bin:i386 repository.

After some investigation looks like this package is no longer avaliable on this version so instead I changed it to wine:i386.

**Comment by ChrisTruncer** [comment]
it works with that?  When was the change made to the package name?

**Comment by KALRONG** [comment]
With the wine package I was able to continue with the installation, Im currently stuck on the Go installation but so far everything related to wine worked.

Regarding the change of the name, the thing is that the package doesn't exist in the repos for debian stretch but in Jessie is still present.

**Comment by ChrisTruncer** [comment]
Well, I'm likely going to close this.  We're currently only supporting debian jessie.  If you want to add in some extra OS detection, I'd check out the code and get it added in, but for the moment we only support Jessie because we really only Support Kali linux primarily.

**Comment by ChrisTruncer** [comment]
I'll close this unless I hear a response
