### ISSUE TITLE
[Debian 8] Error in awk while checking golang-src version

### ISSUE THREAD

**Issue by KALRONG** [Veil-Framework/Veil-Evasion#252]
Hi,

The command used to check the version of golang-src outputs the error:

awk:fatal:tenet of \{\}: /[:-.]/

**Comment by ChrisTruncer** [comment]
what does this show?

apt-cache show golang-src

**Comment by KALRONG** [comment]
Package: golang-src
Source: golang
Version: 2:1.5.1-4
Installed-Size: 34292
Maintainer: Go Compiler Team <pkg-golang-devel@lists.alioth.debian.org>
Architecture: amd64
Description-en: Go programming language - source files
 The Go programming language is an open source project to make programmers more
 productive. Go is expressive, concise, clean, and efficient. Its concurrency
 mechanisms make it easy to write programs that get the most out of multicore
 and networked machines, while its novel type system enables flexible and
 modular program construction. Go compiles quickly to machine code yet has the
 convenience of garbage collection and the power of run-time reflection. It's a
 fast, statically typed, compiled language that feels like a dynamically typed,
 interpreted language.
 .
 This package provides the Go programming language source files needed for
 cross-compilation.
Description-md5: 541938e00b2a0c85f1fbae617a75fcd4
Homepage: https://golang.org
Section: devel
Priority: optional
Filename: pool/main/g/golang/golang-src_1.5.1-4_amd64.deb
Size: 6419102
MD5sum: c57a5e0570ed1c22118858f8b70a0e9a
SHA1: 4b2549f2e16dce9fcaffc7d0cf00ad4f2881b465
SHA256: 568e83fb9a1f3f1a43be6d9ed912303cd6afd44cc40ffadf8316a18e9903f923

**Comment by ChrisTruncer** [comment]
hm... Not sure at the moment, any attempt to update the awk parsing?

**Comment by ChrisTruncer** [comment]
I just don't have the time at this moment to check this out

**Comment by ChrisTruncer** [comment]
I'm closing this until I hear a response
