### ISSUE TITLE
Fix Go Install

### ISSUE THREAD

**Issue by ChrisTruncer** [Veil-Framework/Veil-Evasion#261]
Probably a quick fix, but binary isn't found right now when invoking go for compilation.

**Comment by ChrisTruncer** [comment]
So, I fixed the go install, but it came at a minor tradeoff.  Github is complaining when I am uploading the go binaries into the setup folder because the files are too big (approx 75 megs each).  My solution was to remove it from the setup folder, and now host it on the Veil-Framework website.

The main concern might be that people have to trust the code coming from the site.  My first impression would be, you're already running Veil code, so you either trust it, or you don't.  With that said, it's always worth adding some extra security if I can.  What if the veil webserver becomes compromised?  

I think a good solution would be to perform a hash check that's hard coded into the setup script.  This will prove that the same file that is the true go binary installer is actually what is downloaded on your system.  In the event an attacker were to control the server and modify the go download, then the hash check would fail and could alert you the user to not install Veil at this time (and hopefully let me know my server got owned :)).

Anyways, this is what I think I'm going to do, if anyone has feedback, let me know.

**Comment by condor666** [comment]
Can't you split the files with 7zip and automate it's rebuild with it's
command line during the setup ?

(sorry  for my bad english)

Cet e-mail a été envoyé depuis un ordinateur protégé par Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-02-02 21:03 GMT+01:00 ChrisTruncer <notifications@github.com>:

**Comment by ChrisTruncer** [comment]
I want to try to reduce the clutter, so I'd prefer a single file vs many. Also, I could be wrong, but I don't think there'd be a significant enough saving to do that, vs. just download on the fly

**Comment by ChrisTruncer** [comment]
Hash checking has now been added in.  If the sha256 hash matches, then the install will commence.  if it doesn't match, the setup script will exit and ask to have the user run again, or to alert the developer (me)
