### ISSUE TITLE
Bad IP adress or hostname specified

### ISSUE THREAD

**Issue by Abrelaboca** [Veil-Framework/Veil-Evasion#263]
Working with powershell/meterpreter/rev_https I found a problem when trying to set the LHOST, getting bad IP adress or hostname, any ideas?

**Comment by ChrisTruncer** [comment]
You need to actually give me the ip or domain so I can test, I can't do anything right now without that info

**Comment by Abrelaboca** [comment]
Sure, polisq.ddns.net would be the hostname

**Comment by Abrelaboca** [comment]
Wait a second please, my retardness is showing

**Comment by Abrelaboca** [comment]
Okey, it's now running

**Comment by ChrisTruncer** [comment]
Glad it's working for you!
