### ISSUE TITLE
problem with veil help please

### ISSUE THREAD

**Issue by waldek1234** [Veil-Framework/Veil-Evasion#269]
i try in 2 computers, in second reinstall kali , reinstall veil and i have error:

[!] ERROR: Unable to create output file.

[!] Internal error #2. Unable to generate output. Please run /root/Veil-Evasion/config/update.py manually
why? please help

**Comment by ChrisTruncer** [comment]
Please only open one issue, opening multiple issues doesn't help.  Additionally, you didn't give me any information that was requested of you when opening an issue.  Please read the information that I need in order to help troubleshoot.
