### ISSUE TITLE
install veil in debian testing

### ISSUE THREAD

**Issue by dxg74120** [Veil-Framework/Veil-Evasion#272]
## my os is debian testing x64 
~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux stretch/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
~$ cat /etc/issue
Debian GNU/Linux stretch/sid \n \l

bash setup/setup.sh -s
==========================================================================
 Veil-Evasion (Setup Script) | [Updated]: 2016-01-20
==========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
==========================================================================

 [ERROR] Internal Issue. Couldn't Detect OS Information...

Please help me

**Comment by ChrisTruncer** [comment]
So, we typically only support stable, and really the main OS that is supported is Kali Rolling.  Can you try using Kali Rolling?

Do neither of these work for you either?

os="$(awk -F '=' '/^ID=/ {print $2}' /etc/os-release 2>&-)"
version=$(awk -F '=' '/^VERSION_ID=/ {print $2}' /etc/os-release 2>&-)

**Comment by dxg74120** [comment]
os="$(awk -F '=' '/^ID=/ {print $2}' /etc/os-release 2>&-)"
version=$(awk -F '=' '/^VERSION_ID=/ {print $2}' /etc/os-release 2>&-)

os=debian
why version=“ ”

**Comment by gordonrs** [comment]
I'm currently doing additional distro support work at the moment after letting it slip for a few months for other work. I plan to make sure it also works on Debian testing amongst other distros, so hang in there. Hoping to clean up the installer and config updater. Should have pull requests within the next week for it. Debian testing's /etc/os-release VERSION_ID _should_ have a number in it, in this case VERSION_ID=8 or VERSION_ID=Debian 8, so this will need to be flagged up to them as a bug.

For the time being, I'd recommend to stick to Kali until this is sorted out.

**Comment by dxg74120** [comment]
Yes, I'm looking forward to Veil-Evasion later changes. Thank you.

**Comment by ChrisTruncer** [comment]
Ok, I'll close this for the time being then.  @gordonrs is working on this (awesome, and thanks!)
