### ISSUE TITLE
Veil-Evasion Installation Fails

### ISSUE THREAD

**Issue by PhilipWerlau** [Veil-Framework/Veil-Evasion#273]
## Veil-Evasion version
2.23-0kali1

## OS Used - all info (architecture, linux flavor, etc)
Virtualized, Kali 2.0 x86 v2016.1, kali-rolling

## Pastebin link to error you are encountering
 [*] Initializing Package Installation
Hit:1 http://archive-7.kali.org/kali-security sana/updates InRelease
Get:2 http://archive-7.kali.org/kali kali-rolling InRelease [20.3 kB]
Hit:3 http://archive-7.kali.org/kali sana InRelease
Get:4 http://archive-7.kali.org/kali kali-rolling/main i386 Packages [13.3 MB]
Get:5 http://archive-7.kali.org/kali kali-rolling/non-free i386 Packages [134 kB]
Get:6 http://archive-7.kali.org/kali kali-rolling/contrib i386 Packages [87.6 kB]
Fetched 13.6 MB in 14s (914 kB/s)
Reading package lists...

 [*] Installing Dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ca-certificates is already the newest version (20160104).
git is already the newest version (1:2.7.0-1).
golang is already the newest version (2:1.5.3-1).
mingw-w64 is already the newest version (4.0.4-2).
mono-mcs is already the newest version (4.2.1.102+dfsg2-5).
monodevelop is already the newest version (5.10.0.871-2).
monodoc-browser is already the newest version (4.2-1).
python is already the newest version (2.7.11-1).
python-crypto is already the newest version (2.6.1-6).
python-pefile is already the newest version (1.2.10.139-2).
python-pip is already the newest version (1.5.6-7).
ruby is already the newest version (1:2.2.4).
unzip is already the newest version (6.0-20).
wget is already the newest version (1.17.1-1+b1).
wine is already the newest version (1.8.1-1).
ttf-mscorefonts-installer is already the newest version (3.6).
The following packages were automatically installed and are no longer required:
  inguma libbasicusageenvironment0 libgroupsock1 liblivemedia23
  libpython3.4-minimal libpython3.4-stdlib libqt5xcbqpa5 libsodium13
  libusageenvironment1 python-bluez python-dbus-dev python-geoip python3.4
  python3.4-minimal
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
metasploit-framework is already the newest version (4.11.10-0kali1).
The following packages were automatically installed and are no longer required:
  inguma libbasicusageenvironment0 libgroupsock1 liblivemedia23
  libpython3.4-minimal libpython3.4-stdlib libqt5xcbqpa5 libsodium13
  libusageenvironment1 python-bluez python-dbus-dev python-geoip python3.4
  python3.4-minimal
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

 [*] Installing Capstone Dependencies...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-capstone is already the newest version (3.0.4-0.2).
The following packages were automatically installed and are no longer required:
  inguma libbasicusageenvironment0 libgroupsock1 liblivemedia23
  libpython3.4-minimal libpython3.4-stdlib libqt5xcbqpa5 libsodium13
  libusageenvironment1 python-bluez python-dbus-dev python-geoip python3.4
  python3.4-minimal
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

 [*] (Wine) Python Already Installed... Skipping...

 [*] (Wine) Ruby Already Installed... Skipping...

 [*] Initializing Go Dependencies Installation...
 [*] Installing Go (via TAR)
# Building C bootstrap tool.
cmd/dist

# Building compilers and Go bootstrap tool for host, linux/386.
lib9
libbio
liblink
cmd/cc
cmd/gc
cmd/8l
cmd/8a
cmd/8c
cmd/8g
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
unicode/utf16
bytes
math
strings
strconv
bufio
sort
container/heap
encoding/base64
syscall
time
os
reflect
fmt
encoding
encoding/json
flag
path/filepath
path
io/ioutil
log
regexp/syntax
regexp
go/token
go/scanner
go/ast
go/parser
os/exec
os/signal
net/url
text/template/parse
text/template
go/doc
go/build
cmd/go

# Building packages and commands for linux/386.
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
bytes
bufio
math
syscall
time
os
strconv
reflect
fmt
strings
cmd/internal/goobj
encoding/binary
cmd/internal/rsc.io/arm/armasm
cmd/internal/rsc.io/x86/x86asm
debug/dwarf
debug/elf
debug/gosym
debug/macho
debug/pe
debug/plan9obj
sort
regexp/syntax
regexp
text/tabwriter
cmd/internal/objfile
flag
log
cmd/addr2line
hash
crypto
crypto/md5
go/token
path/filepath
go/scanner
go/ast
io/ioutil
go/parser
go/printer
os/exec
cmd/cgo
go/format
path
cmd/fix
container/heap
encoding
encoding/base64
unicode/utf16
encoding/json
encoding/xml
net/url
text/template/parse
text/template
go/doc
go/build
compress/flate
hash/crc32
compress/gzip
container/list
crypto/subtle
crypto/cipher
crypto/aes
crypto/des
math/rand
math/big
crypto/elliptic
encoding/asn1
crypto/ecdsa
crypto/hmac
internal/syscall
crypto/rand
crypto/rc4
crypto/rsa
crypto/sha1
crypto/sha256
crypto/dsa
crypto/sha512
crypto/x509/pkix
encoding/hex
encoding/pem
runtime/cgo
net
crypto/x509
crypto/tls
mime
net/textproto
mime/multipart
net/http/internal
net/http
os/signal
cmd/go
# cmd/go
/var/lib/veil-evasion/go/pkg/linux_386/runtime/cgo.a(_all.o): unknown relocation type 43; compiled without -fpic?
/var/lib/veil-evasion/go/pkg/linux_386/runtime/cgo.a(_all.o): unknown relocation type 43; compiled without -fpic?
runtime/cgo(.text): unexpected relocation type 299
runtime/cgo(.text): unexpected relocation type 299
runtime/pprof
cmd/gofmt
cmd/nm
cmd/objdump
cmd/pack
cmd/pprof/internal/profile
cmd/pprof/internal/plugin
html
html/template
cmd/pprof/internal/report
cmd/pprof/internal/svg
cmd/pprof/internal/tempfile
cmd/pprof/internal/commands
cmd/pprof/internal/driver
cmd/pprof/internal/fetch
cmd/pprof/internal/symbolizer
cmd/pprof/internal/symbolz
cmd/pprof
# cmd/pprof
/var/lib/veil-evasion/go/pkg/linux_386/runtime/cgo.a(_all.o): unknown relocation type 43; compiled without -fpic?
/var/lib/veil-evasion/go/pkg/linux_386/runtime/cgo.a(_all.o): unknown relocation type 43; compiled without -fpic?
runtime/cgo(.text): unexpected relocation type 299
runtime/cgo(.text): unexpected relocation type 299
cmd/yacc
archive/tar
archive/zip
compress/bzip2
compress/lzw
hash/adler32
compress/zlib
container/ring
database/sql/driver
database/sql
encoding/ascii85
encoding/base32
encoding/csv
encoding/gob
expvar
hash/crc64
hash/fnv
image/color
image
image/color/palette
image/draw
image/gif
image/jpeg
image/png
index/suffixarray
log/syslog
math/cmplx
net/http/cgi
net/http/cookiejar
net/http/fcgi
net/http/httptest
net/http/httputil
net/http/pprof
net/mail
net/rpc
net/rpc/jsonrpc
net/smtp
os/user
runtime/debug
runtime/race
testing
testing/iotest
testing/quick
text/scanner
 [ERROR] Failed To Compile Go... Exit Code: 2.

## Any additional info you want to tell me
I've tried on both Kali 2.0 x86 and x64, reinstalled a clean OS 4 separate times, and read through every issue submission I could find. Nothing is working. The weird thing is the first time I installed it on Kali 2.0 x64 it worked, but I wasn't able to get certain aspects of the program working so decided to reinstall, and that's when I started having the issue. Since then I've reinstalled Kali, both x86 and x64, 4 times.

**Comment by ChrisTruncer** [comment]
You're going to need to git clone our repo and install it that way. The Veil-Evasion package within Kali is not up to date. 

On another note, you're going to want to use Kali Rolling vs. Kali 2

**Comment by PhilipWerlau** [comment]
That was it. Thank you.
