### ISSUE TITLE
Installing Veil on Windows

### ISSUE THREAD

**Issue by Ashesh3** [Veil-Framework/Veil-Evasion#274]
Veil Version: 2.24
Os: Windows 10 x64

Error Message:

````
=========================================================================
 Necessary component missing
 Please run: bash C:\Users\Ashesh\Downloads\Compressed\Veil-Evasion-master\Veil-Evasion-master\setup\setup.sh -s
=========================================================================
````

Veil should run.

I have Following components installed:

Python 2.7
Py2Exe
PyCrypto 
PyWin32
Ruby

**Comment by necrose99** [comment]
**I pray This  a virtual Machine,** 
IT would be **EXTREMELY** unwise if it isn't

**Comment by ChrisTruncer** [comment]
Hey, right now we don't support Veil-Evasion on Windows.  Obviously it's running into an issue because it's trying to run the setup script, which is bash.

At some point I may look into this, but it's not on the top of my priority list at the moment.

If you would like to look into it, by all means please do so, and maybe send a pull request my way.

Thanks!

**Comment by modun** [comment]
I try mang times on my windows

**Comment by necrose99** [comment]
you can install bash on windows, however often comes with bash if you uses GIT...  often gitcola non github git's have a mini bash in them... 
[](https://github.com/GoSecure/malboxes)  , cygwin etc.    <u>**I would NOT EVER  Install Veil on Windows for production**... </u>  USE A disposable VM. ie malboxes
**As you will likely Compromise the  UNHOLY UNLIVING hell out of your windows box** ... 

however if you do **malware reverse engineering**  , or **forensics**, and wish to simulate **how far down the rabbit hole goes**... ;  (ie worst case scenarios) 
 to test advanced engines like [Cylance](cylance.com) for Endpoint protection... 
also .. 
https://www.windowscentral.com/how-install-bash-shell-command-line-windows-10 
can use [Ubuntu from the windows store](https://www.microsoft.com/en-us/store/p/ubuntu/9nblggh4msv6)..  Debian/ Kahli isn't far from Debian or Ubuntu. 
apt-get install git
# git clone https://github.com/LionSec/katoolin.git  && cp katoolin/katoolin.py /usr/bin/katoolin
adds Kahli to stock Ubuntu..
