### ISSUE TITLE
issue with compiling

### ISSUE THREAD

**Issue by zoumou** [Veil-Framework/Veil-Evasion#280]
## Veil-Evasion version
latest version downloaded directly from repo

## OS Used - all info (architecture, linux flavor, etc)
Kali-rolling with all the updates and upgrades

## Pastebin link to error you are encountering (include console actions you took prior to error)
root@ZouMou:/usr/share/veil-evasion/setup# ./setup.sh

 [i] Kali Linux "2016.1" x86_64 Detected...

 [?] Are you sure you wish to install Veil-Evasion?

 Continue With Installation? (y/N): y

 [*] Initializing Package Installation
Hit:1 http://old.kali.org/kali moto InRelease
Hit:2 http://ftp.free.fr/pub/kali kali-rolling InRelease
Hit:3 http://ftp.free.fr/pub/kali-security sana/updates InRelease
Hit:4 http://ftp.free.fr/pub/kali sana InRelease
Reading package lists...

 [*] Adding i386 Architecture To x86_64 System
Hit:1 http://old.kali.org/kali moto InRelease
Hit:2 http://ftp.free.fr/pub/kali kali-rolling InRelease
Hit:3 http://ftp.free.fr/pub/kali-security sana/updates InRelease
Hit:4 http://ftp.free.fr/pub/kali sana InRelease
Reading package lists...

 [*] Installing (Wine) i386 Binaries
Reading package lists... Done
Building dependency tree       
Reading state information... Done
wine32:i386 is already the newest version (1.8.1-1).
The following packages were automatically installed and are no longer required:
  libqt5xcbqpa5 libquvi-scripts libquvi7 python-dbus-dev vlc-plugin-notify
  vlc-plugin-samba
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
wine-bin:i386 is already the newest version (1.6.2-20).
The following packages were automatically installed and are no longer required:
  libqt5xcbqpa5 libquvi-scripts libquvi7 python-dbus-dev vlc-plugin-notify
  vlc-plugin-samba
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.

 [*] Installing Dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ca-certificates is already the newest version (20160104).
git is already the newest version (1:2.7.0-1).
golang is already the newest version (2:1.5.3-1).
mingw-w64 is already the newest version (4.0.4-2).
mono-mcs is already the newest version (4.2.1.102+dfsg2-6).
monodevelop is already the newest version (5.10.0.871-2).
monodoc-browser is already the newest version (4.2-1).
python is already the newest version (2.7.11-1).
python-crypto is already the newest version (2.6.1-6).
python-pefile is already the newest version (1.2.10.139-2).
python-pip is already the newest version (1.5.6-7).
ruby is already the newest version (1:2.2.4).
unzip is already the newest version (6.0-20).
wget is already the newest version (1.17.1-1+b1).
wine is already the newest version (1.8.1-1).
ttf-mscorefonts-installer is already the newest version (3.6).
The following packages were automatically installed and are no longer required:
  libqt5xcbqpa5 libquvi-scripts libquvi7 python-dbus-dev vlc-plugin-notify
  vlc-plugin-samba
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
metasploit-framework is already the newest version (4.11.12-0kali1).
The following packages were automatically installed and are no longer required:
  libqt5xcbqpa5 libquvi-scripts libquvi7 python-dbus-dev vlc-plugin-notify
  vlc-plugin-samba
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.

 [*] Installing Capstone Dependencies...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-capstone is already the newest version (3.0.4-0.2).
The following packages were automatically installed and are no longer required:
  libqt5xcbqpa5 libquvi-scripts libquvi7 python-dbus-dev vlc-plugin-notify
  vlc-plugin-samba
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.

 [*] (Wine) Python Already Installed... Skipping...

 [*] (Wine) Ruby Already Installed... Skipping...

 [*] Initializing Go Dependencies Installation...
 [*] Installing Go (via TAR)
# Building C bootstrap tool.
cmd/dist

# Building compilers and Go bootstrap tool for host, linux/amd64.
lib9
libbio
liblink
cmd/cc
cmd/gc
cmd/6l
cmd/6a
cmd/6c
cmd/6g
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
unicode/utf16
bytes
math
strings
strconv
bufio
sort
container/heap
encoding/base64
syscall
time
os
reflect
fmt
encoding
encoding/json
flag
path/filepath
path
io/ioutil
log
regexp/syntax
regexp
go/token
go/scanner
go/ast
go/parser
os/exec
os/signal
net/url
text/template/parse
text/template
go/doc
go/build
cmd/go

# Building packages and commands for linux/amd64.
runtime
errors
sync/atomic
unicode
unicode/utf8
math
sync
sort
io
syscall
hash
container/heap
encoding
unicode/utf16
hash/crc32
container/list
crypto/subtle
bytes
strings
bufio
text/tabwriter
time
path
crypto/cipher
crypto/hmac
internal/syscall
html
compress/bzip2
strconv
math/rand
hash/adler32
container/ring
hash/crc64
hash/fnv
image/color
os
reflect
regexp/syntax
crypto
crypto/md5
encoding/base64
net/url
path/filepath
crypto/aes
io/ioutil
os/exec
regexp
crypto/rc4
crypto/sha1
crypto/sha256
fmt
encoding/binary
crypto/sha512
encoding/pem
crypto/des
os/signal
cmd/pprof/internal/svg
encoding/ascii85
encoding/base32
image
image/color/palette
index/suffixarray
cmd/internal/goobj
cmd/internal/rsc.io/arm/armasm
cmd/internal/rsc.io/x86/x86asm
debug/dwarf
debug/gosym
debug/plan9obj
flag
debug/elf
debug/macho
debug/pe
log
go/token
encoding/json
encoding/xml
go/scanner
cmd/internal/objfile
go/ast
text/template/parse
cmd/addr2line
compress/flate
go/parser
go/printer
text/template
compress/gzip
math/big
cmd/cgo
go/format
go/doc
cmd/fix
crypto/elliptic
go/build
encoding/asn1
crypto/rand
crypto/ecdsa
crypto/rsa
crypto/dsa
crypto/x509/pkix
encoding/hex
mime
net/http/internal
runtime/pprof
cmd/nm
cmd/objdump
cmd/gofmt
runtime/cgo
cmd/pack
cmd/pprof/internal/profile
html/template
cmd/pprof/internal/tempfile
net
cmd/yacc
cmd/pprof/internal/plugin
cmd/pprof/internal/symbolizer
cmd/pprof/internal/report
cmd/pprof/internal/symbolz
archive/tar
archive/zip
cmd/pprof/internal/commands
compress/lzw
compress/zlib
cmd/pprof/internal/driver
database/sql/driver
database/sql
encoding/csv
encoding/gob
image/draw
image/jpeg
image/gif
image/png
math/cmplx
os/user
runtime/debug
runtime/race
testing
testing/iotest
testing/quick
text/scanner
crypto/x509
net/textproto
log/syslog
mime/multipart
net/mail
crypto/tls
net/http
net/smtp
cmd/go
cmd/pprof/internal/fetch
expvar
net/http/cgi
cmd/pprof
net/http/cookiejar
net/http/fcgi
net/http/httptest
net/http/httputil
net/http/pprof
net/rpc
net/rpc/jsonrpc
# cmd/pprof
/var/lib/veil-evasion/go/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
/var/lib/veil-evasion/go/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
runtime/cgo(.text): unexpected relocation type 298
runtime/cgo(.text): unexpected relocation type 298
# cmd/go
/var/lib/veil-evasion/go/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
/var/lib/veil-evasion/go/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
runtime/cgo(.text): unexpected relocation type 298
runtime/cgo(.text): unexpected relocation type 298
 [ERROR] Failed To Compile Go... Exit Code: 2.

## Any additional info you want to tell me
the install didn't work at first time, i had to backup of my data and reinstall kali, just retried same problem, i started by editing repos and adding : 

deb http://http.kali.org/kali sana main non-free contrib
deb http://security.kali.org/kali-security sana/updates main contrib non-free

than i added 

deb-src http://http.kali.org/kali sana main non-free contrib
deb-src http://security.kali.org/kali-security sana/updates main contrib non-free
deb http://old.kali.org/kali moto main non-free contrib
deb-src http://old.kali.org/kali moto main non-free contrib

and the problem persist, i tried multiple search words, but it seems nobody have had this kind of problem.

thank you for your help :+1: .

**Comment by zoumou** [comment]
Well i guess i spent the night and i ended up finding why, so for everyone having te same problem, dont use apt-get, clone git, it works like a charm, the problem i guess is that the kali repo is not up to date, it's an old version of veil there i guess. thank you anyway

**Comment by ChrisTruncer** [comment]
Can you try with just using the default repos in Kali rolling?

The only change you need to make is to I comment out the source repos.  Everything else stays the same, don't add any repos

**Comment by zoumou** [comment]
hi,
the problem is solved once i got veil from git the install completed smoothly.
as i explained, i firstly did tried with repos without sources, it didnt work than i added sources repo and tried again, it didnt work, and lastely i added kali 1.0 repo and source, i tought may be veil is running on some old data, and it didnt work too.

when searching i found that the problem came from gol, wich i surely have had on kali it didn't try to update it or downgrade it, but when using the git copy, veil reinstaled gol without prompt.

if you need more infos i ll be happy to reproduce the error if that can help.

thank you
