### ISSUE TITLE
i can't open Veil-Evasion after the installation

### ISSUE THREAD

**Issue by hamzatri** [Veil-Framework/Veil-Evasion#281]
## Veil-Evasion version
the latest version from your site

## OS Used - all info (architecture, linux flavor, etc)
Kali linux version 3

When the installation complete i can not open the Veil-Evasion, i get this message :  Necessary component missing
 Please run: bash /root/Veil-Evasion/setup/setup.sh -s
You can see the picture
http://prntscr.com/aah98c

i repeat the instalation but with no result 
there are the steps i follow :
$ git clone https://github.com/Veil-Framework/Veil-Evasion.git
$ cd Veil-Evasion/setup/
$ ./setup.sh

also i re-install the "sudo pip install symmetricjsonrpc" but no result also

**Comment by ChrisTruncer** [comment]
Did you run the setup script?

**Comment by hamzatri** [comment]
i just run the instalation by this file ./setup.sh
how i can run setup by script ?

**Comment by feralfenrir** [comment]
You would need to run ./Install.sh -c if I'm not wrong.

**Comment by gordonrs** [comment]
Delete you .wine profile first, "rm -rf /root/.wine/" and also delete /etc/veil/settings.py

After that, set your console to unlimited scrollback and try and rerun the installer "./setup.sh -c" for a clean install of all dependencies. If anything fails to install, let us know with a screenshot.

**Comment by hamzatri** [comment]
Thank you all for replay and help, but i still have the same error message
ther is the screenshot, http://prntscr.com/aaoncn
plz help me cos i really need this program to be runed

**Comment by veil-evasion** [comment]
.Are you using Kali rolling?

Do you have a file at /etc/veil/settings.py

?

**Comment by hamzatri** [comment]
Hello brothers
You can see at the picture the kali version and /etc/veil content
http://prntscr.com/aapmiw

**Comment by veil-evasion** [comment]
You're not using Kali rolling.

Please try using the latest version of Kali.  Might be easiest to download their new iso

**Comment by hamzatri** [comment]
you think brother "veil-evasion" that this kali rolling solve the problem ??

**Comment by hamzatri** [comment]
Thank you all my friends ... now it works
thaaaaaaaaaaaaank you very much
i installed kali rolling and it works now ;)

**Comment by 1998ww** [comment]
I installed Kali rolling too
but it does not work
I don't know what should I do
please help me!!!!
