### ISSUE TITLE
error compiling payload 

### ISSUE THREAD

**Issue by amainyebriggs** [Veil-Framework/Veil-Evasion#283]
veil-evasion does not compile python modules on latest version on kali linux 2.0 rolling edition

![Uploading Screenshot from 2016-03-05 16-28-36.png…]()
![Uploading Screenshot from 2016-03-05 16-28-36.png…]()

**Comment by amainyebriggs** [comment]
![screenshot from 2016-03-05 16-28-36](https://cloud.githubusercontent.com/assets/13424678/13548411/1d6f18c8-e2f0-11e5-9570-9494b189eaf0.png)

**Comment by ChrisTruncer** [comment]
Please use Kali rolling. That is the latest version of Kali, and is what we now support

**Comment by amainyebriggs** [comment]
am using kali rolling
![screenshot from 2016-03-05 17-16-13](https://cloud.githubusercontent.com/assets/13424678/13548691/3b760ccc-e2f6-11e5-9e6e-8bd32bc358c0.png)

**Comment by amainyebriggs** [comment]
am using kali rolling 
![screenshot from 2016-03-05 17-17-50](https://cloud.githubusercontent.com/assets/13424678/13548695/5eddf29c-e2f6-11e5-8c1f-060e246cc7ef.png)

**Comment by volt72** [comment]
Hello, i have also had this problem but due to my impatience i reinstalled Kali rolling and then once it finished installing i immediately installed Veil to test it out, to my surprise everything is functioning properly so maybe you might want to give that a try.

**Comment by amainyebriggs** [comment]
am using kali rolling updated from 2.0 sana 
i did apt-get update
apt-get dist-upgrade
and i landed at rolling edition

**Comment by volt72** [comment]
I understand what you are saying but then again at the same time i am trying to tell you that it would probably be a good idea to download a fresh version of Kali rolling from their website, start with a fresh install then from there install Veil, From what i have see this method should work for you as a last resort.

**Comment by hatlord** [comment]
If you run the script like it tells you at the bottom of that output, you will get it working, kind of. Where I am now is that Veil appears to work fine after all this, but the Python payloads get an error - I raised a separate issue for them. In short, try and run the command it gives you at the bottom and see where it gets you.

**Comment by ChrisTruncer** [comment]
Can you try a clean kali to test it out on?  I am not certain how well manual upgrades go with the requirements and potential files left over.

If you use a clean kali rolling VM, it should work without a problem.

**Comment by amainyebriggs** [comment]
okay i will try that

**Comment by amainyebriggs** [comment]
i have figured out the issues

**Comment by amainyebriggs** [comment]
1.download a new pyinstaller from https://github.com/pyinstaller/pyinstaller/releases/download/v3.1.1/PyInstaller-3.1.1.tar.gz

2. rm -r /usr/share/pyinstaller
3. extract pyinstaller to /usr/share
4. rename PyInstaller-3.1.1 in usr/share to  pyinstaller
5.cd /usr/share/pyinstaller
6. python setup.py install 
7.cd /usr/share/veil-evasion/config
8.python update.py

that will fix it

**Comment by ChrisTruncer** [comment]
thanks!
