### ISSUE TITLE
Ubuntu 15.10 Strange Behaivours

### ISSUE THREAD

**Issue by arshadmustafa** [Veil-Framework/Veil-Evasion#286]
## Veil-Evasion version
2.24

## OS Used - all info (architecture, linux flavor, etc)
Ubuntu 15.10 64 bit 

## Pastebin link to error you are encountering (include console actions you took prior to error)
Got many errors on using auxiliary/pyinstaller_wrapper, all already solved by editing files by googling.

## Expected behavior
1) Line 122 of modules/common/supportfiles.py should have been:
os.system("cp "+runwPath+" " + settings.PYINSTALLER_PATH + "/usr/share/pyinstaller/PyInstaller/bootloader/Windows-32bit/")

instead of:

os.system("cp "+runwPath+" " + settings.PYINSTALLER_PATH + "support/loader/Windows-32bit/runw.exe")

a directory is expected there instead of runw.exe and that too wrong location

2) Initial installation with setup script didn’t work on my 64 bit system because of wine problems.
Installed wine1.8, changed WINEARCH to win32 before running setup script. There is nothing called wine32 in ubuntu-repos.

So line 118 of setup/setup.sh changed to 
apt-get -y install wine1.8 instead of apt-get -y install wine32

3) python-setuptools should be installed inside Wine C: Python directory else something called import error pkg_resources is showing

4) Also had to manually download and install libgnutls26_2.12.23-12ubuntu2.5_i386.deb, libgcrypt11_1.5.3-2ubuntu4.3_i386 to avoid some TSL SSL support errors or something like that.

## Any additional info you want to tell me
i created this github account just to inform this. Dont know any programming language thoroughly or github usage. So forgive for this weird kind of reporting.

**Comment by gordonrs** [comment]
Thanks for the report, but this is known and Ubuntu 15.10 support has already been added in. It should be available in git master by the end of the month if there is no glaring issues during testing.

Only thing I didn't previously know about was a problem with libgnutls and libgcrypt, thanks for that. I'll make sure to investigate that further.

**Comment by arshadmustafa** [comment]
Got an early error screenshot, forgot to attach, just for reference.
http://picpaste.com/Screenshot_from_2016-03-08_21-33-46-Zt8jWAQw.png
