### ISSUE TITLE
Kali rolling veil evasion fails at installing go dependencies

### ISSUE THREAD

**Issue by clementtinashe** [Veil-Framework/Veil-Evasion#287]
hi i have been trying to install Veil Evasion on the kali rolling edition. i have been getting the same error after running the ./setup.sh command after downloading the page from git.
if you can assist i would greatly appreciate, below is my very long install process : 

Edited by @ChrisTruncer
Please do not post a giant script here.  There is a template for a reason

**Comment by lambr3a** [comment]
you have to go to etc/apt/sources.list and paste repositories # Regular repositories
deb http://http.kali.org/kali sana main non-free contrib
deb http://security.kali.org/kali-security sana/updates main contrib non-free
# Source repositories
deb-src http://http.kali.org/kali sana main non-free contrib
deb-src http://security.kali.org/kali-security sana/updates main contrib non-free 

apt-get update 
and try again

**Comment by gordonrs** [comment]
This should be fixed as soon as #292 is merged.

**Comment by ChrisTruncer** [comment]
Merged in.
