### ISSUE TITLE
Veil-evasion 

### ISSUE THREAD

**Issue by hxrofo** [Veil-Framework/Veil-Evasion#288]
## uname -m : armv7l

hello guys
I installed kali rolling on my samsung grand prime using the latest version of linux deploy. everything went smooth and easy. after i logged in using vnc viewer, i tried to install veil-evasion from command line: apt-get install veil-evasion ... it says "Unable to locate package veil-evasion"
## My sources.list:
deb http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://http.kali.org/kali kali-rolling main contrib non-free

apt-get update, apt-get upgrade and apt-get dist-upgrade didn't change anything...so i git cloned veil-evasion from github and followed the steps: 
cd Veil-Evasion/setup/
./setup.sh -s
all the packages are downloaded...no errors
The problem happens towards the end of the installation, exactly when installing python and ruby dependencies, when an error window pops up with this message "The program winemenubuilder.exe has encountered a serious problem and needs to close." 
The other error i get:
[*] Installing (Wine) Ruby and dependencies
[*] Next -> Next -> Next -> Finished!...Overwrite if prompt. Use default values.
wine: Bad EXE format for Z:\root\Veil-Evasion\setup\rubyinstaller-1.8.7-p371.exe
[ERROR] Failed to Install (Wine) Ruby.exe...Exit code: 193.

P.S: I added i386 architecture, but when i try to install veil-evasion from kali repos, it gives me dependencies errors
I installed kali-linux-all metapackage because it includes veil-evasion and veil-catapult, but after the installation, i didn't find them.

Any help would be appreciated. thanks

**Comment by feralfenrir** [comment]
Hi,

Try cloning from git and then running setup.sh ?

I'm unsure though if all the dependencies will be met...

**Comment by gordonrs** [comment]
> P.S: I added i386 architecture, but when i try to install veil-evasion from kali repos, it gives me dependencies errors
Uhhh... what? Doesn't work that way.

Veil only supports x86 and x86_64. You can't run x86 binaries on an ARM architecture. Just use a normal machine.

**Comment by hxrofo** [comment]
@feralfenrir  i've already mentioned that i git cloned https://github.com/Veil-Framework/Veil-Evasion.git, and that it gave me these errors about wine at the end of the installation:
wine: Bad EXE format for
 Z:\root\Veil-Evasion\setup\rubyinstaller-1.8.7-p371.exe
 [ERROR] Failed to Install (Wine) Ruby.exe...Exit code: 193.

@gordonrs this post ( http://zitstif.no-ip.org/?p=882 ) says that it's possible to install veil-evasion in an ARM Kali chroot environment, but only using git...

**Comment by ChrisTruncer** [comment]
@hxrofo - I'm not sure why you're getting setup errors, but I've installed it recently (I am currently testing @gordonrs cleaner setup process) and I was able to install everything.  Also, I agree with @gordonrs where I believe it to be highly unlikely that Veil-Evasion will work on anything other than x86 and x86_64.  If somehow it does work, it's purely by accident, and I can't really promise good support on that architecture.

**Comment by ChrisTruncer** [comment]
I'm going to close this ticket since we really don't support it.  Now, if you have a question on using it in that environment, I'll leave this open for responses in case someone else knows how to make it work, but I can't really promise that it would.

**Comment by ChrisTruncer** [comment]
Also, that blog post is a couple years old, and a lot has changed since that post.

**Comment by hxrofo** [comment]
I guess you're right. it won't work. i've been trying for two weeks now. thanks for explaining

**Comment by ChrisTruncer** [comment]
Sorry for the issues, but it should work without a problem if you run it on a linux VM.

Thanks!
