### ISSUE TITLE
Ruby installation fails even with the latest Kali rolling reporsitories.

### ISSUE THREAD

**Issue by feralfenrir** [Veil-Framework/Veil-Evasion#290]
## Veil-Evasion version
veil-evasion amd64 2.24-0kali1

## OS Used - all info (architecture, linux flavor, etc)
Linux 4.4.0-kali1-amd64 #1 SMP Debian 4.4.6-1kali1 (2016-03-18) x86_64 GNU/Linux

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/J1k25s01

## Expected behavior
Ruby installation should have finished without error

## Any additional info you want to tell me

**Comment by gordonrs** [comment]
Don't use the package from Kali, instead clone from the git repository.

**Comment by feralfenrir** [comment]
Thanks Gordon!

That would have been my next question! Should I use the version bundled
with Kali or should I clone from the git repo.

I will try this and update. Till then this can be closed.

Thanks and Regards,

Kaushal

**Comment by ChrisTruncer** [comment]
Thanks, and thanks to @gordonrs for answering!
