### ISSUE TITLE
Architecture i686 not suppoted

### ISSUE THREAD

**Issue by Felarof23** [Veil-Framework/Veil-Evasion#291]
## Veil-Evasion version
2.24

## OS Used - all info (architecture, linux flavor, etc)
Kali 2016.1 4.4.0-kali1-686-pae 

## Expected behavior
The setup.sh from Veil must be recognized my arch as i686 and proceed to install the dependencies for Veil

## Any additional info you want to tell me
If i modified the file give him the value for $arch manually it works but Go dependence fail and Veil-Evasion crash generating ruby payloads.

**Comment by gordonrs** [comment]
Thanks I'll investigate this. Just to be sure, you're installing from git and not the Kali packages, yes?

**Comment by ChrisTruncer** [comment]
Also, a followup, is this on a clean system, or did you previously have Veil-Evasion installed?

**Comment by Felarof23** [comment]
Hello, i installed on a clean Rolling Kali x86 and it was cloned from Git

Thanks!!

P.D. Their work is amazing!!!!! :D

**Comment by gordonrs** [comment]
Sorry for the inconvenience of this and the wait. Fix has been made, now just waiting for merge.

**Comment by gordonrs** [comment]
Just tested it, ruby payloads now generate as expected. Run a clean install from git and your problems will be fixed.
