### ISSUE TITLE
Failed to Install (Wine) Python 2.7.5... Exit Code:  3

### ISSUE THREAD

**Issue by rikter1** [Veil-Framework/Veil-Evasion#293]
## Veil-Evasion version
2.24

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux Rolling (i386)
4.4.0-kali1-686-pae #1 SMP Debian 4.4.6-1kali1 (2016-03-18) i686 GNU/Linux

## Pastebin link to error you are encountering (include console actions you took prior to error)
No link, but here is the text:

[*] Installing (Wine) Python...
 [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.

Executing wine (wineserver32) 1.8.1 on Debian Kali Linux Rolling (i386).
If something goes wrong, please rerun with "WINEDEBUG=err+all wine"
for more detailed debugging output.
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/root/.config/wine/veil' has been updated.
 [ERROR] Failed To Install (Wine) Python 2.7.5... Exit Code: 3.

## Expected behavior
Successful installation

## Any additional info you want to tell me
Pulled down Kali iso this morning.  Performed apt-get update && apt-get upgrade && apt-get dist-upgrade.
Git clone veil evasion
Ran the setup script
Setup failed with the error above.

Thanks for the help!  Can't wait to give this a try.....
[Full Install Text.txt](https://github.com/Veil-Framework/Veil-Evasion/files/188168/Full.Install.Text.txt)

**Comment by gordonrs** [comment]
Yeah sorry we need to update the documentation for this. Even though you're root, we require the sudo environment variable to have it all set up appropriately.

Install it as "sudo setup/setup.sh -c" for a clean install.

If you're still receiving the same error, let me know and I'll investigate.

**Comment by ChrisTruncer** [comment]
I'll get this added to the Readme

**Comment by ChrisTruncer** [comment]
Updated docs in #294

**Comment by rikter1** [comment]
Excellent!  Thanks, gents.  Using sudo worked like a champ, and the installation is now complete.
