### ISSUE TITLE
 [ERROR] Failed To Install (Wine) Python 2.7.5... Exit Code: 3.

### ISSUE THREAD

**Issue by honeyfairy** [Veil-Framework/Veil-Evasion#295]
## Veil-Evasion version
 Veil-Evasion | [Version]: 2.24

## OS Used - all info (architecture, linux flavor, etc)
Kali 2016 [  4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-5kali4 (2016-01-13) x86_64 GNU/Linux
]

## Pastebin link to error you are encountering (include console actions you took prior to error)

http://pastebin.com/7P8D5jAi
## Any additional info you want to tell me
Veil already installed, I did a git pull of the latest version and did bash setup/setup.py -s and i get the wine errors as shown

**Comment by ChrisTruncer** [comment]
The install/update process has been updated recently, please do sudo ./setup.sh -c

**Comment by v0ld3** [comment]
@ChrisTruncer 
That fixed my problem.(same issue) Thx

**Comment by ChrisTruncer** [comment]
I'll close this out for now as this should fix the problem, but please let us know if you still are running into an issue.

**Comment by honeyfairy** [comment]
Thank you, that sorted the setup issue.
But when doing the update, i get the following error:

```

Traceback (most recent call last):
  File "./update.py", line 208, in <module>
    wineprefix = "/home/" + user + "/.config/wine/veil/"
TypeError: cannot concatenate 'str' and 'NoneType' objects


```

http://pastebin.com/AGYx2qwr

**Comment by veil-evasion** [comment]
Please run the update.py script too.

**Comment by honeyfairy** [comment]
This is the error i get when i run the update.py
`root@2gb:~/Veil-Evasion/config# ./update.py

Traceback (most recent call last):
  File "./update.py", line 208, in <module>
    wineprefix = "/home/" + user + "/.config/wine/veil/"
TypeError: cannot concatenate 'str' and 'NoneType' objects
root@2gb:~/Veil-Evasion/config#`

**Comment by gordonrs** [comment]
Even though you're root, you need to run it as `sudo ./update.py` for the SUDO_USER environment variable

**Comment by honeyfairy** [comment]
That worked, thanks guys

**Comment by DickVicious** [comment]
I am getting the following error when running setup.sh with the silent command line option (-s). I am trying to add Veil as part of an unattended pentest environment install. If I run with -c, it pops up a few GUIs and completes successfully.

```
 [*] Preparing Wine Python Directories...

 [*] Installing (Wine) Python...
 [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.

err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
err:ole:get_local_server_stream Failed: 80004002
err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
err:ole:get_local_server_stream Failed: 80004002
Could not load wine-gecko. HTML rendering will be disabled.
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/root/.config/wine/veil' has been updated.
 [ERROR] Failed To Install (Wine) Python 2.7.5... Exit Code: 3.
```

**Comment by infosecwriter** [comment]
I also get this error when installing from scratch in Kali through either the apt install and the git clone:

 [*] Installing (Wine) Python...
 [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.
err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
err:ole:get_local_server_stream Failed: 80004002
err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
err:ole:get_local_server_stream Failed: 80004002
Could not load wine-gecko. HTML rendering will be disabled.
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/root/.config/wine/veil' has been updated.
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot

 [*] Installing (Wine) Python dependencies...


 [*] Installing (Wine) Python's pywin32-219.win32-py2.7.exe...
warning [pywin32-219.win32-py2.7.exe]:  196895 extra bytes at beginning or within zipfile
  (attempting to process anyway)


 [*] Installing (Wine) Python's pycrypto-2.6.win32-py2.7.exe...
warning [pycrypto-2.6.win32-py2.7.exe]:  196629 extra bytes at beginning or within zipfile
  (attempting to process anyway)
