### ISSUE TITLE
AttributeError: 'module' object has no attribute 'WINEPREFIX'

### ISSUE THREAD

**Issue by bgx4k3p** [Veil-Framework/Veil-Evasion#296]
## Veil-Evasion version
2.24

## OS Used - all info (architecture, linux flavor, etc)
Kali 2016.1 32bi 4.4.0-kali1-686-pae

## Error you are encountering
=========================================================================
 Veil-Evasion | [Version]: 2.24
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

 Payload: ruby/meterpreter/rev_http loaded

 Required Options:

 Name			Current Value	Description
 ----			-------------	-----------
 COMPILE_TO_EXE  	Y       	Compile to an executable
 LHOST           	        	IP of the Metasploit handler
 LPORT           	80      	Port of the Metasploit handler

 Available Commands:

	set         	Set a specific option value
	info        	Show information about the payload
	options     	Show payload's options
	generate    	Generate payload
	back        	Go to the main menu
	exit        	exit Veil-Evasion

 [ruby/meterpreter/rev_http>>]: set LHOST 1.1.1.1
 [i] LHOST => 1.1.1.1
 [ruby/meterpreter/rev_http>>]: generate

=========================================================================
 Veil-Evasion | [Version]: 2.24
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

 [>] Please enter the base name for output files (default is 'payload'): testpayload.exe
Traceback (most recent call last):
  File "./Veil-Evasion.py", line 301, in <module>
    controller.MainMenu(args=args)
  File "/opt/Veil-Evasion/modules/common/controller.py", line 871, in MainMenu
    self.outputFileName = self.PayloadMenu(self.payload, args=args)
  File "/opt/Veil-Evasion/modules/common/controller.py", line 802, in PayloadMenu
    return self.OutputMenu(payload, payloadCode, args=args)
  File "/opt/Veil-Evasion/modules/common/controller.py", line 608, in OutputMenu
    supportfiles.supportingFiles(self.payload, OutputFileName, {})
  File "/opt/Veil-Evasion/modules/common/supportfiles.py", line 197, in supportingFiles
    os.system('WINEPREFIX=' + settings.WINEPREFIX + ' wine ' + settings.WINEPREFIX + '/drive_c/Ruby187/bin/ruby.exe ' + settings.WINEPREFIX + '/drive_c/Ruby187/bin/ocra --windows '+ payloadFile + ' --output ' + settings.PAYLOAD_COMPILED_PATH + exeName + ' ' + settings.WINEPREFIX + '/drive_c/Ruby187/lib/ruby/gems/1.8/gems/win32-api-1.4.8-x86-mingw32/lib/win32/*')
AttributeError: 'module' object has no attribute 'WINEPREFIX'

##  Notes
Removed ~/.config/wine/veil/ and reinstalled Veil Evasion few times. No errors during the install, but unable to generate payloads.

**Comment by ChrisTruncer** [comment]
Please run the update.py script with Sudo, the same way we specify to run it in the reader, and you should be set.

**Comment by DuStyGSY** [comment]
I'm getting the same issue and I have ran the update.py script in both Veil-Evasion and Veil-Catapult

Please help.

=========================================================================
 Veil-Evasion | [Version]: 2.26.1
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================


 [>] Please enter the base name for output files (default is 'payload'): karltest

 [?] How would you like to create your payload executable?

     1 - Pyinstaller (default)
     2 - Pwnstaller (obfuscated Pyinstaller loader)
     3 - Py2Exe

 [>] Please enter the number of your choice: 1
Traceback (most recent call last):
  File "./Veil-Catapult.py", line 1420, in <module>
    mainMenu(args)
  File "./Veil-Catapult.py", line 276, in mainMenu
    exeDeliveryMenu(args)
  File "./Veil-Catapult.py", line 518, in exeDeliveryMenu
    payloadPath = con.MainMenu()
  File "/root/Veil-Evasion/modules/common/controller.py", line 972, in MainMenu
    self.outputFileName = self.PayloadMenu(self.payload, args=args)
  File "/root/Veil-Evasion/modules/common/controller.py", line 802, in PayloadMenu
    return self.OutputMenu(payload, payloadCode, args=args)
  File "/root/Veil-Evasion/modules/common/controller.py", line 608, in OutputMenu
    supportfiles.supportingFiles(self.payload, OutputFileName, {})
  File "/root/Veil-Evasion/modules/common/supportfiles.py", line 127, in supportingFiles
    and not os.path.isfile(settings.WINEPREFIX + 'drive_c/Python27/python.exe')\
AttributeError: 'module' object has no attribute 'WINEPREFIX'

**Comment by gordonrs** [comment]
Can you show us the contents of /etc/veil/settings.py?

**Comment by JimmyTwoShoes** [comment]
Just installed Veil via Github into a fresh Kali 2016.1 VM, First attempt using Veil Evasion and I get the same stack trace as above. "WINEPREFIX" was not present in /etc/veil/settings.py. As per https://github.com/Veil-Framework/Veil/issues/5, running config/update.py fixed the issue by adding WINEPREFIX to settings.py.

**Comment by dorsec** [comment]
When running the update.py script it had actually said I had 0 payloads loaded and I was not able to fix it. So I deleted Veil, pulled it down from git again, did the install, and then I manually added the WINEPREFIX to the /etc/veil/settings.py file and that fixed the issue. Just and FYI for future users experiencing the issue who land here looking for answers.

**Comment by crazyduckyz** [comment]
@dorsec how exactly did you manually install wineprefix to the /etc/veil/settings.py file. I've been scouring the web and can't find any tutorials. Thanks in advance.

**Comment by dorsec** [comment]
Just add this to your /etc/veil/settings.py file:

WINEPREFIX="/root/.config/wine/veil/"

**Comment by crazyduckyz** [comment]
Thanks for the quick response. Should it be the directory of my veil folder?

**Comment by crazyduckyz** [comment]
@dorsec sorry to be annoying but I have another question.  Once I generate the payload it gives me an error message saying "Can't find python.exe in /root/.config/wine/veil/drive_c/Python27/" Then it gives me an error message right below that saying. "Make sure the python.exe binary exists before using PyInstaller.

**Comment by ChrisTruncer** [comment]
@dorsec - Please search for the answer within the github issues, and if it doesn't exist, please create a new issue.  It also sounds like you're missing the necessary dependencies, so please re-run the setup script (sudo ./setup.sh -c)

**Comment by crazyduckyz** [comment]
ok. Sorry to bother you. thanks
