### ISSUE TITLE
Gmail AV Detects Any Virus, No Matter The Encryption

### ISSUE THREAD

**Issue by Sybrid203** [Veil-Framework/Veil-Evasion#297]
## Veil-Evasion version
2.24

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2.0 
## Pastebin link to error you are encountering (include console actions you took prior to error)
Written in description

## Any additional info you want to tell me
A few days ago, I managed to send payloads encrypted by aes, through gmail.
Today, no matter what encryption I use, Google detects it. 
I know there isn't much to do, but I thought it'll be best if I'd report.

**Comment by ChrisTruncer** [comment]
Hi,

This could really be based on a lot of different things, but thanks for the information.
