### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by saintdrug** [Veil-Framework/Veil-Evasion#301]
## Veil-Evasion version
2.26

## OS Used - all info (architecture, linux flavor, etc)
Linux anonymous 4.0.0-kali1-686-pae #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) i686 GNU/Linux

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/CZnzYEWE

## Expected behavior
it should have proceeded with generation of the payload

## Any additional info you want to tell me
i have all veil installed, catapult, framework, evasion, pillage
i tried as you can see:
rm -rf '/root/.config/wine/veil'

and rerun setup 
nothing, i changed payload selections nothing.
i removed veil completely and reistalled with git clone / setup / update / run it again.

Nothing.

Maybe suggest something for me to do that from your experience could assist?

I went debugged the lines, i am using ./msf5 so all updated
when i try update.py gives me another error as u can also see

Any tip i would appreciate as to where to look so i can fix it

**Comment by saintdrug** [comment]
OK, hello all and Chris :), all it took is a quick smoke :) and found the solution very simple.
For Kali users, exactly we dont use sudo.

Open update.py , nano etc..

Go to line 208 where it says the error, and logic, says add # next to line 208 and 209 just before else if.

and save rerun update --> works

By disabling this function you jump to else, and since in kali it wont affect this, it will never pass from sudo so no harm done.

It will then update your veil, and you can now generate the payloads.

GJ Chris, keep it up with your team :)

you can close and keep this as a solution if you want for kali

**Comment by ChrisTruncer** [comment]
Thanks, will do!
