### ISSUE TITLE
wineprefix not correctly set when not using sudo (but user root)

### ISSUE THREAD

**Issue by sbrun** [Veil-Framework/Veil-Evasion#302]
## Veil-Evasion version
2.26

## OS Used 
kali-rolling

## Pastebin link to error you are encountering 
When running update.py in kali-rolling we have this error:
```
Traceback (most recent call last):
  File "./update.py", line 208, in <module>
    wineprefix = "/home/" + user + "/.config/wine/veil/"
 TypeError: cannot concatenate 'str' and 'NoneType' objects
```
We don't use "sudo" in kali because the user is root, so SUDO_USER doesn't exist.

## Patch suggestion
I patched the code in kali:

[fix-wineprefix.txt](https://github.com/Veil-Framework/Veil-Evasion/files/199401/fix-wineprefix.txt)

**Comment by ChrisTruncer** [comment]
just merged this in.  Thanks for providing the patch!
