### ISSUE TITLE
Avast detected the payload

### ISSUE THREAD

**Issue by vay3t** [Veil-Framework/Veil-Evasion#303]
## Veil-Evasion version
2.26

## OS Used - all info (architecture, linux flavor, etc)
Kali-Rolling

## Pastebin link to error you are encountering (include console actions you took prior to error)
OS victim: `Windows 7 sp1`
AV: `Avast free 2016`
Payload: `python/meterpreter/rev_https`
Avast message: `Infection: Win32:Malware-gen`
I downloaded the payload from Firefox and was detected for Avast and has blocked the download

## Any additional info you want to tell me
```
 [*] Checking Virus Total for payload hashes...
 [*] No payloads found on VirusTotal!
```

**Comment by ChrisTruncer** [comment]
thanks for the report
