### ISSUE TITLE
generate file error

### ISSUE THREAD

**Issue by bofhx** [Veil-Framework/Veil-Evasion#308]
## Veil-Evasion version
 Veil-Evasion | [Version]: 2.26
## OS Used - all info (architecture, linux flavor, etc)
Kail Linux 2016.1.vm-amd64 VMware

## Pastebin link to error you are encountering (include console actions you took prior to error)

[native/backdoor_factory>>]: generate
Traceback (most recent call last):
  File "./Veil-Evasion.py", line 342, in <module>
    controller.MainMenu(args=args)
  File "/usr/share/veil-evasion/modules/common/controller.py", line 972, in MainMenu
    self.outputFileName = self.PayloadMenu(self.payload, args=args)
  File "/usr/share/veil-evasion/modules/common/controller.py", line 797, in PayloadMenu
    payloadCode = payload.generate()
  File "/usr/share/veil-evasion//modules/payloads/native/backdoor_factory.py", line 66, in generate
    if not os.path.isfile(self.required_options["ORIGINAL_EXE"][0]):

## Any additional info you want to tell me

Please how i can fix error.
I reinstall 2 time Veil and not change. 
Tnx,

![image 2016-04-05 at 22 37 59](https://cloud.githubusercontent.com/assets/18294719/14297470/1fb3cdde-fb7f-11e5-81b0-4c48332b7959.jpg)

**Comment by ChrisTruncer** [comment]
This should now be fixed.  Please do a git pull

**Comment by ChrisTruncer** [comment]
Thanks for reporting this issue!

**Comment by bofhx** [comment]
Hi, 
i have another error.
I make you update.
![image 2016-04-06 at 10 33 58](https://cloud.githubusercontent.com/assets/18294719/14310616/254f0c54-fbe3-11e5-9ce1-eeab17103b6e.jpg)

**Comment by ChrisTruncer** [comment]
I'm not certain if this is something you entered incorrectly, or something we need to look at.  @secretsquirrel might be able to give a little context into this.
