### ISSUE TITLE
Delet evasion spy from victim's computer

### ISSUE THREAD

**Issue by hamzatri** [Veil-Framework/Veil-Evasion#309]
Hello

## Veil-Evasion version
last update

## OS Used - all info (architecture, linux flavor, etc)
Kali for attaking and the victim's computer is XP/win7/WinServer

how i can delete evasion trojan from victim's computer, for exemple some entreprise demand to test an external attack, and after the test i must delet the evasion trojan from all infected PC's, how i can do it and thanks very much for help

**Comment by hamzatri** [comment]
Mr ChrisTruncer you closed the topic without help :(

**Comment by void-in** [comment]
Just delete the Veil generated payload file from the location on the victim's hard drive it is executing and you are good to go.

**Comment by hamzatri** [comment]
Thank very much for replay brother void-in
But where i can find "Veil generated payload file" in computer victim's plz ??

**Comment by void-in** [comment]
That would depend upon how you initially gained access to the machine. An easy way is if you have got meterpreter connection, run the ps command look in the Path column. It will show you from where the executable is running. If there is no other copy that the user has made of the Veil generated payload (the payloads doesn't copy itself to multiply locations automatically), deleting from the location shown in the Path column should delete the payload from the victim's computer.
