### ISSUE TITLE
NameError: global name 'os' is not defined

### ISSUE THREAD

**Issue by amrachraf** [Veil-Framework/Veil-Evasion#310]
## Veil-Evasion version
2.26.1

## OS Used - all info (architecture, linux flavor, etc)
kali rolling 

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/4mnrG88P

## Expected behavior
generate the payload

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
I don't think you have the latest version of Veil-Evasion.  This was a bug in a past version, but has been fixed.  Please git pull

**Comment by amrachraf** [comment]
yes!! thanks all done
