### ISSUE TITLE
error while generating payload

### ISSUE THREAD

**Issue by amrachraf** [Veil-Framework/Veil-Evasion#311]
## Veil-Evasion version
2.26.1

## OS Used - all info (architecture, linux flavor, etc)
kali rolling

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/iwP2nkfc

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Sorry, I wish I could, but I can't seem to replicate this.  When I use the exact same input parameters as you, it just continues to run as expected and doesn't error out.

**Comment by amrachraf** [comment]
it wasnt the last version thanks
