### ISSUE TITLE
Macro Word Doc

### ISSUE THREAD

**Issue by vendforce** [Veil-Framework/Veil-Evasion#315]
# Veil-Evasion version : 2.26.1
## Office version : 2010

Im having trouble using veil with a word doc and macro , veil works everytime in an excel doc but word doc, the powershell will not work ?

Im using option  powershell/meterpreter/rev_https  in veil and converting with macroshop https://github.com/khr0x40sh/MacroShop  its works well with an exel doc everytime but just not with a word doc

**Comment by ChrisTruncer** [comment]
Sorry, but I'm not sure why it wouldn't work to be honest.

**Comment by ChrisTruncer** [comment]
Did you look into this anymore?

**Comment by vendforce** [comment]
Im still looking in to this, The macro code just doesnt seem to execute when the word doc is loaded , Im going to keep at it and try different things to see whats causing the problem as I said when executing the macro in excel document it works flawlessly , Ill keep trying and update you

**Comment by vendforce** [comment]
Ok its seem's to be the code that either veil is creating or that macroshop is converting into a macro that word doc wont run it , seems weird since as I said excel doc runs everytime and I get a powershell but when I use a word doc it fails to execute the macro 

I tested a simple greeting macro in word doc to test macro in word 

Private Sub Document_Open()
  'Greet user.
  MsgBox "Greetings", vbOKOnly, "Greetings"
End Sub

I get  a message box with message "Greetings" so the macro works fine

**Comment by vendforce** [comment]
Ok so I've got a little further :)

Subroutine Workbook_Open isn't working in word , so I have changed it to AutoOpen and it works now and I get a powershell when the word doc opens horray !!!!!
