### ISSUE TITLE
Disable Macros Warnings

### ISSUE THREAD

**Issue by vendforce** [Veil-Framework/Veil-Evasion#316]
## OS Arch

This would be usefull to add to the batch file to disable the macro security warnings 

#### Excel
REG ADD HKEY_CURRENT_USER\Software\Microsoft\Office\14.0\Excel\Security /v AccessVBOM /t REG_DWORD /d 1 /f

REG ADD HKEY_CURRENT_USER\Software\Microsoft\Office\14.0\Excel\Security /v VBAWarnings /t REG_DWORD /d 1 /f

####  Word
REG ADD HKEY_CURRENT_USER\Software\Microsoft\Office\14.0\Word\Security /v AccessVBOM /t REG_DWORD /d 1 /f

REG ADD HKEY_CURRENT_USER\Software\Microsoft\Office\14.0\Word\Security /v VBAWarnings /t REG_DWORD /d 1 /f

**Comment by ChrisTruncer** [comment]
This would work for the second time the macro is executed, but the first time those keys wouldn't be set and would then still be present.

Also, while it could help, I'll leave this to the end user to do. I don't want to add in something like this that would reduce a client's workstation without manual interaction by the user.
