### ISSUE TITLE
Pyinstaller,pwnstaller Directory Problem

### ISSUE THREAD

**Issue by unknownish** [Veil-Framework/Veil-Evasion#317]
## Veil-Evasion version
2.26

## OS Used - all info (architecture, linux flavor, etc)

Kali Linux Rolling 2016.1 x86

Can somebody help me with the pwnstaller.
# copy the original runw.exe into the proper location
                runwPath = settings.VEIL_EVASION_PATH+"tools/runw_orig.exe"
                os.system("cp "+runwPath+" " + settings.PYINSTALLER_PATH + **"support/loader/Windows-32bit/runw.exe**") 
 # copy the loader into the correct location
    os.system("mv runw.exe " + settings.PYINSTALLER_PATH + "support/loader/Windows-32bit/")

    print " [*] Pwnstaller runw.exe moved to "+ settings.PYINSTALLER_PATH + "support/loader/Windows-32bit/\n"

Whats the new directory at the new pyinstaller 3.1.1 for **support/loader/Windows-32bit/** ?
When I create a executable with pwnstaller it doesnt gets the icons from the icon folder it gets the default icon of the python.I think something is wrong with the directory and it doesnt uses the runw.exe that the pwnstaller created.
But when i change the directory "support/loader/Windows-32bit/\n" to pyinstaller/PyInstaller/bootloader/Windows-32bit/ it creates a executable with the selected icon but I think its not a working executable when i click the exe nothing starts at windows platform(checked task manager) and in kali it cant open the executable. Sorry for my bad english .Thank you for your help. @ChrisTruncer @rhertzog

**Comment by ChrisTruncer** [comment]
We're looking into this on another ticket, please wait until that is closed.
