### ISSUE TITLE
[ERROR]: Veil-Evasion Only Supported On Ubuntu 15.10+.

### ISSUE THREAD

**Issue by AliBawazeEer** [Veil-Framework/Veil-Evasion#320]
## Veil-Evasion version
latest available on GITHUB , 

while running ./setup.sh encountered the following error message  

## OS Used - all info (architecture, linux flavor, etc)
ubuntu 14

## Any additional info you want to tell me

**Comment by gordonrs** [comment]
As you can clearly see... we don't support Ubuntu 14, only 15 and above. We're not going to support 14LTS. This can now be closed.

**Comment by ChrisTruncer** [comment]
Exactly what @gordonrs said.  Thanks!
