### ISSUE TITLE
Error installing Veil-Evasion on Kali-Rolling v2016.1

### ISSUE THREAD

**Issue by ocasagrande** [Veil-Framework/Veil-Evasion#321]
## OS Used 
SMP Debian 4.3.3-5kali4 (2016-01-13)

## Pastebin link to error you are encountering (include console actions you took prior to error)
Error:
E: Unable to correct problems, you have held broken packages.
 ERROR Failed to install Wine... Exit Code: 100

## Expected behavior
Complete the installation

## Any additional info you want to tell me
Follow many blogs about resolving the issue but no result.

**Comment by ChrisTruncer** [comment]
Do you have the source repos available?

**Comment by ChrisTruncer** [comment]
Also, please search the existing issues we have.  This has been talked about before.  Finally, you barely provided information.  I am going to need more than what you gave to troubleshoot this.

**Comment by ocasagrande** [comment]
Hi Chris, sorry for not sent you more information I´m newbie with this....
I followed many sites mentioning this event but could not solve this issue.

The screen running ./setup.sh

root@kaliorca:/opt/Veil/Veil-Evasion/setup# ./setup.sh
==========================================================================
 Veil-Evasion (Setup Script) | [Updated]: 2016-02-23
==========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
==========================================================================


 [I] Kali Linux "2016.1" x86_64 Detected...


 [?] Are you sure you wish to install Veil-Evasion?

 Continue With Installation? ([y]es/[s]ilent/[N]o): y


 [*] Initializing Package Installation

 [*] Adding x86 Architecture To x86_64 System for Wine
 [*] Installing Wine 32bit and 64bit Binaries
E: Package 'wine32' has no installation candidate
 [ERROR] Failed to install Wine... Exit Code: 100.

root@kaliorca:/opt/Veil/Veil-Evasion/setup#

The repos (sources.list)

root@kaliorca:/opt/Veil/Veil-Evasion/setup# cat /etc/apt/sources.list
#

# deb cdrom:[Debian GNU/Linux 2016.1 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20160120-18:14]/ kali-rolling contrib main non-free

#deb cdrom:[Debian GNU/Linux 2016.1 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20160120-18:14]/ kali-rolling contrib main non-free

#deb http://http.kali.org/kali sana main non-free contrib
#deb http://security.kali.org/kali-security sana/updates main contrib non-free

#deb-src http://http.kali.org/kali sana main non-free contrib
#deb-src  http://security.kali.org/kali-security sana/updates main contrib non-free
root@kaliorca:/opt/Veil/Veil-Evasion/setup#

Thanks for your help.

**Comment by ChrisTruncer** [comment]
all of your repos are commented out...  I don't know how it is finding anything.

**Comment by ocasagrande** [comment]
jaja, sorry that was after testing different options.
I try with uncommented. Sorry for the wrong info.
repos are uncommented but the error is the same.

**Comment by ChrisTruncer** [comment]
Sorry, I really don't know what to say.  I've just run this on Kali rolling VMs and they are all installing properly.

**Comment by ocasagrande** [comment]
Don't worry I will install from scratch again and I will try 32 bits version of Kali.
Thanks. I will let you know

**Comment by vendforce** [comment]
Try adding i386 so 32 bit librarys can be installed
dpkg --add-architecture i386

**Comment by ocasagrande** [comment]
Hi vendforce, I did it but no results. Thanks.
Now I will test kali 32bits
Thanks

**Comment by vendforce** [comment]
what do you mean no results ?? you have to install the 32 bit libaries
sudo apt-get -y install ia32-libs

**Comment by ChrisTruncer** [comment]
I am using x64 Kali rolling and it is installing without any problems

**Comment by ocasagrande** [comment]
Hi everyone, thanks for your help. I solved the issue.
First my repos was wrong. 
They was pointing to 
deb http://http.kali.org/kali sana main non-free contrib
deb http://security.kali.org/kali-security sana/updates main contrib non-free

I changed to: 
deb http://http.kali.org/kali kali-rolling main contrib non-free
deb http://http.kali.org/kali sana main non-free contrib
deb http://security.kali.org/kali-security sana/updates main contrib non-free
deb http://old.kali.org/kali moto main non-free contrib

And the other change that I made was install Veil-Framework first.
I'm reading a book about hacking and the lab ask to install wine before Veil and I change the order.

Issue solved.
thanks for your time.

**Comment by ahmedezzalden** [comment]
i have the same problem her but i'm using  parrot 3.1 !!
what should i do ?

**Comment by rboot071** [comment]
hi this is ali ihave problem in installing 
my problem is: cant installing wine 32 and exit code 100 my repos is:


 deb http://http.kali.org/kali kali-rolling main contrib non-free
 deb http://http.kali.org/kali sana main non-free contrib
 deb http://security.kali.org/kali-security sana/updates main contrib non-free
 deb http://old.kali.org/kali moto main non-free contrib
and im using kali 2016.1 64bit please help me.!!!!

**Comment by sofianedz025** [comment]
~/Veil-Evasion/setup# ./setup.sh -s

**Comment by gambl3** [comment]
ocasagrande's fix was spot on. once i adjusted my /etc/apt/sources.list as he described everything worked great when running the setup.sh script
