### ISSUE TITLE
PEScrambler & hyperion not working

### ISSUE THREAD

**Issue by EinderJam** [Veil-Framework/Veil-Evasion#326]
I used Veil-Evasion to generate a c/meterpreter/rev_tcp payload.Veil compiles it to an exe,located at /usr/share/veil-output/compiled/rev_tcp.exe.
Then,i load the native/hyperion module,i do 
**set ORIGINAL_EXE /usr/share/veil-output/compiled/rev_tcp.exe**
i type **generate**,and i have this 
![capture du 2016-04-25 14 24 13](https://cloud.githubusercontent.com/assets/16850696/14783702/a5a09374-0af1-11e6-8596-b35095695d30.png)
i get the same error when trying to use PEScrambler
Any idea ?
ps:I'm using kali linux 2.0 and veil-evasion 2.26.2

**Comment by ChrisTruncer** [comment]
Have you tried on Kali rolling? I can look at it, but just a FYI we only support the latest version of Kali

**Comment by alxrogan** [comment]
Same issue here, Kali Rolling, Veil-Evasion installed via git, settings.pyc created with sudo python update.py from the config/ folder.

**Comment by phant0m-X** [comment]
Also here with the same issue

**Comment by ChrisTruncer** [comment]
Yeah, I'll get looking into this soon.  Work has kept me busy as of late

**Comment by ChrisTruncer** [comment]
This issue should now be fixed.  Thanks for letting me know.  I'm closing this out.
