### ISSUE TITLE
issue while runing setup

### ISSUE THREAD

**Issue by AliBawazeEer** [Veil-Framework/Veil-Evasion#327]
## OS Used - all info (architecture, linux flavor, etc)
ubuntu 15 x64 

facing issue while run the setup ./setup.sh

ERROR] Failed To Install (Wine) Ruby.exe... Exit Code: 1.

**Comment by AliBawazeEer** [comment]
*] Installing (Wine) Ruby & Dependencies
[*] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.
fixme:process:SetProcessDEPPolicy (1): stub
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
fixme:process:SetProcessDEPPolicy (1): stub
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
fixme:win:DisableProcessWindowsGhosting : stub
[ERROR] Failed To Install (Wine) Ruby.exe... Exit Code: 1.

**Comment by AliBawazeEer** [comment]
root@debian-pentest:~/Veil-Evasion/setup# wine --version
wine-1.6.2

**Comment by AliBawazeEer** [comment]
test@pentest:~/Veil-Evasion/setup# wine --version
wine-1.6.2

**Comment by vendforce** [comment]
sudo dpkg --add-architecture i386 
sudo add-apt-repository -y ppa:wine/wine-builds
sudo apt-get -y update
sudo apt-get -y dist-upgrade

sudo rm -rf $HOME/.config/wine

then try installing again

**Comment by ChrisTruncer** [comment]
Do you have wine installed?  and is it x86 wine?

**Comment by gordonrs** [comment]
@vendforce You don't have to manually add i386 architecture, the setup script does that, and installs mingw-w64 automatically. I also don't recommend using a PPA for the builds because it doesn't make much sense to support builds that aren't in the official repositories.

@AliBawazeEer First, are you actually running an X server or are you trying to install over ssh or something?

Does it still happen if you do a clean install with `sudo setup/setup.sh -c` ?

**Comment by AliBawazeEer** [comment]
@gordonrs  yes am trying to install it on vps over ssh .
Does it still happen if you do a clean install with sudo setup/setup.sh -c ?
yes

**Comment by gordonrs** [comment]
Yeah we don't support setting up like that. We actually launch the windows python and ruby installers in wine and that requires that you have an X session open. Just run Kali in a VM. I'll look into seeing if we can do a fully headless install in the future, but there's other things we have to tackle first.

**Comment by AliBawazeEer** [comment]
@gordonrs , appreciate your support , keep up the good work 
hats off .
this can be closed as of now . thanks again
