### ISSUE TITLE
problem in the tool Veil- evasion

### ISSUE THREAD

**Issue by yazanmasarweh** [Veil-Framework/Veil-Evasion#328]
Hello i have a problem in the tool Veil- evasion. This message appears when installed on kali Linux 1.1  (E: Unable to locate package wine32
 [ERROR] Failed To Install Wine... Exit Code: 100.)

**Comment by ChrisTruncer** [comment]
There are about 5 other tickets about this in the past.  Please search for the answer before creating a new issue.  The solution is in the other tickets.

Thanks!

**Comment by yazanmasarweh** [comment]
I can not find the solution in any tab
