### ISSUE TITLE
reverse_tcp_dns is missing payload 

### ISSUE THREAD

**Issue by vannisca** [Veil-Framework/Veil-Evasion#329]
## Veil-Evasion version
2.26.2

## OS Used - all info (architecture, linux flavor, etc)
kali 2.0 rolling

## Pastebin link to error you are encountering (include console actions you took prior to error)

aa
## Expected behavior
aa

## Any additional info you want to tell me
hi , in Veil-evasion i want to use a payload_reverse_tcp_dns , but this there isn't .  Is there any solutions ?

**Comment by ChrisTruncer** [comment]
It's in there, I just verified it.

windows/meterpreter/reverse_tcp_dns

**Comment by netdestroyer** [comment]
?? where ??? in the module of Veil-evasion 2.26.2 , there isn't the windows/meterpreter/reverse_tcp_dns !!!

**Comment by ChrisTruncer** [comment]
<img width="607" alt="payload" src="https://cloud.githubusercontent.com/assets/1674822/15122489/f923e462-15e4-11e6-818a-2ffcb139653e.png">
