### ISSUE TITLE
 [!] ERROR: Unable to create output file.   [!] Internal error #2. Unable to generate output. Please run /root/Veil/config/update.py manually

### ISSUE THREAD

**Issue by CrimzonScythe** [Veil-Framework/Veil-Evasion#333]
## Veil-Evasion version
Veil-Evasion | [Version]: 2.26.3

## OS Used - all info (architecture, linux flavor, etc)
4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-5kali4 (2016-01-13) x86_64 GNU/Linux

## Pastebin link to error you are encountering (include console actions you took prior to error)

![1](https://cloud.githubusercontent.com/assets/19368722/15271983/49fbe636-1a32-11e6-81af-e7485fa1197e.png)
![2](https://cloud.githubusercontent.com/assets/19368722/15271985/49fceebe-1a32-11e6-88bd-9847f659f2d8.png)
![3](https://cloud.githubusercontent.com/assets/19368722/15271984/49fce860-1a32-11e6-8f9d-01be499da647.png)
![4](https://cloud.githubusercontent.com/assets/19368722/15271987/4a014bb2-1a32-11e6-9b23-f7d381ff4271.png)
![5](https://cloud.githubusercontent.com/assets/19368722/15271986/4a00fcca-1a32-11e6-9b56-888d48c09af5.png)
![6](https://cloud.githubusercontent.com/assets/19368722/15271988/4a04413c-1a32-11e6-8bcd-968a81218b18.png)
![7](https://cloud.githubusercontent.com/assets/19368722/15271989/4a050964-1a32-11e6-8e40-1ae15209ac56.png)
![8](https://cloud.githubusercontent.com/assets/19368722/15271990/4a0b2e8e-1a32-11e6-9fe1-2d5258f2b396.png)

## Expected behavior
What could be causing this error? I have tried UN-installing wine and re-running the setup.sh to no avail. I then tried to UN-install Veil-Evasion all together and then re-install it, also did not work. The sources I am using are:

deb http://http.kali.org/kali kali-rolling main contrib non-free
deb http://http.kali.org/kali sana main non-free contrib
deb http://security.kali.org/kali-security sana/updates main contrib non-free
deb http://old.kali.org/kali moto main non-free contrib

As far as I know there was not an error during install, but I am also still a script-kiddy myself in the Linux department

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
So it looks like you might be using Kali 2.0, is that the case? Can you try Kali rolling?

**Comment by CrimzonScythe** [comment]
Running upgrade now, didn't notice that. I will let you know if it is fixed after this is done.

**Comment by CrimzonScythe** [comment]
Still receiving the same error.
![screenshot from 2016-05-15 02-38-07](https://cloud.githubusercontent.com/assets/19368722/15272431/29a52faa-1a46-11e6-9e75-680e62561b3f.png)

**Comment by CrimzonScythe** [comment]
Here is the install from ./setup.sh --clean
[VeilInstallLog.txt](https://github.com/Veil-Framework/Veil-Evasion/files/264951/VeilInstallLog.txt)

**Comment by CrimzonScythe** [comment]
It was the /usr/share/pyinstaller. Removed the directory and used a fresh copy for install and everything is working fine now

**Comment by ChrisTruncer** [comment]
Great, thanks for reporting the issue and fix!

**Comment by malek234** [comment]
please can you tell me how you fix it because I have the same error in payloads with python
