### ISSUE TITLE
unmet dependencies of libgnome-vfs2.0-cil in Ubuntu 16.04 x64

### ISSUE THREAD

**Issue by sidjad** [Veil-Framework/Veil-Evasion#335]
## Veil-Evasion version

latest version 
## OS Used - all info (architecture, linux flavor, etc)

Ubuntu 16.04 x64
## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/rgLfqYjM

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Is there a package that we can replace that with that you know of?

**Comment by sidjad** [comment]
sorry , No idea about any replacing package .

**Comment by ChrisTruncer** [comment]
Just a heads up, might be a repo or some other issue you may have encountered.  I just download 16.04 x64 and ran the setup.  It completed perfectly and the tool is now running without an issue.  Maybe give a retry.

Thanks!
