### ISSUE TITLE
Veil ERROR: something went wrong while obfuscating python code.

### ISSUE THREAD

**Issue by freshd** [Veil-Framework/Veil-Evasion#336]
## Veil-Evasion version
2.26.3

## OS Used - all info (architecture, linux flavor, etc)
Ubuntu 15.04

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/wv8dJq1u

ERROR: something went wrong while obfuscating python code.

## Expected behavior
No error to be reported 

## Any additional info you want to tell me

Hi, encountering the next error when generating Python based payloads, tested with option 35 and all the default options (except call home ip address and port), the payload does get generated, however it errors. I understand the issue is in modules/common/supportfiles.py but not sure why the error occurs.

**Comment by ChrisTruncer** [comment]
Oddly enough, I was wanting to remove pyobfuscate also.  As of now, it's still present, but just commented out.  This should solve and prevent the error from popping up again for you.
