### ISSUE TITLE
Unable to determine OS information

### ISSUE THREAD

**Issue by sabsowitz** [Veil-Framework/Veil-Evasion#338]
I just cloned the latest version of Veil-Evasion. I am using Mac OSX El Capitan. I have been unable to find any information regarding this matter, but assumed that the Veil Framework would work for OSX. 
When I attempt to run ./setup.sh I receive the following error:
`./setup.sh: line 557: [: ==: unary operator expected
./setup.sh: line 559: [: ==: unary operator expected
 [!] Unable to determine OS information. Exiting...`

Is it not possible to use Veil on OSX, or do I need Kali or a Debian based linux distro?

**Comment by sabsowitz** [comment]
I just searched through the closed issues and discovered that OSX is not supported. Sorry for the duplicate issue. I'm going to go ahead and close the issue.

**Comment by ChrisTruncer** [comment]
Yeah, no problem at all.  Sorry, but yeah, we need a lot of things in Linux where we're picking that for support vs. OSX

**Comment by Fahim-Ferdous** [comment]
I am using linux mint, but having this problem. a few months ago, i installed it correctly. but now i am facing this problem

**Comment by x0dus35** [comment]
@Fahim-Ferdous 
To install it on linux mint go to setup dir and run this commands
`sed -i 's/ubuntu/linuxmint/g' setup.sh` This command will change the os detection from ubuntu to linux mint
`sudo ./setup.sh` re-execute the installation script
