### ISSUE TITLE
Debian Testing install Veil-Evasion Error

### ISSUE THREAD

**Issue by dxg74120** [Veil-Framework/Veil-Evasion#340]
## OS isDebian Testing

susu@debian:~/Tools/Veil-Evasion/setup$ ./setup.sh -s

id: "": no such user
==========================================================================
 Veil-Evasion (Setup Script) | [Updated]: 2016-02-23
==========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
==========================================================================

./setup.sh: 第 545 行:[: -lt: 需要一元表达式

 [*] Initializing Package Installation

 [*] Silent Mode: Enabled 

 [*] Adding x86 Architecture To x86_64 System for Wine
 [*] Installing Wine 32bit and 64bit Binaries
 [*] Creating new Veil Wine environment in /home//.config/wine/veil 
 [*] Initializing Veil's Wine environment...
sudo: 未知用户：mkdir
sudo: 无法初始化策略插件
sudo: 未知用户：WINEARCH=win32
sudo: 无法初始化策略插件
 [ERROR] Veil Wine environment could not be found!

         Check for existence of /home//.config/wine/veil/drive_c

**Comment by ChrisTruncer** [comment]
So, Veil-Evasion does work on Debian Stable (I just tested last week).  We're specifically targeting only Debian Stable for support, and not testing, but I would also think testing should work.  I'm not certain, but this could also be an issue with localization that Veil is somehow messing up.  Could you please try Debian Stable and let me know if it works?

**Comment by dxg74120** [comment]
I use root success
