### ISSUE TITLE
runw.exe': No such file or directory

### ISSUE THREAD

**Issue by smurph211** [Veil-Framework/Veil-Evasion#345]
## Veil-Evasion version

Veil-Evasion | [Version]: 2.26.4

## OS Used - all info (architecture, linux flavor, etc)
Ubuntu 16.04 x86_64

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/PLK1uFbd

## Any additional info you want to tell me
im not sure what the root cause of this issue is. i think it may have something to do with line 134 in the paste. running as root does not give the errors from line 135 to line 165 but still spits out the error on line 134 and wont generate output.

i apologize if this is a trivial issue or if it has been solved already. i read all related issues i could find and no fix.

**Comment by ChrisTruncer** [comment]
This should be fixed now, although the error shouldn't have caused Veil-Evasion to not function correctly.

Thanks!
