### ISSUE TITLE
Veil Install Error - Fresh setup of Kali x86

### ISSUE THREAD

**Issue by eagleboy007** [Veil-Framework/Veil-Evasion#347]
## Veil-Evasion version
latest from github

## OS Used - all info (architecture, linux flavor, etc)
 Kali Linux "2016.1" i686 Detected

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/Lj7E2Waa  <--- error here 

## Any additional info you want to tell me
-please share steps if you have , i have followed many steps and forums, but nothing could give concrete solution.

**Comment by ChrisTruncer** [comment]
Have you had this previously installed?  Can you try on a clean kali install?

**Comment by eagleboy007** [comment]
Hi Chris,

Yes, this is fresh install of Kali and i have been using Kali from long. I
was using 64bit version and got errors in installing Veil. So i downloaded
fresh 32 bit OS and got the new error that i gave you.

On Wed, Jun 8, 2016 at 3:46 AM, ChrisTruncer <notifications@github.com>
wrote:

> Have you had this previously installed? Can you try on a clean kali
> install?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Veil-Framework/Veil-Evasion/issues/347#issuecomment-224431487>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS4gTOqhj62Waq-XZjpkAyspNOg0G7iLks5qJe2zgaJpZM4Iv7nV>
> .
>



-- 

Thanks and Regards,

*Milin Shah*| I
nformation Security Consultant| IT Risk Governance and Compliance
connect me : www.facebook.com/eagleboy007

*+91-98-333-95595 *
*AFCEH | CISE |CEH*

**Comment by ChrisTruncer** [comment]
It looks like a lot of errors are based on not finding packages.  Please ensure you have your source repos uncommented.  I unfortunately can't seem to reproduce this.  I'm using a clean Kali install here as well and it completed the setup fine after I cloned from here.

**Comment by eagleboy007** [comment]
Hi Chris,

Are you using the latest version or you have a version older or something ?

Also, can you share if possible the list of repos i can add to source.list.

**Comment by ChrisTruncer** [comment]
I don't have a list on me, but just do a search and find them online.  And look up how to enable source repos.  And I have the latest version from their site.

**Comment by ChrisTruncer** [comment]
if enabling source repos doesn't work, please let me know

**Comment by eagleboy007** [comment]
Thanks a lot Chris! Will try !
