### ISSUE TITLE
ERROR: Unable to create output file.

### ISSUE THREAD

**Issue by hanwenlee** [Veil-Framework/Veil-Evasion#350]
## Veil-Evasion version
Veil-Evasion | [Version]: 2.26.5
 Veil-Evasion (Setup Script) | [Updated]: 2016-02-23

## OS Used - all info (architecture, linux flavor, etc)

Install a fresh copy of kali linux 64bit in vmware:
Kali Linux "2016.1" x86_64
uname -a
Linux kali 4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-5kali4 (2016-01-13) x86_64 GNU/Linux

## Pastebin link to error you are encountering (include console actions you took prior to error)

http://pastebin.com/5pYhanjy
## Expected behavior
Expect to generate a payload.exe but get the following errors:
[!] ERROR: Unable to create output file.

 [!] Internal error #2. Unable to generate output. Please run /root/Desktop/tmp/Veil-Evasion/config/update.py manually

## Any additional info you want to tell me
I have tried a few times reinstalling fresh copy of kali linux, clone and reinstalled Veil-Evasion but still get the same error of unable to generate output.

Then, I run update.py, but still get the same error:
root@kali:~/Desktop/tmp/Veil-Evasion/config# sudo ./update.py

After that, I delete the Veil Wine profile (rm -rf '/root/.config/wine/veil') and re-run: '/root/Desktop/tmp/Veil-Evasion/config/setup.sh, but still get the same error.

**Comment by hanwenlee** [comment]
one more interesting issue, if I reboot, i will stuck at login page. I confirm my password is correct. And it happens if i go through the same steps that I mentioned in pastebin link.

**Comment by MystikReasons** [comment]
I have the same problem with the output :/

Also tried to reinstall and then update veil but still not working.

**Comment by ChrisTruncer** [comment]
Veil has nothing to do with getting stuck at login.

What you could try to do uncomment the try except in the code here (https://github.com/Veil-Framework/Veil-Evasion/blob/c6c867402e5a9651dba00e6f8007c7b4d6aa6d25/modules/common/controller.py#L623-641) and then you would get the real error.  Post that here please.

**Comment by hanwenlee** [comment]
Wow!
after comment the try except and looking at the error message. I realize that the root cause is:
Please enter the base name for output files (default is 'payload'): sample.exe

It is working fine if I input:
Please enter the base name for output files (default is 'payload'): sample

Now, I am able to generate the payload. Thanks Chris for looking into my problem :-)

**Comment by CarlosVilleags** [comment]
Hello,

I'm running into a little snag and i'm super new (and very interested) with Veil-Evasion, so I appreciate if you could point me in the right direction. 

I followed ChrisTruncer's suggestion (above, Jun 17) to comment-out the try/catch statement in the controller.py. Here's what I got:

`cp: cannot create regular file '/opt/pyinstaller-2.0//PyInstaller/bootloader/Windows-32bit/runw.exe': No such file or directory
C:\Python27\python.exe: can't open file '/opt/pyinstaller-2.0//pyinstaller.py': [Errno 2] No such file or directory`

I really appreciate help in getting my problem resolved. :) !!

Carlos
