### ISSUE TITLE
fruitywifi xtr4nge

### ISSUE THREAD

**Issue by Digita-Nightmare** [Veil-Framework/Veil-Evasion#351]
i was wondering if i could run fruitywifi from ssh  on the raspberry pi i really didnt want to have a tv
in order to use this feature its hard to put a tv in a pringles can lol

or is there a way with karma on fruity wifi to create an ssid and connect to it just like the wifi pineapple 
you can tell im new to this i just installed kali linux on the raspberry pi then i donr all the updates / upgrades "as usual"  then i installed fruitywifi and started php5 and the other services its ready to rock and roll but i really want this over ssh via my laptop i hope i am being clear about this if im not please tell me and ill try to explain better i am a newbi at this so please be kind lol any help at all would be appreciated

**Comment by Digita-Nightmare** [comment]
nevermind guys i figured it out  sorry if i wasted anyones time i feel stupid  all i had to do is...........................................

my raspberry pi is connected to my router all i had to do was   ssh root@10.0.0.11  "thats the ip from the router"  via ethernet  "for now for testing purposes"

password:toor "default "..........

once i was ssh'ed in i had to start   (          /etc/init.d/fruitywifi start    )  and then  (       /etc/init.d/php5-fpm start     )       

and since im on the same network with the raspberry pi   i opened firefox and typed    .............  10.0.0.11:8000    or   10.0.0.11:8443

the 8000 port is for http:   and the  8443 port is for https:  

once i did that i was prompted to login to fruity wifi admin admin 

sorry if i sound stupid but maybe this will help someone else idk   

i just know i didnt want to have to plug this thing into a tv all the tim in order to use it mobile    like i said you cant fit a tv in a pringles can lol  .....

but all the same thank you guys for just being here for me to ask questions to   cheers :..........

**Comment by strasharo** [comment]
What does have Veil to do with FruityWifi?!

**Comment by Digita-Nightmare** [comment]
sorry man i had so many pages open i pasted it to the wrong one lol 
i just wasnt paying attention ..........please forgive me ...thanks

**Comment by Digita-Nightmare** [comment]
sorry i had an old page open i did not have any sleep i was up all night i
accidently posted that without thinking
so i sincerely appologize that post  was ment to go to hak5 forums once
again im sorry
