### ISSUE TITLE
what is this ? pls help 

### ISSUE THREAD

**Issue by Defalt2** [Veil-Framework/Veil-Evasion#355]
can i ask ?
what is this code mean? 
HTTP request sent, awaiting response... 200 OK
Length: 80147269 (76M) [application/x-gzip]
Saving to: ‘go153x64.tar.gz.2

go153x64.tar.gz.2   100%[===================>]  76.43M   138KB/s    in 6m 7s   

2016-06-20 22:44:48 (213 KB/s) - ‘go153x64.tar.gz.2’ saved [80147269/80147269]

\033[01;31mHASH MISMATCH!  Run again, or alert developer!!!!\033[00m
`

**Comment by ChrisTruncer** [comment]
Please delete your go153x64 files and re-run the setup script.  It looks like your system did not download the file successfully.

**Comment by Defalt2** [comment]
Thank you You safe me !!!
