### ISSUE TITLE
Python {ayload Genetration Issue

### ISSUE THREAD

**Issue by feralfenrir** [Veil-Framework/Veil-Evasion#361]
## Veil-Evasion version
 Veil-Evasion | [Version]: 2.27.1

## OS Used - all info (architecture, linux flavor, etc)
Kali Rolling 2016 x86_64 (Updated)

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/zhFpdnqk

## Expected behavior
Generation of a Python payload using PyInstaller

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
This issue has been discussed, please search the existing issues on here before creating a new one.  Thanks
