### ISSUE TITLE
kali doesn't open after veil-evasion installation

### ISSUE THREAD

**Issue by camaell** [Veil-Framework/Veil-Evasion#362]
## Any additional info you want to tell me

**Comment by camaell** [comment]
I installed veil-evasion on kali linux and after i reboot the system, kali didn't open. it stucked on the login screen. I'm writing my username and password but it's shows me the login screen again and again instead of open it. what can i do about that?

**Comment by ChrisTruncer** [comment]
Sorry, but Veil-Evasion wouldn't cause this.  It doesn't touch anytime for your system's startup

**Comment by camaell** [comment]
but i re-installed kali and this problem occured whenever i tried to install veil.

**Comment by benichmt1** [comment]
For the record I had this issue as well on Kali 2.0 x64
