### ISSUE TITLE
error installation on Arch linux

### ISSUE THREAD

**Issue by dummys** [Veil-Framework/Veil-Evasion#366]
## Veil-Evasion version
latest

## OS Used - all info (architecture, linux flavor, etc)
archlinux

## Pastebin link to error you are encountering (include console actions you took prior to error)
the trueuser in the install.sh script is not working, the command "who am i" return nothing under Arch linux.

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Do you have a patch you could submit for this?  We don't officially support arch but have tried to add in some support for it.  If you have a patch, I'd be happy to look at it.

**Comment by ChrisTruncer** [comment]
I just pushed a fix for this I believe.  Please go ahead and try the install again.

Thanks

**Comment by dummys** [comment]
unfortunately I have no time to dig on this right now. There is not only this that bug, there is also the python install with wine that is faulty.
Thanks for fix btw.

**Comment by ChrisTruncer** [comment]
There shouldn't be a wine install issue.

Thanks for the help reporting this!

**Comment by p403nix** [comment]
Is there a fix for this error? am having the same issue... Please this is urgent
