### ISSUE TITLE
ERROR: Invalid payload specified!

### ISSUE THREAD

**Issue by netdestroyer** [Veil-Framework/Veil-Evasion#367]
## Veil-Evasion version
2.27.1

## OS Used - all info (architecture, linux flavor, etc)

Kali rolling

## Pastebin link to error you are encountering (include console actions you took prior to error)
Press [enter] for windows/meterpreter/reverse_tcp
 [*] Press [tab] to list available payloads
 [>] Please enter metasploit payload: 
 [!] ERROR: Invalid payload specified!

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
I just installed Veil-Evasion on Kali Rolling, so I can verify that this works.  You might not have the right path for your metasploit path within your settings.py file.  Can you run the update.py script again?

**Comment by ChrisTruncer** [comment]
This will only happen if you are specifying an invalid payload, or the metasploit path is not correct.  Please check both because one will be the fix.

Thanks, and let me know if you run into another issue with this.

**Comment by netdestroyer** [comment]
I resolved , I changed the path of metasploit  but when i create  a python/aes_encrypt , the payload works good but remains the open window of payload.exe , 
should disappear window , why ??

**Comment by ChrisTruncer** [comment]
Because there's a bug in pyinstaller so that is the only way for the current python payloads to work
