### ISSUE TITLE
Installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by OutCell** [Veil-Framework/Veil-Evasion#372]
## Veil-Evasion version
Lastest, downloaded yesterday.

## OS Used - all info (architecture, linux flavor, etc)
**Ubuntu 16.04 MATE (64bit) - on Lenovo Carbon X1 thinkpad, 4th gen.**

## Pastebin link to error you are encountering (include console actions you took prior to error)
Pasted below

## Expected behavior
Does not complete the install.

## Any additional info you want to tell me
**Below is the result of running setup.sh**

als@desktop:~/Veil-Evasion/setup$ sudo bash ./setup.sh -c
[sudo] password for als: 
id: ‘als\nals’: no such user
==========================================================================
 Veil-Evasion (Setup Script) | [Updated]: 2016-02-23
==========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
==========================================================================

 [I] Ubuntu 16 x86_64 Detected...

[*] Initializing Package Installation
[*] Adding x86 Architecture To x86_64 System for Wine
W: GPG error: http://ppa.launchpad.net/wine/wine-builds/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E61A24DF77C899CB
W: The repository 'http://ppa.launchpad.net/wine/wine-builds/ubuntu xenial InRelease' is not signed.
W: The repository 'http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu xenial Release' does not have a Release file.
W: The repository 'http://ppa.launchpad.net/tiheum/equinox/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/tiheum/equinox/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.[*] Installing Wine 32bit and 64bit Binaries
(Reading database ... 266040 files and directories currently installed.)
Removing winehq-devel (1.9.13~ubuntu16.04.1) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160523-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Selecting previously unselected package wine1.6-amd64.
(Reading database ... 265979 files and directories currently installed.)
Preparing to unpack .../wine1.6-amd64_1%3a1.6.2-0ubuntu14_amd64.deb ...
Unpacking wine1.6-amd64 (1:1.6.2-0ubuntu14) ...
Selecting previously unselected package wine1.6-i386:i386.
Preparing to unpack .../wine1.6-i386_1%3a1.6.2-0ubuntu14_i386.deb ...
Unpacking wine1.6-i386:i386 (1:1.6.2-0ubuntu14) ...
Selecting previously unselected package wine1.6.
Preparing to unpack .../wine1.6_1%3a1.6.2-0ubuntu14_amd64.deb ...
Unpacking wine1.6 (1:1.6.2-0ubuntu14) ...
Selecting previously unselected package wine.
Preparing to unpack .../wine_1%3a1.8.0-0ubuntu1~ubuntu15.10.1~ppa1_amd64.deb ...
Unpacking wine (1:1.8.0-0ubuntu1~ubuntu15.10.1~ppa1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160523-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up wine1.6-amd64 (1:1.6.2-0ubuntu14) ...
Setting up wine1.6-i386:i386 (1:1.6.2-0ubuntu14) ...
Setting up wine1.6 (1:1.6.2-0ubuntu14) ...
Setting up wine (1:1.8.0-0ubuntu1~ubuntu15.10.1~ppa1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...[*] Creating new Veil Wine environment in /home/als als/.config/wine/veil [*] Initializing Veil's Wine environment...
sudo: als: command not found
sudo: als: command not found
 [ERROR] Veil Wine environment could not be found!

         Check for existence of /home/als als/.config/wine/veil/drive_c

**Comment by ChrisTruncer** [comment]
Please use pastebin or something similar for large code pastes.

This looks to be an issue with the repos you are using.  It can't find any of the packages that are required.  I just installed Veil-Evasion on stock Ubuntu 16.04 and verified that it is able to download the required packages.

**Comment by OutCell** [comment]
Will use pastebin, thanks.

I will reinstall Wine and Veil-Evasion and try again
