### ISSUE TITLE
Necessary component missing

### ISSUE THREAD

**Issue by netdestroyer** [Veil-Framework/Veil-Evasion#374]
## Veil-Evasion version

the last version
## OS Used - all info (architecture, linux flavor, etc)
Kali 2.0 rolling 

## Pastebin link to error you are encountering (include console actions you took prior to error)
=========================================================================
 Necessary component missing
 Please run: bash /root/Veil-Evasion/setup/setup.sh -s
=======================================================================

## Any additional info you want to tell me
I install veil evasion  setup.sh -c

But when i launch veil ./Veil-evasion.py

========================================================================
 Necessary component missing
 Please run: bash /root/Veil-Evasion/setup/setup.sh -s
=======================================================================

**Comment by veil-evasion** [comment]
Hello,

You didn't provide any of the information that's requested when making a github issue. I can't really help based off of what you gave me.

**Comment by netdestroyer** [comment]
the installation of veil is OK but when run it , display this message error :

Necessary component missing
Please run: bash /root/Veil-Evasion/setup/setup.sh -s
