### ISSUE TITLE
Improve Installation Process

### ISSUE THREAD

**Issue by zero77** [Veil-Framework/Veil-Evasion#377]
## Veil-Evasion version:
2.28.1

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux

During the installation process Veil Evasion does not detect if the dependences are already installed, instead it makes you reinstall them and if you cancel any of the dependences installation process it fails and you have to start all over again.

Can you add detection for already installed dependences.

**Comment by ChrisTruncer** [comment]
Veil-Evasion already does a lot of dependency detection. We first use apt everywhere we can, which auto-detects installation of dependencies. For the libraries we manually have to install, there is also dependency detection there.

Please look at the setup script and you will see it throughout the entire script.
