### ISSUE TITLE
I am trying to install veil evation on kali 2016.1 and this error occurs

### ISSUE THREAD

**Issue by Ghostrisen** [Veil-Framework/Veil-Evasion#380]
I am trying to install Veil-Evation on kali 2016.1 and this error occurs...........

E: Package 'wine32' has no installation candidate
 [ERROR] Failed to install Wine... Exit Code: 100

Plz help to fix this 

kali   [ 64-Bit ]

**Comment by ChrisTruncer** [comment]
Please change your repos, this has been discussed multiple times on here.
