### ISSUE TITLE
Manjaro (Arch) support

### ISSUE THREAD

**Issue by indigopsy** [Veil-Framework/Veil-Evasion#381]
## Veil-Evasion version
latest

## OS Used - all info (architecture, linux flavor, etc)
Manjaro/Arch linux x64

## Pastebin link to error you are encountering (include console actions you took prior to error)
[!] Unable to determine OS information. Exiting...

## Expected behavior
not error apparently 

## Any additional info you want to tell me
yes

can you edit file and add support for manjaro linux
it's arch based
elif [ "${os}" == "arch" ] || [ "${os}" == "manjaro" ] ; then
...

tnx

**Comment by indigopsy** [comment]
error in file setup.sh
error in line 242
"mingw-w64-mingw-w64-winpthreads"
it should be
"mingw-w64-winpthreads"

**Comment by indigopsy** [comment]
[*] Preparing Wine Python Directories...

 [*] Installing (Wine) Python...
 [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.

 [ERROR] Failed To Install (Wine) Python 2.7.5... Exit Code: 3.

**Comment by indigopsy** [comment]
so I manually type command on 332 line in terminal:
sudo -u ro0t WINEPREFIX=/home/ro0t/.config/wine/veil wine msiexec /i /usr/share/veil/setup/python-2.7.5.msi TARGETDIR=C:\Python27 ALLUSERS=1 && echo "OK"

it completed without errors.
i think error is in ${arg}
i deleted your ${arg} variable any install completed without errors, but i needed to click next next next.
same problem in line 501
i removed ${arg} variable and completed installation

tnx

bye

**Comment by ChrisFernandez** [comment]
you can install from BlackArch repos for Arch works great with Manjaro.. [blackarch.org](https://blackarch.org)  and https://github.com/BlackArch/blackarch

**Comment by ChrisTruncer** [comment]
@indigopsy I don't have plans to support that currently. If someone else wants to create a package that can do it, then that's awesome and I'm cool with that.  But right now my development time is elsewhere and I don't plan on adding that in.
