### ISSUE TITLE
Feature request: Support stageless binaries out of metasploit

### ISSUE THREAD

**Issue by Viss** [Veil-Framework/Veil-Evasion#384]
There are new payloads that would be super helpful to have in this toolkit - namely the reverse_tcp_rc4 payload and all the stageless tcp and http/s payloads. 

AV tends to catch the stages more than anything else, and adding these payloads to veil-evasion would just make it that much more sneaky

**Comment by ChrisTruncer** [comment]
Yeah, I'll look into getting this added in.  Not sure how much work it would be but I'll check.

**Comment by ChrisTruncer** [comment]
I'll go ahead and close this now, but this does exist :)

**Comment by arkantos-tas** [comment]
I know this issue is closed but I'd really like to know about creating stageless payload options using Veil. Is it possible in powershell? My payload gets stuck on Sending Stage to ................. I guess something is blocking the stage from being sent
sorry for my bad English
