### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by zero77** [Veil-Framework/Veil-Evasion#390]
Can you add support for more payloads like, Java payloads, macho payloads and php, asp, vbs and js payloads.

Adding the pyInstaller was a nice touch, could you also add an equivalent for go, ruby and java.

Can you also add reverse https c payload and more perl payloads.

Thanks

**Comment by ChrisTruncer** [comment]
Thanks for making the request.  Right now I am working on updates to Veil, so that will take priority for the meantime.  If you have any sample payloads and you're able to make a module for them, I would always love to have one submitted :)

**Comment by ChrisTruncer** [comment]
For the moment, I am leaving this open for future work, but I won't be able to look at this for now.

**Comment by ChrisTruncer** [comment]
Veil 3 is the current version, and this is no longer supported
