### ISSUE TITLE
ArchLinux Setup.sh "Unable To Determine OS Information"

### ISSUE THREAD

**Issue by BigNoseSec** [Veil-Framework/Veil-Evasion#392]
## Veil-Evasion version
2.28.2 (pull down on day posted)

## OS Used - all info (architecture, linux flavor, etc)
Antergos(ArchLinux)

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/GCP8uJgW

## Expected behavior
Sets up veil

## Any additional info you want to tell me

A previous user encountered this issue but it seems to be unresolved.

[ERROR] Unable to determine OS information. Exiting...

**Comment by BigNoseSec** [comment]
Adittionally, looking through setup.sh

`os="$(awk -F '=' '/^ID=/ {print $2}' /etc/os-release 2>&-)"
version="$(awk -F '=' '/^VERSION_ID=/ {print $2}' /etc/os-release 2>&-)"`

my output of the first:
`[x@x setup]$ awk -F '=' '/^ID=/ {print $2}' /etc/os-release 2>&-
"antergos"
`

my output of the second: 
`[x@x setup]$ awk -F '=' '/^VERSION_ID=/ {print $2}' /etc/os-release 2>&-
[x@x setup]$ 
`

**Comment by ChrisTruncer** [comment]
Hey, thanks for reporting this, but we don't officially support arch.  Some users have tried adding support in which we've allowed, but it's not a distro that's officially supported.

**Comment by ChrisTruncer** [comment]
Haven't had a response, so closing this now.  If you're interested in patching it, I'll definitely take a pull request.

**Comment by BigNoseSec** [comment]
Thanks for the response. I will work on a patch and get it to you by the
end of next week.

**Comment by emanuelecesari** [comment]
I had the same probleem on manjaro
