### ISSUE TITLE
Unable to install Python 2.7.5 on Wine

### ISSUE THREAD

**Issue by rustempasha** [Veil-Framework/Veil-Evasion#393]
## Veil-Evasion version

2.28.2
## OS Used - all info (architecture, linux flavor, etc)
Kali Linux x64
Rolling release
## Pastebin link to error you are encountering (include console actions you took prior to error)

![issue](https://cloud.githubusercontent.com/assets/6200247/19107611/945d26ca-8adc-11e6-89dd-05a0c86aa72d.png)

I can't go any further from The Python 2.7.5 setup screen, the Next button is not working.
## Expected behavior
Even Wine configuration has done in my Kali, the Python installation fails, is there any way to install Python 2.7.5 on Wine from outsource?

**Comment by ChrisTruncer** [comment]
Can you try running the setup script again?  I think that might be a Wine issue or something, because all we're doing in the setup is having msiexec run the script.

**Comment by Axotic** [comment]
Having the same issue, it's very frustrating, could really use a fix. I've tried so many things, one of which is manually installing Python 2.7.5 but I cannot seem to get it to work.

**Comment by veil-evasion** [comment]
Unfortunately, if you've also tried manually installing it, that shows that it likely isn't a Veil specific issue. If manual install did work, then it would lead me to think there might be a problem in the install process.

**Comment by Axotic** [comment]
Well, I've tried a manual install, but I don't know how or where to select the directory that veil looks for when making a payload.

**Comment by rustempasha** [comment]
I've re-installed the wine32 in my kali and it is fixed.

**Comment by Axotic** [comment]
I have no idea how to reinstall wine32, can you give me any info on how to install it?

**Comment by r1Ns3** [comment]
Yes, how do we reinstall wine32?

**Comment by rustempasha** [comment]
Sorry for late response. Our government blocked github and re-opened again lol :D.

I've typed "apt-get install wine32" before running "install.sh -c" and then it worked.

**Comment by JITUMOHANTY** [comment]
thanks it is useful for me

**Comment by thisisdipen** [comment]
I've tried  to  install wine 32 and 64 both and it says i have both upgraded version. but still python install is stuck same their, what to do?

**Comment by ChrisTruncer** [comment]
As stated on the main page, Veil-Evasion is no longer supported. Please use veil 3

**Comment by JITUMOHANTY** [comment]
go for terminal type wine --help
then check the version of wine if there is an error wine32 is not install then install wine 32 again

**Comment by poriyanetwork** [comment]
hi---i try all but check this video its working...
https://www.youtube.com/watch?v=WZhurTJ8Rws
