### ISSUE TITLE
Program does not install all dependencies if the system does not have a $DISPLAY environment variable

### ISSUE THREAD

**Issue by thecarterb** [Veil-Framework/Veil-Evasion#394]
## Pastebin link to error code:
[Error code here.](http://pastebin.com/DpLmAHE3)

## Expected behavior:

Install correctly and fully.

## Any additional info you want to tell me
The dependencies that were not installed were: `(Wine) Ruby & dependencies,` ` (Wine) OCRA gem, `and I also got a bad hash for `Go x86_64`. The location of my Metasploit installation is `/opt/metasploit-framework`. This ran on a Google Cloud VM running Debian(with no desktop environment)

## Final Veil-Framework configuration summary:
[http://pastebin.com/cFSZBk7F](http://pastebin.com/cFSZBk7F) where USERNAME is my Google username.

**Comment by ChrisTruncer** [comment]
Are you doing any sort of X-server forwarding?  I don't actually think this will fully install headlessly.

**Comment by thecarterb** [comment]
No I'm not. Does installation require the `$DISPLAY` variable to be set?

**Comment by ChrisTruncer** [comment]
It's going to require some sort of graphical interface in order to get the dependencies installed.  You have to accept certain EULAs and click through the install process.

**Comment by thecarterb** [comment]
Ah okay makes sense. Thank you :)
