### ISSUE TITLE
Python 2.7.5 Setup "Next" Button stuck... Installation Fail.

### ISSUE THREAD

**Issue by r1Ns3** [Veil-Framework/Veil-Evasion#395]
## Veil-Evasion version
Latest Veil-Evasion version

## OS Used - all info (architecture, linux flavor, etc)
Kali Rolling Linux WK39 2.2 I think...

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/vD1aBAqc

## Expected behavior
I can not press the Next button on the Python 2.7.5 "Select Destination Directory" section!!!!

## Any additional info you want to tell me
First few days on GitHub please tell me if I do anything wrong.

**Comment by ChrisTruncer** [comment]
Your whole install looked like a problem. Look at the errors. You should try to reinstall everything.

**Comment by ChrisTruncer** [comment]
Please be sure to check your console output before creating an issue.  It's likely you already have APT running in the background and it caused in issue when installing nearly all the dependencies (as shown in the logs).  It doesn't look like setup completed, or barely did at all.

Also, please cd into the setup directory and run the setup script from within it.

**Comment by r1Ns3** [comment]
Thanks for the help, sorry I wasn't very good at looking through errors, will do as you said. Thanks again :)
