### ISSUE TITLE
Cannot generate output

### ISSUE THREAD

**Issue by xeq** [Veil-Framework/Veil-Evasion#396]
## Veil-Evasion version

the latest one
## OS Used - all info (architecture, linux flavor, etc)

Ubuntu 16.04, x86
## Pastebin link to error you are encountering (include console actions you took prior to error)

[!] ERROR: Unable to create output file.

 [!] Internal error #2. Unable to generate output. Please run /home/XXXX/Veil-Evasion/config/update.py manually
## Expected behavior

It should generate the .exe
## Any additional info you want to tell me

It happens every time I try to generate .exe payloads. Doesn't matter whether I use Ruby or Python payloads, it happens all the time. I don't know why it isn't working, I was trying to fix it for like 5 hours and I didn't succeed.

**Comment by ChrisTruncer** [comment]
Did you run the update file?

**Comment by xeq** [comment]
Yes, I did and it still didn't work.

**Comment by ChrisTruncer** [comment]
You may have to go into the code and remove that exception to get the actual error. Based on the information in here I don't have enough info to tell you what the issue is.

**Comment by iliaselmatani** [comment]
Can reproduce this issue. The exception is:
   ```
 from PyInstaller.__main__ import run
  File "Z:\opt\veil\PyInstaller-3.2\PyInstaller\__main__.py", line 21, in <module>
    import PyInstaller.building.build_main
  File "Z:\opt\veil\PyInstaller-3.2\PyInstaller\building\build_main.py", line 32, in <module>
    from ..depend import bindepend
  File "Z:\opt\veil\PyInstaller-3.2\PyInstaller\depend\bindepend.py", line 38, in <module>
    from ..utils.win32.winmanifest import RT_MANIFEST
  File "Z:\opt\veil\PyInstaller-3.2\PyInstaller\utils\win32\winmanifest.py", line 97, in <module>
    from PyInstaller.utils.win32 import winresource
  File "Z:\opt\veil\PyInstaller-3.2\PyInstaller\utils\win32\winresource.py", line 20, in <module>
    import pywintypes
  File "C:\Python27\lib\site-packages\win32\lib\pywintypes.py", line 124, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Python27\lib\site-packages\win32\lib\pywintypes.py", line 98, in __import_pywin32_system_module__
    raise ImportError("No system module '%s' (%s)" % (modname, filename))
ImportError: No system module 'pywintypes' (pywintypes27.dll)
```

**Comment by ChrisTruncer** [comment]
if you just run ./setup.sh on your system, or a clean install, does it work after the install?

**Comment by xeq** [comment]
No

**Comment by ChrisTruncer** [comment]
Can you please remove the exception and paste the error that is shown?

**Comment by xeq** [comment]
it doesn't really create any files, there's no exception in supportfiles. It just says "unable to generate file". Idk why. It doesn't work for ruby and python

**Comment by ChrisTruncer** [comment]
You need to comment out the exception in the Veil-Evasion code where that error is happening so we can see the real error.  Without doing this, I can't help just because I won't have the information about what the error is.

**Comment by ChrisTruncer** [comment]
Closing since I haven't heard back.
