### ISSUE TITLE
ERROR] Unable to determine OS information. Exiting...

### ISSUE THREAD

**Issue by ndemon** [Veil-Framework/Veil-Evasion#399]
Whenever I run setup.sh I get 
[ ERROR] Unable to determine OS information. Exiting...
## Veil-Evasion version

Not installed yet
## OS Used - all info (architecture, linux flavor, etc)

Architecture: 64 bit
Flavor: Arch Linux
Kernel: Linux 4.8.2-1-ARCH
## Pastebin link to error you are encountering (include console actions you took prior to error)

http://pastebin.com/AhpP0XBY
## Expected behavior

I Expected it to install
## Any additional info you want to tell me

The Veil-Framework Install.sh doesnt work either.

**Comment by ChrisTruncer** [comment]
Arch linux isn't a supported distro for Veil-Evasion.
