### ISSUE TITLE
Cannot Installing Veil-Evasion

### ISSUE THREAD

**Issue by arekik6** [Veil-Framework/Veil-Evasion#401]
## Veil-Evasion version

Latest
## OS Used - all info (architecture, linux flavor, etc)

Kali Linux x64
## Pastebin link to error you are encountering (include console actions you took prior to error)

http://pastebin.com/XjZi2iRv

**Comment by ChrisTruncer** [comment]
Your wine install failed.  Please just try again, or change the repos you are using.
