### ISSUE TITLE
Get error in the installation with kali linux last version.

### ISSUE THREAD

**Issue by Omardavinci** [Veil-Framework/Veil-Evasion#405]
Get error in the installation with kali linux last version.

E: No se ha podido localizar el paquete mingw-w64
E: El paquete «monodoc-browser» no tiene un candidato para la instalación
E: No se ha podido localizar el paquete golang
 [ERROR] Failed to install dependencies... Exit code: 100

Leyendo lista de paquetes... Hecho
Creando árbol de dependencias  
Leyendo la información de estado... Hecho
metasploit-framework ya está en su versión más reciente (4.12.22-0kali1).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.

 [*] Installing Capstone dependencies...
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias  
Leyendo la información de estado... Hecho
python-capstone ya está en su versión más reciente (3.0.4-0.2).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.

 [*] Initializing Python dependencies installation...

 [_] Installing Python's SymmetricJSONRPC...
 [_] Installing SymmetricJSONRPC dependency (via Repository)
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias  
Leyendo la información de estado... Hecho
E: No se ha podido localizar el paquete python-symmetric-jsonrpc
 [ERROR] Failed to install SymmetricJSONRPC... Exit code: 100

**Comment by ChrisTruncer** [comment]
You are using a bad/old repo.  Please change your repos as your system can't find the required packages.
