### ISSUE TITLE
Issue with Python auto installer 

### ISSUE THREAD

**Issue by N-Komodo** [Veil-Framework/Veil-Evasion#407]
## Expected behavior - Installs Python like its supposed to.

**Comment by N-Komodo** [comment]
Right, I've established that the problem is to due with my version of kali being 64-bit, and Veil wants wine 32-bit (Python installer not booting correctly), resulting in a bit miss-match. But, my CPU doesn't have PAE so it cant run Kali 32-bit. Help please!

**Comment by ChrisTruncer** [comment]
It requires 32 bit wine.  If that isn't installed, Veil-Evasion won't work.

**Comment by N-Komodo** [comment]
Except 32 bit wine isn't an available package on 64-bit Kali.

**Comment by ChrisTruncer** [comment]
It is, I have it running on Kali and Debian.  Please try changing the repos you are using then.

**Comment by N-Komodo** [comment]
From tutorials I have seen, none are required. Could you also provide me with the Repos required? I'm not too good with Linux.
