### ISSUE TITLE
Failed To install Ruby.exe and Bad Hash Go

### ISSUE THREAD

**Issue by Elsha3r** [Veil-Framework/Veil-Evasion#412]
## Veil-Evasion version

 Veil-Evasion | [Version]: 2.28.2

## OS Used - all info (architecture, linux flavor, etc)
Kali 2016.2
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

## Pastebin link to error you are encountering (include console actions you took prior to error)
 $/root/Veil-Evasion/setup/setup.sh -c
Failed to install (Wine) Ruby.exe... Exit code: 1
Failed to install (Wine) Ruby OCRA Gem... Exit code: 2
Bad hash for go153x64.tar.gz!

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Can you try re-cloning the repo and installing again?
