### ISSUE TITLE
chris, can you help me to send me the info about public chart which meterpreter can bypass av? please help. appreciated

### ISSUE THREAD

**Issue by ericmcwhite** [Veil-Framework/Veil-Evasion#415]
## Any additional info you want to tell me

**Comment by ericmcwhite** [comment]
Norton AV seem to block all meterpreters. Windows/meterpreter/reverse_tcp and reverse_http reverse_https

**Comment by ChrisTruncer** [comment]
https://docs.google.com/spreadsheets/d/1GkNmPkaPrHevO0tHnc-W_xctBNWtnL3LaQIeejTNX6U/edit?usp=drive_web
