### ISSUE TITLE
Fresh install from git clone has errors - ...couldn't get IPSFactory buffer for interface...

### ISSUE THREAD

**Issue by infosecwriter** [Veil-Framework/Veil-Evasion#417]
## Any additional info you want to tell me

I've completely removed the Veil-Evasion and /root/.config/wine/veil, then retried.  Every time it happens.

Always comes up with the same results:::
-------------------------------------
[*] Installing Capstone dependencies...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-capstone is already the newest version (3.0.4-0.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

 [*] Initializing Python dependencies installation...

 [*] Installing Python's SymmetricJSONRPC...
 [*] Installing SymmetricJSONRPC dependency (via Repository)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  python-symmetric-jsonrpc
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 11.2 kB of archives.
After this operation, 64.5 kB of additional disk space will be used.
Get:1 http://kali.localmsp.org/kali kali-rolling/main amd64 python-symmetric-jsonrpc all 0.1-0kali2 [11.2 kB]
Fetched 11.2 kB in 0s (13.1 kB/s)                    
Selecting previously unselected package python-symmetric-jsonrpc.
(Reading database ... 404958 files and directories currently installed.)
Preparing to unpack .../python-symmetric-jsonrpc_0.1-0kali2_all.deb ...
Unpacking python-symmetric-jsonrpc (0.1-0kali2) ...
Setting up python-symmetric-jsonrpc (0.1-0kali2) ...

 [*] Initializing (Wine) Python dependencies installation...

 [*] Preparing (Wine) Python directories...

 [*] Installing (Wine) Python...
 [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.
err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
err:ole:get_local_server_stream Failed: 80004002
err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
err:ole:get_local_server_stream Failed: 80004002
Could not load wine-gecko. HTML rendering will be disabled.
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/root/.config/wine/veil' has been updated.
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot

 [*] Installing (Wine) Python dependencies...

 [*] Installing (Wine) Python's pywin32-219.win32-py2.7.exe...
warning [pywin32-219.win32-py2.7.exe]:  196895 extra bytes at beginning or within zipfile
  (attempting to process anyway)

 [*] Installing (Wine) Python's pycrypto-2.6.win32-py2.7.exe...
warning [pycrypto-2.6.win32-py2.7.exe]:  196629 extra bytes at beginning or within zipfile
  (attempting to process anyway)

 [*] Installing Python's PyInstaller

 [*] Installing Python's PEFile (For PyInstaller)
C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build\lib
copying pefile.py -> build\lib
copying peutils.py -> build\lib
creating build\lib\ordlookup
copying ordlookup\ws2_32.py -> build\lib\ordlookup
copying ordlookup\__init__.py -> build\lib\ordlookup
copying ordlookup\oleaut32.py -> build\lib\ordlookup
running install_lib
copying build\lib\peutils.py -> C:\Python27\Lib\site-packages
copying build\lib\pefile.py -> C:\Python27\Lib\site-packages
creating C:\Python27\Lib\site-packages\ordlookup
copying build\lib\ordlookup\ws2_32.py -> C:\Python27\Lib\site-packages\ordlookup
copying build\lib\ordlookup\__init__.py -> C:\Python27\Lib\site-packages\ordlookup
copying build\lib\ordlookup\oleaut32.py -> C:\Python27\Lib\site-packages\ordlookup
byte-compiling C:\Python27\Lib\site-packages\peutils.py to peutils.pyc
byte-compiling C:\Python27\Lib\site-packages\pefile.py to pefile.pyc
byte-compiling C:\Python27\Lib\site-packages\ordlookup\ws2_32.py to ws2_32.pyc
byte-compiling C:\Python27\Lib\site-packages\ordlookup\__init__.py to __init__.pyc
byte-compiling C:\Python27\Lib\site-packages\ordlookup\oleaut32.py to oleaut32.pyc
running install_egg_info
Writing C:\Python27\Lib\site-packages\pefile-2016.3.28-py2.7.egg-info

**Comment by ChrisTruncer** [comment]
I just installed this from Git and haven't run into an issue, can you try again?
