### ISSUE TITLE
E: Package 'wine' has no installation candidate

### ISSUE THREAD

**Issue by leesoh** [Veil-Framework/Veil-Evasion#421]
## Veil-Evasion version
2.28.2

## OS Used - all info (architecture, linux flavor, etc)
Ubuntu 16.10

## Pastebin link to error you are encountering (include console actions you took prior to error)
```
[*] Installing Wine 32-bit and 64-bit binaries
E: Package 'wine' has no installation candidate
[ERROR] Failed to install Wine... Exit code: 100
```

## Expected behavior
Wine completes

## Any additional info you want to tell me
This looks to be caused by a renaming of the `wine` package to `wine-stable`. Because of this mismatch, each apt trying to install Wine fails, including the large one on line [281](https://github.com/Veil-Framework/Veil-Evasion/blob/master/setup/setup.sh#L281) Manually modifying the `setup.sh` file to replace instances of `wine` with `wine-stable` resolved the issue and let the installation continue.

It would be an easy PR, but I wasn't sure whether any of the other distros lumped in that if statement had the same name change so I figured I'd just open an issue.

**Comment by ChrisTruncer** [comment]
thanks for this info, I will get a change merged in!

**Comment by ChrisTruncer** [comment]
This should now be fixed.  Thanks
