### ISSUE TITLE
awk: fatal: tent of \{\}: /[:-.]/

### ISSUE THREAD

**Issue by leesoh** [Veil-Framework/Veil-Evasion#422]
## Veil-Evasion version
2.28.2

## OS Used - all info (architecture, linux flavor, etc)
Ubuntu 16.10

## Pastebin link to error you are encountering (include console actions you took prior to error)
```
 [*] Initializing Go dependencies installation...

awk: fatal: tent of \{\}: /[:-.]/
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gccgo-5 is already the newest version (5.4.1-2ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
update-alternatives: error: no alternatives for go
```

## Expected behavior
No errors!

## Any additional info you want to tell me
Just got this while re-running `setup.sh` as root (sudo su -)

**Comment by leesoh** [comment]
Found the issue [here](https://github.com/Veil-Framework/Veil-Evasion/blob/master/setup/setup.sh#L545). On Ubuntu, this is what the output of `apt-cache show golang-src` looks like:

```
Package: golang-src
Priority: optional
Section: devel
Installed-Size: 11
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Go Compiler Team <pkg-golang-devel@lists.alioth.debian.org>
Architecture: amd64
Source: golang-defaults
Version: 2:1.6.1+1ubuntu2
Depends: golang-1.6-src
Filename: pool/main/g/golang-defaults/golang-src_1.6.1+1ubuntu2_amd64.deb
Size: 3352
MD5sum: 59bbac0a64062f8cb28cebe9c74f7670
SHA1: 5c53bf3eac19e81a37c1516816416c1ce4709ed7
SHA256: 9dfde383eb591c91a223dfabfa66693121922d1b2e9dcebc1df0e372a7f494aa
Description-en: Go programming language - source files
 The Go programming language is an open source project to make programmers more
 productive. Go is expressive, concise, clean, and efficient. Its concurrency
 mechanisms make it easy to write programs that get the most out of multicore
 and networked machines, while its novel type system enables flexible and
 modular program construction. Go compiles quickly to machine code yet has the
 convenience of garbage collection and the power of run-time reflection. It's a
 fast, statically typed, compiled language that feels like a dynamically typed,
 interpreted language.
 .
 This is a dependency package that depends on the default Go standard library
 source code, which is needed for the go build process.
Description-md5: 4f562b95d873fbeb7b702f869c5413db
Homepage: https://golang.org
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 9m
```

I'm guessing something changed in the syntax of Version at some point and the ":" in the string is screwing things up, but the later comparison to "12" threw me for a loop so I wasn't sure how to fix.

Hope this is useful.

**Comment by ChrisTruncer** [comment]
Sorry, I've specifically tried installing this last night on Ubuntu 16.10.  I built out a VM but I cannot get this error to trigger.

**Comment by leesoh** [comment]
Weird. If I paste that line in question, I get it every time. Does your `apt-cache show golang-src` look like mine?

**Comment by ChrisTruncer** [comment]
yeah, that looks exactly the same

**Comment by leesoh** [comment]
What does your output of `apt-cache show golang-src | awk -F '[:-.]' '/Version/ {print $3$4}'` look like?
`

**Comment by ChrisTruncer** [comment]
16

**Comment by leesoh** [comment]
Ahhh, the version number is making sense to me now, but super strange that I'm having problems and you're not.

**Comment by leesoh** [comment]
OK, I was rearranging things in the awk delims and this spits out a 16: `apt-cache show golang-src | awk -F '[.:-]' '/Version/{print $3$4}'`

The only thing I did was rearrange the delimiters.

**Comment by ChrisTruncer** [comment]
hm... I'm not sure either to be honest

**Comment by ChrisTruncer** [comment]
Well, I wish I could give more info on this, sorry I can't come up with the same results.  Unless there's anything else to bring up, I'm going to close this out.

**Comment by fenech** [comment]
I just stumbled across this thread...`[.:-]` is a valid bracket expression containing three characters, whereas the `-` in the middle of `[:-.]` is interpreted as the range of characters between `:` and `.`. `-` Should always go at the start or end of a bracket expression for this reason.

**Comment by ChrisTruncer** [comment]
Hey, I'm closing this issue since this is no longer a problem in Veil 3.0
