### ISSUE TITLE
ERROR: Can't find python.exe

### ISSUE THREAD

**Issue by malek234** [Veil-Framework/Veil-Evasion#427]
veil-evasion version 2.28.1
distro: Linux parrot 4.6.0
[!] ERROR: Can't find python.exe in /home/malek/.config/wine/veil/drive_c/Python27/
 [!] ERROR: Make sure the python.exe binary exists before using PyInstaller.

![screenshot at 2016-12-22 16-07-41](https://cloud.githubusercontent.com/assets/22845316/21412467/0cdfaa8a-c79d-11e6-9954-d6c5bebc2080.png)

![screenshot at 2016-12-22 16-08-12](https://cloud.githubusercontent.com/assets/22845316/21412480/21280690-c79d-11e6-97cf-9d2ba87cef5a.png)

this is very important to me
Because all another tools not good

**Comment by ChrisTruncer** [comment]
I don't support parrot, but the main thing you need to do is run the setup script.

**Comment by malek234** [comment]
I do that before and I install Veil it do this when I want to generate a payload from python all another payloads works.

if you do not know how solve this problem, tell me about another tools to encrypted payloads.
or scripts can do that
