### ISSUE TITLE
VEIL-EVASION Won't Install

### ISSUE THREAD

**Issue by hyzo90** [Veil-Framework/Veil-Evasion#428]
## Veil-Evasion version
2.28.2

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux Rolling 2016.2

## Pastebin link to error you are encountering (include console actions you took prior to error)

![veil](https://cloud.githubusercontent.com/assets/24711785/21449572/fbd6ae6e-c931-11e6-8a95-f549a725b9eb.jpg)

## Any additional info you want to tell me

Waited for 1-2 hours. Stuck like that. Won't install it

**Comment by ChrisTruncer** [comment]
It's downloading the packages in the background.  You might have a slow connection to the mirrors you are using.
