### ISSUE TITLE
Elementary os, based on ubuntu 16.04

### ISSUE THREAD

**Issue by Kajpio** [Veil-Framework/Veil-Evasion#431]
## Veil-Evasion version
last

## OS Used - all info (architecture, linux flavor, etc)
elementary os 0.4

## Pastebin link to error you are encountering (include console actions you took prior to error)
just installing, and the script couldn't find the os

## Any additional info you want to tell me
hi,
I know that is not an issue (and that elementary os is not supported ! :1st_place_medal:  ), but I was trying to install Veil, but I couldn't due to the fact that I'm on elementary but elementary os is using ubuntu repos. So I think that it could work. 
I tried editing the script but I didn't not find a way to install it.
Thanks in advance for the help !
Kajpio

**Comment by ChrisTruncer** [comment]
Elementary OS isn't supported, so I can't say whether or not it would work on it.  Closest thing is you'll want to look at line 9 in the setup script, and find what it is doing for your distro to replace it further down in the setup script.  At that point, it would be testing and seeing if the setup completes.
