### ISSUE TITLE
Veil evasion on Kali linux problem

### ISSUE THREAD

**Issue by stg1213** [Veil-Framework/Veil-Evasion#432]
I'm trying to install veil on my virtual machine Kali linux. When I get to the part where the setup uses wine to open the python page in order to install veil, I pressed yes. Than after, a page that would check what directory you want to use comes up. When I press on next it doesn't do anything or move to another page, just nothing. Can anybody please help????

**Comment by ChrisTruncer** [comment]
Please follow the outline when submitting Github issues.

I've seen that this has impacted a really small number of users, but I can't recreate this.  I've installed Veil in multiple distros and have yet to encounter this error.

For the best installation process, please follow the readme and clone the tool from Github.
