### ISSUE TITLE
Can't install Python

### ISSUE THREAD

**Issue by Thenen** [Veil-Framework/Veil-Evasion#434]
## Veil-Evasion version
2.28.2

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2.0 x64

## Pastebin link to error you are encountering (include console actions you took prior to error)
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:msi:ITERATE_Actions Execution halted, action L"SelectDirectoryDlg" returned 1602
 [ERROR] Failed to install (Wine) Python 2.7.5... Exit code: 66

## Expected behavior
When I try to click "next" while during the installation of Python, literally nothing happens. I have tried different solutions from the Internet, but so far nothing has worked for me.

## Any additional info you want to tell me
Kali is my second OS. I have Windows installed on my primary Drive C:\ and Kali on a partition of my secondary Drive K:\. Maybe this helps solving the problem.

**Comment by ChrisTruncer** [comment]
I wish I could recreate this, but I can't seem to make it happen.  I've tested on Debian, Kali, and Ubuntu, and I'm able to install Python on all of them.

**Comment by ChrisTruncer** [comment]
Can you give any more info?

**Comment by dinaosama91** [comment]
I have the same issue. I tried to install Veil on Kali linux 2016.2 , amd64 and when it comes to installing python 2.7.5 , I click next but nothing happens

**Comment by mk80** [comment]
I am getting the same thing. I do have wine64 installed as wine32 is not available.

more info here: [http://pastebin.com/9KQ7benQ](url)

**Comment by ChrisTruncer** [comment]
@mk80 - are you running as root or sudo?

**Comment by mk80** [comment]
root...should i be sudo?

**Comment by ChrisTruncer** [comment]
try sudo, but root should work

**Comment by mk80** [comment]
Same issue. I make it to the Python 2.7.5 Select Destination Directory. The Python27 folder is already populated but when you click next nothing happens. The cancel button does cancel though.

**Comment by ChrisTruncer** [comment]
I really don't know how to fix that.  Not sure if it's an odd issue with wine, or a bug in it.  There's no code behind this besides just using msiexec to install the msi file (Python).

**Comment by mk80** [comment]
i figured it was something local since it is just not allowing me to proceed...just thought i would check here...i will continue to work it out...once i figure something out i will post it here...thank you

**Comment by ChrisTruncer** [comment]
Yes, I would absolutely love if you can figure it out.  I'm installing kali as we speak to check.  I wish there was more to offer, but it's just a simple install one liner - https://github.com/Veil-Framework/Veil-Evasion/blob/master/setup/setup.sh#L415

**Comment by Thenen** [comment]
It works fine on my Notebook with 32bit Kali, but Still not running on 64 bit.

**Comment by ChrisTruncer** [comment]
So, I literally just pulled a brand new Kali x64 iso (latest version) and installed it in a VM.  After updating it, I cloned Veil-Evasion from git, and installed it.  It installed perfectly, and didn't hang up anywhere.  I generated a test payload just to make sure it was successful, and it worked.

I wish I could help further troubleshoot this, but even pulling a fresh/clean iso and installing it doesn't seem to throw the error

**Comment by mk80** [comment]
yea..i might just remake the vm...thank you for taking the time..

**Comment by Thenen** [comment]
How did you update it? With wich command?

**Comment by Thenen** [comment]
Got it working, after typing "apt-get install kali-linux-all" in the terminal. Thank you guys a lot for your time and your help. @mk80 I hope this works for you too. If not, feel free to tell me so, maybe I we can find a different solution for you :D

**Comment by ChrisTruncer** [comment]
ok, I'm going to close this out, but leave it available for everyone to continue the discussion if needed
