### ISSUE TITLE
Veil-Evasion (Payload Icon Not Changing)

### ISSUE THREAD

**Issue by ibrahimnezar** [Veil-Framework/Veil-Evasion#435]
## Veil-Evasion version
Version 2.28.2

## OS Used - all info (architecture, linux flavor, etc)
Linux kali 4.6.0-kali1-686 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) i686 GNU/Linux

## Pastebin link to error you are encountering (include console actions you took prior to error)
There is not error during the generation of the payload, but the resulted payload does not includ the custom icon from the default icons folder /root/Veil-Evasion/modules/common/source/icons

I just followed the normal procedures to generate the payload using pwnstaller option (2), check below pastebin are the steps I implemented:

http://pastebin.com/VVGVmSzY

## Expected behavior
Replace the default payload icon with a random icon when using pwnstaller

## Any additional info you want to tell me
The icon is not changing even if I remove the default icons from the /root/Veil-Evasion/modules/common/source/icons folder and add new icons or put only one icon just as a troubleshooting steps.

**Comment by ChrisTruncer** [comment]
Hi,

This isn't something that I plan on supporting.  It's very limited in nature and doesn't impact the overall project.  If you are able to get this working, feel free to post in here how it is done.

Thanks
