### ISSUE TITLE
python/meterpreter/rev_tcp (Internal error #2)

### ISSUE THREAD

**Issue by n0mn0m** [Veil-Framework/Veil-Evasion#437]
## Veil-Evasion version
2.28.2

## OS Used - all info (architecture, linux flavor, etc)
Linux kali 4.8.0-kali2-amd64 #1 SMP Debian 4.8.15-1kali1 (2016-12-23) x86_64 GNU/Linux

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/n3Ctdrbr

## Any additional info you want to tell me

Well i tried to follow the instruction for run update.py manually, but still got the same error here.
I want to create malware with architecture 64 using "python/meterpreter/rev_tcp" with pyinstaller.
What i missed?

**Comment by ChrisTruncer** [comment]
So, unless you have 64 bit wine installed with 64 bit python and the required 64 bit libraries, it won't work.  That process Veil does not automate during the setup steps.  You would need to manually install it yourself.

Veil can output the source code that you could then convert into an executable, but it just won't make the x64 exe itself.
