### ISSUE TITLE
[question] Use a compiled executable as a payload to generate powershell output

### ISSUE THREAD

**Issue by valerianrossigneux** [Veil-Framework/Veil-Evasion#444]
Hi, I'm probably missing something obvious but how can I generate a powershell payload that will take my already compiled binary and execute it e.g. calc.exe.
(and subsequently use macrosafe to generate a friendly output to be embbeded in a word document)
Thanks

**Comment by veil-evasion** [comment]
Veil itself doesn't do that. It would be faster to have you write a PowerShell script to do that.
