### ISSUE TITLE
Veil-Evasion Error

### ISSUE THREAD

**Issue by Al2x** [Veil-Framework/Veil-Evasion#445]
## Veil-Evasion version
2.28.2

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/bvk6HEcz

## Expected behavior
Just want to make what do the guy in the video : https://www.youtube.com/watch?v=3WPoD8F5V64

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Please search for the error, this has been answered a large number of times.

Run the update.py script
