### ISSUE TITLE
Internal error #2. Unable to generate output. Please run /root/Desktop/veil/Veil-Evasion/config/update.py manually

### ISSUE THREAD

**Issue by hackituria** [Veil-Framework/Veil-Evasion#447]
## Veil-Evasion version
2.28.2

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux Versión 3.21.90

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/kxctGVdH

## Expected behavior
Python payload, with PYHERION , generation

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Can you try running the update script like it says?

**Comment by hackituria** [comment]
yes, but the error persists

**Comment by ChrisTruncer** [comment]
You'll need to comment out the try except and get the true error, and then let me know what it says, then I can help.

**Comment by hackituria** [comment]
I think it was a failed installation because i reinstalled it and now i can use it without problems.
