### ISSUE TITLE
Wine Errors Captured - Output attached 

### ISSUE THREAD

**Issue by sma92878** [Veil-Framework/Veil-Evasion#450]
## Any additional info you want to tell me

**Comment by sma92878** [comment]
Selecting previously unselected package libgstreamer0.10-0:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 251257 files and directories currently installed.)
Preparing to unpack .../libgstreamer0.10-0_0.10.36-1.5ubuntu1_amd64.deb ...
Unpacking libgstreamer0.10-0:amd64 (0.10.36-1.5ubuntu1) ...
Selecting previously unselected package libgstreamer-plugins-base0.10-0:amd64.
Preparing to unpack .../libgstreamer-plugins-base0.10-0_0.10.36-2_amd64.deb ...
Unpacking libgstreamer-plugins-base0.10-0:amd64 (0.10.36-2) ...
Selecting previously unselected package libmpg123-0:amd64.
Preparing to unpack .../libmpg123-0_1.22.4-1_amd64.deb ...
Unpacking libmpg123-0:amd64 (1.22.4-1) ...
Selecting previously unselected package libopenal1:amd64.
Preparing to unpack .../libopenal1_1%3a1.16.0-3_amd64.deb ...
Unpacking libopenal1:amd64 (1:1.16.0-3) ...
Preparing to unpack .../wine1.8-amd64_1%3a1.8.0-0ubuntu1~ubuntu15.10.1~ppa1_amd64.deb ...
Unpacking wine1.8-amd64 (1:1.8.0-0ubuntu1~ubuntu15.10.1~ppa1) ...
Selecting previously unselected package libglib2.0-0:i386.
Preparing to unpack .../libglib2.0-0_2.48.2-0ubuntu1_i386.deb ...
Unpacking libglib2.0-0:i386 (2.48.2-0ubuntu1) ...
Selecting previously unselected package libexif12:i386.
Preparing to unpack .../libexif12_0.6.21-2_i386.deb ...
Unpacking libexif12:i386 (0.6.21-2) ...
Selecting previously unselected package libvpx3:i386.
Preparing to unpack .../libvpx3_1.5.0-2ubuntu1_i386.deb ...
Unpacking libvpx3:i386 (1.5.0-2ubuntu1) ...
Selecting previously unselected package libxpm4:i386.
Preparing to unpack .../libxpm4_1%3a3.5.11-1ubuntu0.16.04.1_i386.deb ...
Unpacking libxpm4:i386 (1:3.5.11-1ubuntu0.16.04.1) ...
Selecting previously unselected package libgd3:i386.
Preparing to unpack .../libgd3_2.1.1-4ubuntu0.16.04.5_i386.deb ...
Unpacking libgd3:i386 (2.1.1-4ubuntu0.16.04.5) ...
Selecting previously unselected package libusb-1.0-0:i386.
Preparing to unpack .../libusb-1.0-0_2%3a1.0.20-1_i386.deb ...
Unpacking libusb-1.0-0:i386 (2:1.0.20-1) ...
Selecting previously unselected package libgphoto2-port12:i386.
Preparing to unpack .../libgphoto2-port12_2.5.9-3_i386.deb ...
Unpacking libgphoto2-port12:i386 (2.5.9-3) ...
Selecting previously unselected package libgphoto2-6:i386.
Preparing to unpack .../libgphoto2-6_2.5.9-3_i386.deb ...
Unpacking libgphoto2-6:i386 (2.5.9-3) ...
Selecting previously unselected package libgstreamer0.10-0:i386.
Preparing to unpack .../libgstreamer0.10-0_0.10.36-1.5ubuntu1_i386.deb ...
Unpacking libgstreamer0.10-0:i386 (0.10.36-1.5ubuntu1) ...
Selecting previously unselected package liborc-0.4-0:i386.
Preparing to unpack .../liborc-0.4-0_1%3a0.4.25-1_i386.deb ...
Unpacking liborc-0.4-0:i386 (1:0.4.25-1) ...
Selecting previously unselected package libgstreamer-plugins-base0.10-0:i386.
Preparing to unpack .../libgstreamer-plugins-base0.10-0_0.10.36-2_i386.deb ...
Unpacking libgstreamer-plugins-base0.10-0:i386 (0.10.36-2) ...
Processing triggers for libc-bin (2.23-0ubuntu5) ...
Processing triggers for libglib2.0-0:amd64 (2.48.2-0ubuntu1) ...
Processing triggers for udev (229-4ubuntu16) ...
dpkg: wine-stable: dependency problems, but removing anyway as you requested:
 winetricks depends on wine; however:
  Package wine is not installed.
  Package wine1.6 which provides wine is not installed.
  Package wine1.8 which provides wine is not installed.
  Package wine-stable which provides wine is to be removed.

(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 252922 files and directories currently installed.)
Removing wine-stable (1.8.6-3ubuntu2~16.04.york0) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Selecting previously unselected package wine.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 252876 files and directories currently installed.)
Preparing to unpack .../wine_1%3a1.8.0-0ubuntu1~ubuntu15.10.1~ppa1_amd64.deb ...
Unpacking wine (1:1.8.0-0ubuntu1~ubuntu15.10.1~ppa1) ...
Preparing to unpack .../wine1.8-i386_1%3a1.8.0-0ubuntu1~ubuntu15.10.1~ppa1_i386.deb ...
Unpacking wine1.8-i386:i386 (1:1.8.0-0ubuntu1~ubuntu15.10.1~ppa1) ...
dpkg: error processing archive /var/cache/apt/archives/wine1.8-i386_1%3a1.8.0-0ubuntu1~ubuntu15.10.1~ppa1_i386.deb (--unpack):
 trying to overwrite '/usr/lib/i386-linux-gnu/wine/regsvcs.exe.so', which is also in package libwine:i386 1.8.6-3ubuntu2~16.04.york0
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Preparing to unpack .../wine1.8_1%3a1.8.0-0ubuntu1~ubuntu15.10.1~ppa1_amd64.deb ...
Unpacking wine1.8 (1:1.8.0-0ubuntu1~ubuntu15.10.1~ppa1) ...
dpkg: error processing archive /var/cache/apt/archives/wine1.8_1%3a1.8.0-0ubuntu1~ubuntu15.10.1~ppa1_amd64.deb (--unpack):
 trying to overwrite '/usr/share/wine/fonts/ssee1257.fon', which is also in package fonts-wine 1.8.6-3ubuntu2~16.04.york0
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package fonts-horai-umefont.
Preparing to unpack .../fonts-horai-umefont_590-1_all.deb ...
Unpacking fonts-horai-umefont (590-1) ...
Selecting previously unselected package fonts-unfonts-core.
Preparing to unpack .../fonts-unfonts-core_1.0.3.is.1.0.2-080608-10ubuntu1_all.deb ...
Unpacking fonts-unfonts-core (1.0.3.is.1.0.2-080608-10ubuntu1) ...
Selecting previously unselected package libgsm1:amd64.
Preparing to unpack .../libgsm1_1.0.13-4_amd64.deb ...
Unpacking libgsm1:amd64 (1.0.13-4) ...
Selecting previously unselected package libice6:i386.
Preparing to unpack .../libice6_2%3a1.0.9-1_i386.deb ...
Unpacking libice6:i386 (2:1.0.9-1) ...
Selecting previously unselected package libieee1284-3:i386.
Preparing to unpack .../libieee1284-3_0.2.11-12_i386.deb ...
Unpacking libieee1284-3:i386 (0.2.11-12) ...
Selecting previously unselected package libsm6:i386.
Preparing to unpack .../libsm6_2%3a1.2.2-1_i386.deb ...
Unpacking libsm6:i386 (2:1.2.2-1) ...
Selecting previously unselected package libcapi20-3:i386.
Preparing to unpack .../libcapi20-3_1%3a3.27-1_i386.deb ...
Unpacking libcapi20-3:i386 (1:3.27-1) ...
Selecting previously unselected package libcapi20-3:amd64.
Preparing to unpack .../libcapi20-3_1%3a3.27-1_amd64.deb ...
Unpacking libcapi20-3:amd64 (1:3.27-1) ...
Selecting previously unselected package fonts-wqy-microhei.
Preparing to unpack .../fonts-wqy-microhei_0.2.0-beta-2_all.deb ...
Unpacking fonts-wqy-microhei (0.2.0-beta-2) ...
Selecting previously unselected package icoutils.
Preparing to unpack .../icoutils_0.31.0-3_amd64.deb ...
Unpacking icoutils (0.31.0-3) ...
Selecting previously unselected package libodbc1:amd64.
Preparing to unpack .../libodbc1_2.3.1-4.1_amd64.deb ...
Unpacking libodbc1:amd64 (2.3.1-4.1) ...
Selecting previously unselected package libsane:i386.
Preparing to unpack .../libsane_1.0.25+git20150528-1ubuntu2_i386.deb ...
Unpacking libsane:i386 (1.0.25+git20150528-1ubuntu2) ...
Selecting previously unselected package libv4lconvert0:i386.
Preparing to unpack .../libv4lconvert0_1.10.0-1_i386.deb ...
Unpacking libv4lconvert0:i386 (1.10.0-1) ...
Selecting previously unselected package libv4l-0:i386.
Preparing to unpack .../libv4l-0_1.10.0-1_i386.deb ...
Unpacking libv4l-0:i386 (1.10.0-1) ...
Selecting previously unselected package libwine:amd64.
Preparing to unpack .../libwine_1.8.6-3ubuntu2~16.04.york0_amd64.deb ...
Unpacking libwine:amd64 (1.8.6-3ubuntu2~16.04.york0) ...
dpkg: error processing archive /var/cache/apt/archives/libwine_1.8.6-3ubuntu2~16.04.york0_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/wine/xaudio2_3.dll.so', which is also in package wine1.8-amd64 1:1.8.0-0ubuntu1~ubuntu15.10.1~ppa1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package libxt6:i386.
Preparing to unpack .../libxt6_1%3a1.1.5-0ubuntu1_i386.deb ...
Unpacking libxt6:i386 (1:1.1.5-0ubuntu1) ...
Selecting previously unselected package odbcinst1debian2:amd64.
Preparing to unpack .../odbcinst1debian2_2.3.1-4.1_amd64.deb ...
Unpacking odbcinst1debian2:amd64 (2.3.1-4.1) ...
Selecting previously unselected package odbcinst.
Preparing to unpack .../odbcinst_2.3.1-4.1_amd64.deb ...
Unpacking odbcinst (2.3.1-4.1) ...
Selecting previously unselected package ttf-wqy-microhei.
Preparing to unpack .../ttf-wqy-microhei_0.2.0-beta-2_all.deb ...
Unpacking ttf-wqy-microhei (0.2.0-beta-2) ...
Selecting previously unselected package unixodbc.
Preparing to unpack .../unixodbc_2.3.1-4.1_amd64.deb ...
Unpacking unixodbc (2.3.1-4.1) ...
Selecting previously unselected package wine64.
Preparing to unpack .../wine64_1.8.6-3ubuntu2~16.04.york0_amd64.deb ...
Unpacking wine64 (1.8.6-3ubuntu2~16.04.york0) ...
Selecting previously unselected package gnome-exe-thumbnailer.
Preparing to unpack .../gnome-exe-thumbnailer_0.9.3-2_all.deb ...
Unpacking gnome-exe-thumbnailer (0.9.3-2) ...
Selecting previously unselected package libosmesa6:amd64.
Preparing to unpack .../libosmesa6_12.0.6-0ubuntu0.16.04.1_amd64.deb ...
Unpacking libosmesa6:amd64 (12.0.6-0ubuntu0.16.04.1) ...
Selecting previously unselected package p11-kit-modules:i386.
Preparing to unpack .../p11-kit-modules_0.23.2-5~ubuntu16.04.1_i386.deb ...
Unpacking p11-kit-modules:i386 (0.23.2-5~ubuntu16.04.1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for fontconfig (2.11.94-0ubuntu1.1) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for libc-bin (2.23-0ubuntu5) ...
Errors were encountered while processing:
 /var/cache/apt/archives/wine1.8-i386_1%3a1.8.0-0ubuntu1~ubuntu15.10.1~ppa1_i386.deb
 /var/cache/apt/archives/wine1.8_1%3a1.8.0-0ubuntu1~ubuntu15.10.1~ppa1_amd64.deb
 /var/cache/apt/archives/libwine_1.8.6-3ubuntu2~16.04.york0_amd64.deb

**Comment by sma92878** [comment]
I just did a fresh install of Ubuntu 16.04 with the following as the only modification

apt-get update
apt-get upgrade

**** Files needed for SEToolkit & Metasploit ****
apt-get install python-pip
pip install pycrypto
pip install pexpect
pip install --upgrade pip

**** Installation of Metasploit as found in this guide, include Ruby Modules  ****
http://www.darkoperator.com/installing-metasploit-in-ubunt/

**** Installation of SET as found in this guide  ****
http://askubuntu.com/questions/654461/how-to-start-the-social-engineering-tookit

**** Installation of Veil  ****
git clone https://github.com/Veil-Framework/Veil-Evasion.git

executed /opt/Veil-Evasion/setup/setup.py -c 


**** Output Below ****

root@ubuntu:/opt/Veil-Evasion/setup# ./setup.sh -c
 ==========================================================================
             Veil-Evasion (Setup Script) | [Updated]: 2016-09-09
 ==========================================================================
  [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
 ==========================================================================

 [I] Ubuntu 16 x86_64 detected...



 [*] Initializing package installation


 [*] Adding x86 architecture to x86_64 system for Wine

 [*] Installing Wine 32-bit and 64-bit binaries
E: Unable to locate package wine-stable
 [ERROR] Failed to install Wine... Exit code: 100

 [*] Creating new Veil Wine environment in: /home/saiello/.config/wine/veil
 [*] Initializing Veil's Wine environment...
sudo: wine: command not found
 [ERROR] Veil Wine environment could not be found!

 [ERROR] Check for existence of /home/saiello/.config/wine/veil/drive_c



 [*] Installing dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package wine-stable
 [ERROR] Failed to install dependencies... Exit code: 100


 [*] Installing Capstone dependencies...
 [*] Installing Capstone (via PIP)
Collecting capstone
  Downloading capstone-3.0.4.tar.gz (3.2MB)
    100% |████████████████████████████████| 3.2MB 370kB/s 
Building wheels for collected packages: capstone
  Running setup.py bdist_wheel for capstone ... done
  Stored in directory: /root/.cache/pip/wheels/7c/d1/d0/db6e2c5ef1063aabb9de2dd8b92b4c27ee6f9fd213240099b8
Successfully built capstone
Installing collected packages: capstone
Successfully installed capstone-3.0.4

 [*] Initializing Python dependencies installation...


 [*] Installing Python's SymmetricJSONRPC...
 [*] Installing SymmetricJSONRPC dependency (via PIP)...
Collecting symmetricjsonrpc
  Downloading symmetricjsonrpc-0.1.0.tar.gz
Building wheels for collected packages: symmetricjsonrpc
  Running setup.py bdist_wheel for symmetricjsonrpc ... done
  Stored in directory: /root/.cache/pip/wheels/1d/cc/9a/f007714e99c5ba1ae09173c2fc7a5981cedfbc46cde71770ba
Successfully built symmetricjsonrpc
Installing collected packages: symmetricjsonrpc
Successfully installed symmetricjsonrpc-0.1.0

 [*] Initializing (Wine) Python dependencies installation...

 [*] Preparing (Wine) Python directories...


 [*] Installing (Wine) Python...
 [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.
sudo: wine: command not found
 [ERROR] Failed to install (Wine) Python 2.7.5... Exit code: 1


 [*] Installing (Wine) Python dependencies...


 [*] Installing (Wine) Python's pywin32-219.win32-py2.7.exe...
 [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.
sudo: wine: command not found
 [ERROR] Failed to install pywin32-219.win32-py2.7.exe... Exit code: 1



 [*] Installing (Wine) Python's pycrypto-2.6.win32-py2.7.exe...
 [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.
sudo: wine: command not found
 [ERROR] Failed to install pycrypto-2.6.win32-py2.7.exe... Exit code: 1



 [*] Installing Python's PyInstaller


 [*] Installing Python's PEFile (For PyInstaller)
sudo: wine: command not found


 [*] Installing Python's Futures (For PyInstaller)
sudo: wine: command not found


 [*] Installing Python's setup  tools
sudo: wine: command not found

 [*] Initializing (Wine) Ruby dependencies installation...


 [*] Installing (Wine) Ruby & dependencies
 [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.
sudo: wine: command not found
 [ERROR] Failed to install (Wine) Ruby.exe... Exit code: 1


 [*] Installing (Wine) Ruby OCRA gem...

sudo: wine: command not found
 [ERROR] Failed to install (Wine) Ruby OCRA Gem... Exit code: 1


 [*] Extracting (Wine) Ruby dependencies...

 [*] Initializing Go dependencies installation...

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libpango1.0-0 libpangox-1.0-0
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libgo7
Suggested packages:
  gccgo-5-doc libgo7-dbg
The following NEW packages will be installed:
  gccgo-5 libgo7
0 upgraded, 2 newly installed, 0 to remove and 15 not upgraded.
Need to get 19.5 MB of archives.
After this operation, 107 MB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libgo7 amd64 5.4.0-6ubuntu1~16.04.4 [6,401 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 gccgo-5 amd64 5.4.0-6ubuntu1~16.04.4 [13.1 MB]                                                                                        
Fetched 19.5 MB in 18s (1,060 kB/s)                                                                                                                                                                           
Selecting previously unselected package libgo7:amd64.
(Reading database ... 185131 files and directories currently installed.)
Preparing to unpack .../libgo7_5.4.0-6ubuntu1~16.04.4_amd64.deb ...
Unpacking libgo7:amd64 (5.4.0-6ubuntu1~16.04.4) ...
Selecting previously unselected package gccgo-5.
Preparing to unpack .../gccgo-5_5.4.0-6ubuntu1~16.04.4_amd64.deb ...
Unpacking gccgo-5 (5.4.0-6ubuntu1~16.04.4) ...
Processing triggers for libc-bin (2.23-0ubuntu5) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up libgo7:amd64 (5.4.0-6ubuntu1~16.04.4) ...
Setting up gccgo-5 (5.4.0-6ubuntu1~16.04.4) ...
Processing triggers for libc-bin (2.23-0ubuntu5) ...
update-alternatives: error: no alternatives for go


 [*] Installing Go x86_64 (via TAR)

 [ERROR] Bad hash for go153x64.tar.gz!


 [*] Updating Veil-Framework configuration...

[sudo] password for saiello: 
 [>] Please enter the path of your metasploit installation: /opt/metasploit/apps/pro/msf3

 Veil-Framework configuration:

 [*] OPERATING_SYSTEM = Linux
 [*] TERMINAL_CLEAR = clear
 [*] WINEPREFIX = /home/saiello/.config/wine/veil/
 [*] TEMP_DIR = /tmp/
 [*] MSFVENOM_OPTIONS = 
 [*] METASPLOIT_PATH = /opt/metasploit/apps/pro/msf3
 [*] MSFVENOM_PATH = /opt/metasploit/apps/pro/msf3
 [*] PYINSTALLER_PATH = /opt/veil/PyInstaller-3.2/

 [*] VEIL_EVASION_PATH = /opt/Veil-Evasion/
 [*] PAYLOAD_SOURCE_PATH = /usr/share/veil-output/source/
 [*] Path '/usr/share/veil-output/source/' Created
 [*] PAYLOAD_COMPILED_PATH = /usr/share/veil-output/compiled/
 [*] Path '/usr/share/veil-output/compiled/' Created
 [*] Path '/usr/share/veil-output/handlers/' Created
 [*] GENERATE_HANDLER_SCRIPT = True
 [*] HANDLER_PATH = /usr/share/veil-output/handlers/
 [*] HASH_LIST = /usr/share/veil-output/hashes.txt

 [*] VEIL_CATAPULT_PATH = /opt/Veil-Catapult/
 [*] Path '/usr/share/veil-output/catapult/' Created
 [*] CATAPULT_RESOURCE_PATH = /usr/share/veil-output/catapult/

 [*] Path '/etc/veil/' Created
 Configuration File Written To '/etc/veil/settings.py'


 [*] Ensuring this account (saiello) owns veil output directory (/usr/share/veil-output)...
 [*] Ensuring this account (saiello) has correct ownership of /home/saiello/.config/wine/veil
  There was issues installing the following:

 
Failed to install Wine... Exit code: 100
Veil Wine environment could not be found!
Check for existence of /home/saiello/.config/wine/veil/drive_c
Failed to install dependencies... Exit code: 100
Failed to install (Wine) Python 2.7.5... Exit code: 1
Failed to install pywin32-219.win32-py2.7.exe... Exit code: 1
Failed to install pycrypto-2.6.win32-py2.7.exe... Exit code: 1
Failed to install (Wine) Ruby.exe... Exit code: 1
Failed to install (Wine) Ruby OCRA Gem... Exit code: 1
Bad hash for go153x64.tar.gz!


 [I] If you have any errors running Veil-Evasion, delete the Veil Wine profile ('rm -rf /home/saiello/.config/wine/veil') and re-run: '/opt/Veil-Evasion/setup/setup.sh -c'


 [I] Done!

**Comment by ChrisTruncer** [comment]
I'm closing this on here since Veil-Evasion is no longer supported.

The error looks to be due to the setup script specifically looking to support 16.10, but I'm undecided if I want to support the latest version, or LTS version.  I'm leaning towards LTS, but I need to think about it.
