### ISSUE TITLE
no payloads show in list command

### ISSUE THREAD

**Issue by deepgray** [Veil-Framework/Veil-Evasion#451]
## Veil-Evasion version
2.28.2

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2 Rolling amd64

## Expected behavior
modules should show in list.

## Any additional info you want to tell me

installed via git clone.
./Install.sh -c
cd Veil-Evasion
./Veil-Evasion.py
![veil-evasion](https://cloud.githubusercontent.com/assets/14880472/23445461/8fb4482e-fe09-11e6-916e-4590b1200de0.png)

**Comment by ChrisTruncer** [comment]
It should have run during setup, but please run the update.py script, and that should fix your issue.

**Comment by deepgray** [comment]
what happened to the repo? i went to clone it on a fresh build and there is nothing there...

git clone https://github.com/Veil-Framework/Veil.git

**Comment by deepgray** [comment]
executed /root/Desktop/Veil/Veil-Evasion/config/update.py and got the same results...no payloads.

**Comment by ChrisTruncer** [comment]
please try new Veil on Veil repo
