### ISSUE TITLE
##Veil-Evasion Internal error #2. Unable to generate output.

### ISSUE THREAD

**Issue by TowersCr4ck** [Veil-Framework/Veil-Evasion#452]
##  Veil-Evasion | [Version]: 2.28.2
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

 [!] ERROR: Unable to create output file.

 [!] Internal error #2. Unable to generate output. Please run /root/Veil-Evasion/config/update.py manually

 [>] Press any key to return to the main menu.

 [!] Exiting...

**Comment by TowersCr4ck** [comment]
And yes, i update manually the file update.py and same error.

**Comment by ChrisTruncer** [comment]
Veil-Evasion is no longer supported. Please use Veil 3.0
