### ISSUE TITLE
No Distribution Websites are incorrect about their detection?

### ISSUE THREAD

**Issue by mattonfire** [Veil-Framework/Veil-Evasion#453]
Hi, I test the no distribution websites which say there is no issues from any of the programs including Kaspersky, AVG, Windows Defender etc. But when I tested them live none of them worked, they were all detected by all real time anti virus programs. Anyone know why this is, is the type of evasion I used outdated?

**Comment by ChrisTruncer** [comment]
Veil-Evasion is no longer supported, as it says on the front page of this repo. Please use Veil 3.0
