### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by MadzBlind** [Veil-Framework/Veil-Evasion#456]
## Veil-Evasion version
Latest

## OS Used - all info (architecture, linux flavor, etc)

Kali Linux Debian x64
## Pastebin link to error you are encountering (include console actions you took prior to error)
[*] Initializing (Wine) Ruby dependencies installation...

 [*] Installing (Wine) Ruby & dependencies
 [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.

 [*] Installing (Wine) Ruby OCRA gem...
Successfully installed ocra-1.3.0
1 gem installed
Installing ri documentation for ocra-1.3.0...
Installing RDoc documentation for ocra-1.3.0...

 [*] Extracting (Wine) Ruby dependencies...

 [*] Initializing Go dependencies installation...

E: Aucun paquet n'a été trouvé
./setup.sh: ligne 546 : [:  : nombre entier attendu comme expression
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Aucune version du paquet gccgo-5 n'est disponible, mais il existe dans la base
de données. Cela signifie en général que le paquet est manquant, qu'il est devenu obsolète
ou qu'il n'est disponible que sur une autre source
Cependant les paquets suivants le remplacent :
  libgcc-5-dev

E: Le paquet « gccgo-5 » n'a pas de version susceptible d'être installée
update-alternatives: erreur: pas d'alternatives pour go

 [*] Installing Go x86 (via TAR)

 [*] Setttings already detected... Skipping...

  There was issues installing the following:

 
Failed to install dependencies... Exit code: 100
Failed to install SymmetricJSONRPC... Exit code: 100

 [I] If you have any errors running Veil-Evasion, delete the Veil Wine profile ('rm -rf /root/.config/wine/veil') and re-run: '/root/Veil-Evasion/setup/setup.sh -c'

 [I] Done!

root@kali:~/Veil-Evasion/setup# cd ..
root@kali:~/Veil-Evasion# ./Veil-Evasion.py 
=========================================================================
 Necessary component missing
 Please run: bash /root/Veil-Evasion/setup/setup.sh -s
=========================================================================
root@kali:~/Veil-Evasion# 

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
As stated at the very top of this project, Veil-Evasion is no longer supported. Please use Veil 3.0
