### ISSUE TITLE
Error Module 3

### ISSUE THREAD

**Issue by a9v8i** [Veil-Framework/Veil-Evasion#457]
Veil-Evasion | [Version]: 2.28.2
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

 Payload: auxiliary/pyinstaller_wrapper loaded

 Required Options:

 Name			Current Value	Description
 ----			-------------	-----------
 ARCHITECTURE    	32      	Select the final binary architecture (32, 64)
 COMPILE_TO_EXE  	Y       	Compile to an executable
 PYTHON_SOURCE   	        	A Python source file to compile with pyinstaller
 USE_PYHERION    	N       	Use the pyherion encrypter

 Available Commands:

	set         	Set a specific option value
	info        	Show information about the payload
	options     	Show payload's options
	generate    	Generate payload
	back        	Go to the main menu
	exit        	exit Veil-Evasion

 [auxiliary/pyinstaller_wrapper>>]: set PYTHON_SOURCE /root/payload.py
 [*] PYTHON_SOURCE => /root/payload.py
 [auxiliary/pyinstaller_wrapper>>]: set USE_PYHERION Y
 [*] USE_PYHERION => Y
 [auxiliary/pyinstaller_wrapper>>]: generate
Traceback (most recent call last):
  File "./Veil-Evasion.py", line 345, in <module>
    controller.MainMenu(args=args)
  File "/usr/share/veil-evasion/modules/common/controller.py", line 875, in MainMenu
    self.outputFileName = self.PayloadMenu(self.payload, args=args)
  File "/usr/share/veil-evasion/modules/common/controller.py", line 801, in PayloadMenu
    payloadCode = payload.generate()
  File "/usr/share/veil-evasion//modules/payloads/auxiliary/pyinstaller_wrapper.py", line 48, in generate
    PayloadCode = encryption.pyherion(PayloadCode)
  File "/usr/share/veil-evasion/modules/common/encryption.py", line 203, in pyherion
    cipherEnc = AES.new(key)
TypeError: new() takes at least 2 arguments (1 given)

**Comment by ChrisTruncer** [comment]
This Ian no longer supported, please use Veil 3

**Comment by ChrisTruncer** [comment]
This is*

**Comment by Shahidkhanofficial** [comment]
sir am using veil 3 but can't convert my .py into an .exe with pyinstaller_wrapper )-:
