### ISSUE TITLE
Veil says payload generated but no EXE exsists

### ISSUE THREAD

**Issue by zeknox** [Veil-Framework/Veil-Evasion#84]
Updated Veil to the latest version.  Attempted to generate a rev_https_contained payload as seen in the screenshot below.  Veil states everything is all good and even tells me where the EXE is located.

![screen shot 2014-12-11 at 5 57 53 pm](https://cloud.githubusercontent.com/assets/2473269/5404718/8cb7a22a-815f-11e4-9897-e3748cb2a016.png)

However when I take a look at that folder no files seem to exist.

<pre>
root@kali:/usr/share/veil-evasion/compiled# ls -la /usr/share/veil-evasion/compiled/
total 8
drwxr-xr-x 2 root root 4096 Dec 11 18:35 .
drwxr-xr-x 6 root root 4096 Dec 11 18:46 ..
</pre>

**Comment by ChrisTruncer** [comment]
Did that work for you?

**Comment by ChrisTruncer** [comment]
I'm going to go ahead and close this out.  Feel free to respond in here if you still need any help.
