### ISSUE TITLE
Bad VEIL_EVASION_PATH when executing ./config/update.py

### ISSUE THREAD

**Issue by Moloson** [Veil-Framework/Veil-Evasion#92]
There is an error when generating the configuration file using ./config/update.py from the Veil-Evasion folder. When using it, the EVASION_PATH set in the configuration is the parent of the current one leading to an empty list of payloads when executing ./Veil_Evasion.py.

To fix it, just change
```
veil_evasion_path = "/".join(os.getcwd().split("/")[:-1]) + "/"
```

with: 
```
veil_evasion_path =  os.getcwd() + "/"
```

**Comment by ChrisTruncer** [comment]
I see the issue you are talking about, however, we just tell people to move into the config folder and then run the update.py script.  That's how our scripts currently reference it, and how we tell people to run it.  If we were to make the suggested patch, then when people went into the config folder and ran update.py, it would change the veil_evasion_path to be:

 <FULLVEILEVASIONPATH>/config/

**Comment by ChrisTruncer** [comment]
I'm going to go ahead and close this.  If you have a reason to re-open, feel free to add it to here and we'll look at it again.

**Comment by 0xdade** [comment]
When I encountered an error generating a pyinstaller payload, it told me:

 ```
 [!] ERROR: Unable to create output file.

 [!] Internal error #2. Unable to generate output. Please run /usr/share/veil-evasion/config/update.py manually
```

I'd recommend/request updating this class of error messages to ensure users know to run update.py from within the /config/ folder. I got super confused when all my payloads disappeared :)

Thanks.

**Comment by ChrisTruncer** [comment]
Thanks, just a FYI, evasion is no longer supported, as it says on the main git page for it.

Veil 3.0 is now the supported version
