### ISSUE TITLE
Can't Create EXE file

### ISSUE THREAD

**Issue by shakmalik89** [Veil-Framework/Veil-Evasion#95]
Hi,
I signed up on this site for only asking this question that whenever I try to generate an executable file it can't compile the file. The directory  "/usr/share/veil-evasion/compiled/" is empty. Please help me and please tell me what I am doing wrong.
=========================================================================
 Veil-Evasion | [Version]: 2.16.0
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

 Main Menu

	39 payloads loaded

 Available commands:

	use         	use a specific payload
	info        	information on a specific payload
	list        	list available payloads
	update      	update Veil to the latest version
	clean       	clean out payload folders
	checkvt     	check payload hashes vs. VirusTotal
	exit        	exit Veil

 [>] Please enter a command: 26

=========================================================================
 Veil-Evasion | [Version]: 2.16.0
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

 Payload: python/meterpreter/rev_tcp loaded

 Required Options:

 Name			Current Value	Description
 ----			-------------	-----------
 LHOST           	192.168.x.xxx	IP of the metasploit handler
 LPORT           	4444    	Port of the metasploit handler
 compile_to_exe  	Y       	Compile to an executable
 expire_payload  	X       	Optional: Payloads expire after "X" days
 use_pyherion    	N       	Use the pyherion encrypter

 Available commands:

	set         	set a specific option value
	info        	show information about the payload
	generate    	generate payload
	back        	go to the main menu
	exit        	exit Veil

 [>] Please enter a command: generate

=========================================================================
 Veil-Evasion | [Version]: 2.16.0
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

 [*] Press [enter] for 'payload'
 [>] Please enter the base name for output files: AK47

 [?] How would you like to create your payload executable?

     1 - Pyinstaller (default)
     2 - Pwnstaller (obfuscated Pyinstaller loader)
     3 - Py2Exe

 [>] Please enter the number of your choice: 1
err:module:import_dll Library pywintypes27.dll (which is needed by L"C:\\Python27\\lib\\site-packages\\win32\\win32api.pyd") not found
err:module:import_dll Library pywintypes27.dll (which is needed by L"C:\\Python27\\lib\\site-packages\\win32\\win32api.pyd") not found
err:module:import_dll Library pywintypes27.dll (which is needed by L"C:\\Python27\\lib\\site-packages\\win32\\win32api.pyd") not found
err:module:import_dll Library pywintypes27.dll (which is needed by L"C:\\Python27\\lib\\site-packages\\win32\\win32api.pyd") not found
err:module:import_dll Library pywintypes27.dll (which is needed by L"C:\\Python27\\lib\\site-packages\\win32\\win32api.pyd") not found
Error: PyInstaller for Python 2.6+ on Windows needs pywin32.
Please install from http://sourceforge.net/projects/pywin32/
fixme:msvcr90:__clean_type_info_names_internal (0x8c4460) stub
fixme:msvcr90:__clean_type_info_names_internal (0x44ba30) stub
fixme:msvcr90:__clean_type_info_names_internal (0x100554f0) stub
fixme:msvcr90:__clean_type_info_names_internal (0x1d1b5210) stub
fixme:msvcr90:__clean_type_info_names_internal (0x1e24c178) stub
mv: cannot stat `dist/AK47.exe': No such file or directory
rm: cannot remove `*.spec': No such file or directory
rm: cannot remove `logdict*.*': No such file or directory

=========================================================================
 Veil-Evasion | [Version]: 2.16.0
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

 [*] Executable written to: /usr/share/veil-evasion/compiled/AK47.exe

 Language:		python
 Payload:		python/meterpreter/rev_tcp
 Required Options:      LHOST=192.168.1.105  LPORT=4444  compile_to_exe=Y
                        expire_payload=X  use_pyherion=N
 Payload File:		/usr/share/veil-evasion/source/AK47.py
 Handler File:		/usr/share/veil-evasion/handlers/AK47_handler.rc

 [!] Please run ./config/update.py !
 [*] Your payload files have been generated, don't get caught!
 [!] And don't submit samples to any online scanner! ;)

 [>] press any key to return to the main menu:

**Comment by ChrisTruncer** [comment]
Hi there,

It looks like you probably didn't run the setup script, because it seems like python can't be found in wine.  I just tested the same payload on my machine, and had a friend test it as well, and everything works for both of our systems.

**Comment by shakmalik89** [comment]
Now what to do ?

**Comment by ChrisTruncer** [comment]
Run the setup script

**Comment by shakmalik89** [comment]
I have already done while installing veil

**Comment by ChrisTruncer** [comment]
It sounds like it is something isolated to your machine.  I'd check to see if everything in your install worked correctly, because it seems like you are missing certain packages.  Worst case, try it in a different VM.  Wish I had a better answer for you, but I can't seem to re-create it here with my laptop, or anyone else's around me.

**Comment by shakmalik89** [comment]
Doen not worked for me

**Comment by AbuDinz** [comment]
How to fix:

Execute these commands

1. rm -fr /home/.wine

2. WINEARCH=win32 winecfg
   - then chose the setting for the default Windows type -> ex: Windows 7

3. dpkg --add-architecture i386 && apt-get update && apt-get install wine32

4. veil-evasion
   - follow the steps... installing python etc...

**Comment by wifiuk** [comment]
i get the same issues, even when following the How to fix above.

`err:module:import_dll Library pywintypes27.dll (which is needed by L"C:\\Python27\\lib\\site-packages\\win32\\win32api.pyd") not found
err:module:import_dll Library pywintypes27.dll (which is needed by L"C:\\Python27\\lib\\site-packages\\win32\\win32api.pyd") not found
err:module:import_dll Library pywintypes27.dll (which is needed by L"C:\\Python27\\lib\\site-packages\\win32\\win32api.pyd") not found
err:module:import_dll Library pywintypes27.dll (which is needed by L"C:\\Python27\\lib\\site-packages\\win32\\win32api.pyd") not found
Traceback (most recent call last):
  File "/usr/share/veil/pyinstaller//pyinstaller.py", line 14, in <module>
    from PyInstaller.__main__ import run
  File "Z:\usr\share\veil\pyinstaller\PyInstaller\__main__.py", line 21, in <module>
    import PyInstaller.building.build_main
  File "Z:\usr\share\veil\pyinstaller\PyInstaller\building\build_main.py", line 32, in <module>
    from ..depend import bindepend
  File "Z:\usr\share\veil\pyinstaller\PyInstaller\depend\bindepend.py", line 38, in <module>
    from ..utils.win32.winmanifest import RT_MANIFEST
  File "Z:\usr\share\veil\pyinstaller\PyInstaller\utils\win32\winmanifest.py", line 97, in <module>
    from PyInstaller.utils.win32 import winresource
  File "Z:\usr\share\veil\pyinstaller\PyInstaller\utils\win32\winresource.py", line 20, in <module>
    import pywintypes
  File "C:\Python27\lib\site-packages\win32\lib\pywintypes.py", line 124, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Python27\lib\site-packages\win32\lib\pywintypes.py", line 98, in __import_pywin32_system_module__
    raise ImportError("No system module '%s' (%s)" % (modname, filename))
ImportError: No system module 'pywintypes' (pywintypes27.dll)

=========================================================================
 Veil-Evasion | [Version]: 2.28.2
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

 [!] ERROR: Unable to create output file.

 [!] Internal error #2. Unable to generate output. Please run /usr/share/veil-evasion/config/update.py manually

 [>] Press any key to return to the main menu.
`

**Comment by veil-evasion** [comment]
Please rerun the setup script with -c
